### ISSUE TITLE
fdk-aac... requires version <= 0.1.6, found 2.0.1

### ISSUE THREAD

**Issue by hmorneau** [savonet/liquidsoap#1117] opened 2020-03-21 21:16 UTC
It seems like liquidsoap need fdk-aac 0.1.6. The latest version is 2.0.1, that's the only version available on alpine. Any plan to update this?

Thank you.

**Comment by smimram** [comment] 2020-03-22 08:51
No, this is not the case, I am compiling with 2.0.1 here. What makes you think that an old version is required exactly? Please show us the precise error you have.

**Comment by hmorneau** [comment] 2020-03-22 12:01
While trying to install 1.4.1
#=== ERROR while compiling fdkaac.0.3.1 =======================================#
# context              2.0.5 | linux/x86_64 | ocaml-system.4.08.1 | https://opam.ocaml.org#08f6512d
# path                 /usr/local/opam/default/.opam-switch/build/fdkaac.0.3.1
# command              /usr/local/opam/default/.opam-switch/build/fdkaac.0.3.1/./configure --prefix=/usr/local/opam/default
# exit-code            1
# env-file             /usr/local/opam/log/fdkaac-67-65bd14.env
# output-file          /usr/local/opam/log/fdkaac-67-65bd14.out
### output ###
# [...]
# checking for camlp4orf... no
# checking for camlp4prof... no
# checking for camlp4r... no
# checking for camlp4rf... no
# checking for ocamlfind... ocamlfind
# checking for ocaml standard library path... /usr/lib/ocaml
# checking for caml/threads.h... yes
# checking for gcc option to produce PIC... -fPIC
# checking whether to build shared modules... yes
# checking for pkg-config... /usr/bin/pkg-config
# checking pkg-config is at least version 0.9.0... yes
# checking whether pkg-config knows about fdk-aac... configure: error: requires version <= 0.1.6, found 2.0.1

**Comment by smimram** [comment] 2020-03-22 13:26
Ok you're right, this was fixed in https://github.com/savonet/ocaml-fdkaac/commit/3317881c1ca327ddda795cbd19f507ef89471085 which was not released yet.

@toots shall we make a new release?

**Comment by toots** [comment] 2020-03-22 22:49
The problem is that debian sid is still stuck with `0.1.6`..

**Comment by smimram** [comment] 2020-03-23 07:49
No chance to make something working for both 0.1.6 and 2.0.1?

**Comment by toots** [comment] 2020-03-23 15:29
I'll look at it.

**Comment by toots** [comment] 2020-03-27 22:33
Well, surprisingly, the latest `master` seems to work just fine with both versions.. Releasing!

**Closed** 2020-03-27 22:46 UTC
