### ISSUE TITLE
on_blank script 

### ISSUE THREAD

**Issue by CharlesOnAir** [savonet/liquidsoap#1473] opened 2021-01-14 14:25 UTC
Hello,

I would like to run a Python script when triggering the rescue file.

Here is my code

But the script is not taken into account

def handler()
                    system("../var/www/html/secoursfiles/TestSecours.py")
                end
                
                stream = fallback(track_sensitive=false, [ strip_blank(max_blank=5.,flux) , security ])

                stream = on_blank(handler,stream)

**Comment by toots** [comment] 2021-01-14 14:57
Duplicate of #1474

**Closed by toots** 2021-01-14 14:57 UTC
Labels: usage
