### ISSUE TITLE
Increased CPU usage over time leading to high latency, catchup, and resetting sources

### ISSUE THREAD

**Issue by dmccombs** [savonet/liquidsoap#4187] opened 2024-10-23 00:39 UTC
### Description

Over time releases of Liquidsoap 2.x steadily use more and more CPU until "Too much latency"  and catchup warnings start filling the logs, leading to resetting active sources repeatedly. This happens after a couple of weeks of instances running, whereas it didn't happen on Liquidsoap 1.x in largely the same configuration running for years.

Logs are hundreds of MB in size after a month, but some sample log lines are:
```
2024/10/23 00:00:39 [clock.generic:2] We must catchup 45.31 seconds!
2024/10/23 00:00:40 [clock.generic:2] We must catchup 45.88 seconds!
2024/10/23 00:00:41 [clock.generic:2] We must catchup 46.53 seconds!
2024/10/23 00:00:41 [clock.generic.2:2] We must catchup 47.27 seconds!
2024/10/23 00:00:42 [clock.generic:2] We must catchup 47.22 seconds!
2024/10/23 00:00:42 [clock.generic.2:2] We must catchup 48.30 seconds!
2024/10/23 00:00:43 [clock.generic:2] We must catchup 47.95 seconds!
2024/10/23 00:00:43 [clock.generic.2:2] We must catchup 49.22 seconds!
2024/10/23 00:00:44 [clock.generic:2] We must catchup 48.48 seconds!
2024/10/23 00:00:44 [clock.generic.2:2] We must catchup 50.05 seconds!
```
```
2024/10/22 23:46:44 [clock.generic.2:2] Too much latency! Resetting active sources...
2024/10/22 23:49:01 [clock.generic.2:2] Too much latency! Resetting active sources...
2024/10/22 23:51:02 [clock.generic.2:2] Too much latency! Resetting active sources...
2024/10/22 23:53:34 [clock.generic.2:2] Too much latency! Resetting active sources...
2024/10/22 23:55:32 [clock.generic.2:2] Too much latency! Resetting active sources...
2024/10/22 23:56:46 [clock.generic.2:2] Too much latency! Resetting active sources...
```

Restarting the instances clears the issue for another couple of weeks, and resets CPU usage down to ~10%, before it climbs back to 100% over time.

These are metrics showing the state the system was in after a month of running, then the reset when liquidsoap was restarted:
![shot-2024-10-22_20-10-41](https://github.com/user-attachments/assets/b056ec73-31a7-446c-b98f-49c1b4126f45)

This has happened both when running 1 instance of Liquidsoap with 3 playlists in it, and also when running 3 separate instances of Liquidsoap with 1 playlist in each.

Here's one of the 3 scripts, the problem happens with or without the `buffer()` around the playlist in the output:
```
#!/usr/bin/liquidsoap
set("log.file.path", "/var/log/liquidsoap/echoesofbluemars.log")

set("server.socket", true)
set("server.socket.path", "/sockets/echoes_socket-bluemars")
set("server.socket.permissions", 432)

# Enable replaygain use to normalize volume
enable_replaygain_metadata ()

# Music
bmplaylist = playlist(reload_mode='watch', mode='randomize', prefetch=9, "/music/bm-playlist.m3u")

# Bluemars
output.icecast(%mp3,
        host = "localhost",
        port = 8000,
        password = "<REDACTED>",
        mount = "bluemars",
        fallible = true,
        name = "Echoes of BLUEMARS",
        description = "Music For the Space Traveler",
        genre = "Ambient",
        url = "http://www.echoesofbluemars.org",
        buffer(max=60.0, crossfade(replaygain(bmplaylist))))
```

### Steps to reproduce

Run the above script for weeks and observe CPU usage increasing over time. The playlist used has 372 tracks on it, all with replaygain already computed and tagged in the files.

### Expected behavior

Liquidsoap should use a steady amount of CPU over time, and not need restarts to continue to run normally.

### Liquidsoap version

```text
Liquidsoap 2.3.0+git@24f373365
Copyright (c) 2003-2024 Savonet team
Liquidsoap is open-source software, released under GNU General Public License.
See <http://liquidsoap.info> for more information.
```

### Liquidsoap build config

```text
* Liquidsoap version  : 2.3.0+git@24f373365

 * Compilation options
   - Release build       : false
   - Git SHA             : 24f373365
   - OCaml version       : 4.14.2
   - OS type             : Unix
   - Libs versions       : alsa=0.3.0 angstrom=0.16.0 ao=0.2.4 asetmap=0.8.1 asn1-combinators=0.2.6 astring=0.8.5 base=v0.16.3 base.base_internalhash_types=v0.16.3 base.caml=v0.16.3 base.shadow_stdlib=v0.16.3 base64=3.5.1 bigarray=[distributed with Ocaml] bigarray-compat=1.1.0 bigstringaf=0.9.1 bjack=0.1.6 bos=0.2.1 bytes=[distributed with OCaml 4.02 or above] ca-certs=v0.2.3 camlp-streams camomile.lib=2.0 cohttp=5.3.1 cohttp-lwt=5.3.0 cohttp-lwt-unix=5.3.0 conduit=6.2.3 conduit-lwt=6.2.3 conduit-lwt-unix=6.2.3 cry=1.0.3 cstruct=6.2.0 ctypes=0.22.0 ctypes-foreign=0.22.0 ctypes.stubs=0.22.0 curl=0.9.2 domain-name=0.4.0 domain_shims dssi=0.1.5 dtools=0.4.5 dune-build-info=3.16.0 dune-private-libs.dune-section=3.16.0 dune-site=3.16.0 dune-site.private=3.16.0 duppy=0.9.4 eqaf=0.9 eqaf.bigstring=0.9 eqaf.cstruct=0.9 faad=0.5.2 fdkaac=0.3.3 ffmpeg-av=1.2.0 ffmpeg-avcodec=1.2.0 ffmpeg-avdevice=1.2.0 ffmpeg-avfilter=1.2.0 ffmpeg-avutil=1.2.0 ffmpeg-swresample=1.2.0 ffmpeg-swscale=1.2.0 fileutils=0.6.4 flac=0.5.1 flac.decoder=0.5.1 flac.ogg=0.5.1 fmt=0.9.0 fpath=0.7.3 frei0r=0.1.2 gd=1.1 gen=1.1 gmap=0.3.0 hkdf=1.0.4 inotify=2.0-62-g5e58536 integers ipaddr=5.6.0 ipaddr-sexp=5.6.0 ipaddr.unix=5.6.0 irc-client irc-client-unix ladspa=0.2.2 lame=0.3.7 lastfm=0.3.4 lilv=0.2.0 liquidsoap-lang=2.3.0 liquidsoap-lang.console=2.3.0 liquidsoap_alsa=rolling-release-v2.3.x-1-g24f3733 liquidsoap_ao=rolling-release-v2.3.x-1-g24f3733 liquidsoap_bjack=rolling-release-v2.3.x-1-g24f3733 liquidsoap_builtins=rolling-release-v2.3.x-1-g24f3733 liquidsoap_core=rolling-release-v2.3.x-1-g24f3733 liquidsoap_dssi=rolling-release-v2.3.x-1-g24f3733 liquidsoap_faad=rolling-release-v2.3.x-1-g24f3733 liquidsoap_fdkaac=rolling-release-v2.3.x-1-g24f3733 liquidsoap_ffmpeg=rolling-release-v2.3.x-1-g24f3733 liquidsoap_flac=rolling-release-v2.3.x-1-g24f3733 liquidsoap_frei0r=rolling-release-v2.3.x-1-g24f3733 liquidsoap_gd=rolling-release-v2.3.x-1-g24f3733 liquidsoap_irc=rolling-release-v2.3.x-1-g24f3733 liquidsoap_ladspa=rolling-release-v2.3.x-1-g24f3733 liquidsoap_lame=rolling-release-v2.3.x-1-g24f3733 liquidsoap_lastfm=rolling-release-v2.3.x-1-g24f3733 liquidsoap_lilv=rolling-release-v2.3.x-1-g24f3733 liquidsoap_lo=rolling-release-v2.3.x-1-g24f3733 liquidsoap_mad=rolling-release-v2.3.x-1-g24f3733 liquidsoap_ogg=rolling-release-v2.3.x-1-g24f3733 liquidsoap_ogg_flac=rolling-release-v2.3.x-1-g24f3733 liquidsoap_optionals=rolling-release-v2.3.x-1-g24f3733 liquidsoap_opus=rolling-release-v2.3.x-1-g24f3733 liquidsoap_osc=rolling-release-v2.3.x-1-g24f3733 liquidsoap_oss=rolling-release-v2.3.x-1-g24f3733 liquidsoap_portaudio=rolling-release-v2.3.x-1-g24f3733 liquidsoap_posix_time=rolling-release-v2.3.x-1-g24f3733 liquidsoap_prometheus=rolling-release-v2.3.x-1-g24f3733 liquidsoap_pulseaudio=rolling-release-v2.3.x-1-g24f3733 liquidsoap_runtime=rolling-release-v2.3.x-1-g24f3733 liquidsoap_samplerate=rolling-release-v2.3.x-1-g24f3733 liquidsoap_sdl=rolling-release-v2.3.x-1-g24f3733 liquidsoap_sdl_log_level=rolling-release-v2.3.x-1-g24f3733 liquidsoap_shine=rolling-release-v2.3.x-1-g24f3733 liquidsoap_soundtouch=rolling-release-v2.3.x-1-g24f3733 liquidsoap_speex=rolling-release-v2.3.x-1-g24f3733 liquidsoap_sqlite=rolling-release-v2.3.x-1-g24f3733 liquidsoap_srt=rolling-release-v2.3.x-1-g24f3733 liquidsoap_ssl=rolling-release-v2.3.x-1-g24f3733 liquidsoap_stdlib=rolling-release-v2.3.x-1-g24f3733 liquidsoap_stereotool=rolling-release-v2.3.x-1-g24f3733 liquidsoap_theora=rolling-release-v2.3.x-1-g24f3733 liquidsoap_tls=rolling-release-v2.3.x-1-g24f3733 liquidsoap_vorbis=rolling-release-v2.3.x-1-g24f3733 liquidsoap_xmlplaylist=rolling-release-v2.3.x-1-g24f3733 liquidsoap_yaml=rolling-release-v2.3.x-1-g24f3733 lo=0.2.0 logs=0.7.0 logs.fmt=0.7.0 logs.lwt=0.7.0 lwt=5.7.0 lwt.unix=5.7.0 macaddr=5.6.0 mad=0.5.3 magic-mime=1.3.1 mem_usage=0.1.1 memtrace=0.2.3 menhirLib=20231231 metadata=0.3.0 mirage-crypto=0.11.3 mirage-crypto-ec=0.11.3 mirage-crypto-pk=0.11.3 mirage-crypto-rng=0.11.3 mirage-crypto-rng.unix=0.11.3 mm=0.8.5 mm.audio=0.8.5 mm.base=0.8.5 mm.image=0.8.5 mm.midi=0.8.5 mm.video=0.8.5 ocplib-endian ocplib-endian.bigstring ogg=0.7.4 ogg.decoder=0.7.4 opus=0.2.3 opus.decoder=0.2.3 osc osc-unix parsexp=v0.16.0 pbkdf portaudio=0.2.3 posix-base=5a7f328 posix-socket=5a7f328 posix-socket.constants=5a7f328 posix-socket.stubs=5a7f328 posix-socket.types=5a7f328 posix-time2=5a7f328 posix-time2.constants=5a7f328 posix-time2.stubs=5a7f328 posix-time2.types=5a7f328 posix-types=5a7f328 posix-types.constants=5a7f328 ppx_compare.runtime-lib=v0.16.0 ppx_hash.runtime-lib=v0.16.0 ppx_sexp_conv.runtime-lib=v0.16.0 prometheus=1.2 prometheus-app=1.2 ptime=1.1.0 ptime.clock.os=1.1.0 pulseaudio=0.1.6 re=1.11.0 result=1.5 rresult=0.7.0 samplerate=0.1.7 saturn_lockfree=0.4.1 sedlex=3.2 seq=[distributed with OCaml 4.07 or above] sexplib=v0.16.0 sexplib0=v0.16.0 shine=0.2.3 soundtouch=0.1.9 speex=0.4.2 speex.decoder=0.4.2 sqlite3=5.1.0 srt=0.3.1 srt.constants=0.3.1 srt.stubs=0.3.1 srt.stubs.locked=0.3.1 srt.types=0.3.1 ssl=0.7.0 stdlib-shims=0.3.0 stereotool=rolling-release-v2.3.x-1-g24f3733 str=[distributed with Ocaml] stringext=1.6.0 theora=0.4.1 theora.decoder=0.4.1 threads=[distributed with Ocaml] threads.posix=[internal] tls=0.17.4 tsdl=v1.0.0 tsdl-image=0.5 tsdl-ttf=0.6 unix=[distributed with Ocaml] unix-errno=52c6ecb unix-errno.errno_bindings=52c6ecb unix-errno.errno_types=52c6ecb unix-errno.errno_types_detected=52c6ecb unix-errno.unix=52c6ecb uri=4.4.0 uri-sexp=4.4.0 uri.services=4.4.0 vorbis=0.8.1 vorbis.decoder=0.8.1 x509=0.16.5 xmlm=1.4.0 xmlplaylist=0.1.5 yaml=3.2.0 yaml.bindings=3.2.0 yaml.bindings.types=3.2.0 yaml.c=3.2.0 yaml.ffi=3.2.0 yaml.types=3.2.0 zarith=1.13
   - architecture        : amd64
   - host                : x86_64-pc-linux-gnu
   - target              : x86_64-pc-linux-gnu
   - system              : linux
   - ocamlopt_cflags     : -O2 -fno-strict-aliasing -fwrapv -pthread -fPIC
   - native_c_compiler   : gcc -O2 -fno-strict-aliasing -fwrapv -pthread -fPIC -D_FILE_OFFSET_BITS=64
   - native_c_libraries  : -lm

 * Configured paths
   - mode              : posix
   - standard library  : /usr/share/liquidsoap/libs
   - scripted binaries : /usr/share/liquidsoap/bin
   - rundir            : /var/run/liquidsoap
   - logdir            : /var/log/liquidsoap
   - user cache        : $HOME/.cache/liquidsoap (override with $LIQ_CACHE_USER_DIR)
   - system cache      : /var/cache/liquidsoap (override with $LIQ_CACHE_SYSTEM_DIR)
   - camomile files    : /usr/share/liquidsoap/camomile

 * Supported input formats
   - MP3               : yes
   - AAC               : yes
   - Ffmpeg            : yes
   - Flac (native)     : yes
   - Flac (ogg)        : yes
   - Opus              : yes
   - Speex             : yes
   - Theora            : yes
   - Vorbis            : yes
   - WAV/AIFF          : yes (native)

 * Supported output formats
   - FDK-AAC           : yes
   - FFmpeg            : yes
   - MP3               : yes
   - MP3 (fixed-point) : yes
   - Flac (native)     : yes
   - Flac (ogg)        : yes
   - Opus              : yes
   - Speex             : yes
   - Theora            : yes
   - Vorbis            : yes
   - WAV/AIFF          : yes (native)

 * Tags
   - AAC               : yes
   - FFmpeg            : yes
   - FLAC (native)     : yes
   - Flac (ogg)        : yes
   - Native decoder    : yes
   - Vorbis            : yes

 * Input / output
   - ALSA              : yes
   - AO                : yes
   - FFmpeg            : yes
   - JACK              : yes
   - OSS               : yes
   - Portaudio         : yes
   - Pulseaudio        : yes
   - SRT               : yes

 * Audio manipulation
   - FFmpeg            : yes
   - LADSPA            : yes
   - Lilv              : yes
   - Samplerate        : yes
   - SoundTouch        : yes
   - StereoTool        : yes

 * Video manipulation
   - camlimages        : no (requires camlimages)
   - FFmpeg            : yes
   - frei0r            : yes
   - ImageLib          : no (requires imagelib)
   - SDL               : yes

 * MIDI manipulation
   - DSSI              : yes

 * Visualization
   - GD                : yes
   - Graphics          : no (requires graphics)
   - SDL               : yes

 * Additional libraries
   - FFmpeg filters    : yes
   - FFmpeg devices    : yes
   - inotify           : yes
   - irc               : yes
   - jemalloc          : no (requires jemalloc)
   - lastfm            : yes
   - lo                : yes
   - memtrace          : no (requires memtrace)
   - osc               : yes
   - ssl               : yes
   - sqlite3           : yes
   - tls               : yes
   - posix-time2       : yes
   - windows service   : no (requires winsvc)
   - YAML support      : yes
   - XML playlists     : yes

 * Monitoring
   - Prometheus        : yes
```

### Installation method

From official packages in the release artifacts

### Additional Info

Happy to provide any additional info that might help track this down, as it's prevented me from upgrading my production instances to Liquidsoap 2.x for over a year.

**Comment by toots** [comment] 2024-10-23 03:21
Thanks for this report! I will prioritize fixing it.

I have an ongoing PR fixing some serious performance issues around `source.drop`, which is the operator used to compute data on the files to get `replaygain` information. 

I was wondering:
* Do you know if computation happens on the sources related to replaygain data? Typically you would see logs of the form: 
```
2024/10/22 16:44:04 [source.drop:4] Start dropping source (ratio: 50.00x)
```
* If that is the case then I would recommend trying again once https://github.com/savonet/liquidsoap/pull/4184 has landed.

I'll make sure to ping y'all again by them!

**Comment by dmccombs** [comment] 2024-10-23 12:59
Thanks @toots!

Grepping the ~700MB of logs I have from this last run with this issue there's no instances of `source.drop` or `dropping`.

**Comment by toots** [comment] 2024-10-23 13:52
Hi @dmccombs ok thanks and, damn!

I just merged the PR in question and pushed a new build with it to the `rolling-release-v2.3.x` branch.

I'm gonna try and see if I can reproduce your issue. How long does it take for you to start seeing the CPU increase?

**Comment by dmccombs** [comment] 2024-10-23 14:03
@toots it's varied between days, weeks, or even a couple of months before I started seeing the log errors since I've been dealing with it, but that's across different 2.x versions and I hadn't been looking at CPU metrics directly to see when they started to climb before errors started showing up.

Last night was the first time I've restarted the 2.3.0 build I'm on since having the problem. I'll keep a closer eye on CPU use and let you know when I start seeing it climb again.

**Comment by dmccombs** [comment] 2024-10-26 18:50
![shot-2024-10-26_14-48-42](https://github.com/user-attachments/assets/9dd19a68-acce-4e60-b779-b73561162d14)

So far, it looks like just a slow and steady climb. After restarting just under 4 days ago, it's gone from a little over 10% CPU usage up to a little over 20%. I'll continue to watch it.

**Comment by toots** [comment] 2024-10-26 18:54
Ok thanks. If you can detect the issue over a short amount of time, it could also be nice to try and remove features to see if it can be pinned down. I can think of:
* Trying without replaygain
* Trying without amplify
* Trying without `crossfade`
* Trying without a `buffer`

This way we might be able to focus on a specific part of the application logic.

**Comment by dmccombs** [comment] 2024-10-26 18:57
Yeah, I can try turning one thing off at a time and see - at the least I don't think it's `buffer`, as I only added that in an attempt to help things at some point after I was already having the problem. I'll try turning off one feature and restarting things, and seeing where CPU usage is at in 4 days.

**Comment by toots** [comment] 2024-10-27 14:52
Thanks for that! Also, if possible, could you monitor memory usage as well? With OCaml, memory and CPU usage can be correlated too.

**Comment by dmccombs** [comment] 2024-10-30 13:43
Looking back when the CPU was steadily increasing, memory stayed pretty consistent. It's now been 4 days since I restarted liquidsoap on Oct 26th with `crossfade` removed from the config but everything else left in place, and CPU hasn't been inching up, so it seems like that might be a clue as to the culprit. I'll keep monitoring it but hopefully that's a starting point. Let me know if there's anything else I can do to help gather more information!

![shot-2024-10-30_09-39-30](https://github.com/user-attachments/assets/bbc10a27-3c83-48f5-8737-9733a7fcfe21)

**Comment by toots** [comment] 2024-11-01 17:03
Any chance you might be able to test with the changes at https://github.com/savonet/liquidsoap/pull/4198 ?

The binary packages are available here: https://github.com/savonet/liquidsoap/actions/runs/11632224590

The docker images (amd64 only) are here: 
* `savonet/liquidsoap-ci-build:weak-queue-passive-clocks_amd64`
* `savonet/liquidsoap-ci-build:weak-queue-passive-clocks-minimal`
* `savonet/liquidsoap-ci-build:weak-queue-passive-clocks_alpine_amd64`
* `savonet/liquidsoap-ci-build:weak-queue-passive-clocks-minimal_alpine_amd64`

**Comment by toots** [comment] 2024-11-01 22:40
Ok I have merge those changes to `main` and `rolling-release-v2.3.x` after some cleanup. It would be great if you test with the latest build when it comes out..

**Comment by dmccombs** [comment] 2024-11-02 12:20
I checked in again before updating and restarting, and after 7 days CPU usage had not climbed with `crossfade` disabled:
![shot-2024-11-02_07-05-18](https://github.com/user-attachments/assets/ae707254-51af-4721-b199-87796bdf1dc0)

I've updated to `liquidsoap-63abaa4_2.3.0-ubuntu-noble-1_amd64.deb`, added `crossfade` back in, and restarted the instances, I'll check back in a few days to see how CPU is looking.

**Comment by toots** [comment] 2024-11-05 17:52
Hi! Any update on this? From what I can see from another user, the latest `main` and `rolling-release-v2.3.x` did help but not fix everything.

One thing you could try if the bug is confirmed still present is run with memtrace to get a trace of memory usage.

To enable you simply need to set `MEMTRACE=/tmp/trace.ctf`.

You let it run for a while and then collect the file and send it to us.

If the instance is running inside a docker container you can do:
```
docker cp <container ID>:/tmp/trace.ctf /tmp
```

**Comment by dmccombs** [comment] 2024-11-05 21:14
Hey @toots!

It is indeed still there, CPU usage is climbing again:
![shot-2024-11-05_16-12-29](https://github.com/user-attachments/assets/fbbab534-54bf-4bcc-a19c-dbb45f739f4a)

That tracing is built into liquidsoap? Do I just need to have that environment variable set when liquidsoap starts up? How long do you think is a reasonable while for it to run to be useful?

**Comment by toots** [comment] 2024-11-05 21:40
> Hey @toots!
> 
> It is indeed still there, CPU usage is climbing again: ![shot-2024-11-05_16-12-29](https://private-user-images.githubusercontent.com/403277/383317718-fbbab534-54bf-4bcc-a19c-dbb45f739f4a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4NDMwOTksIm5iZiI6MTczMDg0Mjc5OSwicGF0aCI6Ii80MDMyNzcvMzgzMzE3NzE4LWZiYmFiNTM0LTU0YmYtNGJjYy1hMTljLWRiYjQ1ZjczOWY0YS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNVQyMTM5NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04Y2NkY2Q1Y2M3MzRmOTgzYWExMTNmMWE5MTViZTAxOWY1ZTgzZTcwMzk0ODJiYjZkN2NhNWVjYzE1YWNmZDk4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.jqLoLNXTaZpXmqT6Kw_N701y4yKp2isB5IS7iZrYc2c)
> 
> That tracing is built into liquidsoap? Do I just need to have that environment variable set when liquidsoap starts up? How long do you think is a reasonable while for it to run to be useful?

Our builds have it by default. I'd say, this window above is about the time it would take to see anything I imagine.

**Comment by dmccombs** [comment] 2024-11-06 18:11
I've added that environment variable, restarted my instances of liquidsoap, and confirmed that `/tmp/trace.ctf` now exists in each container. I'll give it a few days until I see the CPU clearing ramping up again and then post those files here or send them to you in another way, just let me know.

**Comment by toots** [comment] 2024-11-09 18:59
Hi! Any update on that trace? 🙂

**Comment by dmccombs** [comment] 2024-11-09 21:14
Hi @toots! Here's the current ramp of CPU usage:
![shot-2024-11-09_16-09-04](https://github.com/user-attachments/assets/17ad3e78-d6df-4db5-bec2-1fcdb6781af8)

Here's the 3 trace files from all 3 instances.
[traces-bluemars.zip](https://github.com/user-attachments/files/17689408/traces-bluemars.zip)

**Comment by toots** [comment] 2024-11-09 22:53
Thanks! I was able to see much but I did some local tests with a more intrusive setting for `memtrace` (it only captures a very small fraction of the memory allocation by default) and was able to detect more memory leaks related to server commands registration: https://github.com/savonet/liquidsoap/pull/4206

This is building in the `rolling-release-v2.3.x` branch now. Maybe you can give it a try when it's ready?

Thanks for your patience!

**Comment by dmccombs** [comment] 2024-11-10 02:21
@toots hmm, I can check more tomorrow, but at an initial test with build `ccbd0ef` if I pass in my script it hangs on start. It never connects to icecast, and also never creates the log file or outputs anything on stdout/stderr even if I include the `--debug` parameter. :thinking:

**Comment by toots** [comment] 2024-11-10 17:50
Hmm that's odd. An initial hang on start is expected. I cannot reproduce here. Do you have a log of the issue? Maybe also a `gdb` trace of the threads while it hangs?

**Comment by dmccombs** [comment] 2024-11-11 03:00
It's odd, when I run `liquidsoap --help` I get normal help output, if I pass it an invalid script file I get a syntax error message, but if I pass my script file that I listed at the start of this Github issue, liquidsoap hangs with no output at all, no log file is even created, and no connection is made to icecast. After waiting hours, there's no output. I even tried jumping back to version `liquidsoap-63abaa4_2.3.0-ubuntu-noble-1_amd64.deb` to make sure something else didn't get changed in my configuration, but that version still starts normally.

Here's the output of `thread apply all bt` from inside `gdb` attached to the hung liquidsoap process from the `ccbd0ef` build. Hopefully it's useful in some way:
[liquidsoap-hung-gdb.txt](https://github.com/user-attachments/files/17694617/liquidsoap-hung-gdb.txt)

**Comment by toots** [comment] 2024-11-11 14:54
Yeah I see what's happening. Looks like the process to dump all the source's content gets started too early when the rest of the infrastructure (wokers, queues etc) is not there.

I pushed a commit to make sure this does not happen. There's a rolling release build coming up here: https://github.com/savonet/liquidsoap/actions/runs/11780880881

**Comment by toots** [comment] 2024-11-11 23:56
Great! Fingers crossed now.

**Comment by toots** [comment] 2024-11-14 14:41
Hi! Any update on the CPU usage? I think I'm ready to have a `rc2` if this issue is confirmed fixed.

**Comment by dmccombs** [comment] 2024-11-15 00:32
![shot-2024-11-14_19-26-49](https://github.com/user-attachments/assets/94f9c5e8-21f4-4ecc-9107-62e67dcfe89b)

So, since I updated to the most recent build we were trying on the 11th, CPU usage isn't showing signs up ramping up - if anything it actually dropped off some earlier today for some reason.

I don't see any instances of `catchup` in the logs of any of the instances either, icecast info is populated, and listening is working. So far no signs of trouble! :crossed_fingers: I'll keep an eye on it longer of course, but I think this is ready for rc2!

**Comment by toots** [comment] 2024-11-15 03:15
Awesome news thank you so much for your patience!

**Closed by toots** 2024-11-15 03:15 UTC
Labels: bug

**Comment by dmccombs** [comment] 2024-11-23 21:07
![shot-2024-11-23_16-05-52](https://github.com/user-attachments/assets/a9f2eca5-55a1-49e5-b453-79c81bab2012)

Just wanted to check in and say that 11 days since restarting the instances, CPU usage hasn't climbed, so I'm pretty comfortable saying this is really taken care of now. Thanks again @toots!
