### ISSUE TITLE
Make playlist not pick the same file twice in a row (check_next)

### ISSUE THREAD

**Issue by giflw** [savonet/liquidsoap#197] opened 2014-11-07 02:54 UTC
Playlist in `random` could not pick the same file twice in a row. This behavior could be default or setted by parameter. This is really interesting when the size of playlist is small, increasing the changes of repetition.

**Comment by giflw** [comment] 2015-04-10 05:48
Hi!

I finally had some time to compile and test this. I used your suggestion for check_next, but when it returns false, the playlist do not try to load a new track, but freezes instead. There was 2 songs on the playlist. Below is my test script:

```
set("log.file.path", "/tmp/music.log")
%include "~/Binaries/LiquidSoap/liquidsoap-full/liquidsoap/scripts/utils.liq"

prev = ref("")
def check_next(r)
  metadata = request.metadata(r)
  print("PLAYLIST #{prev} -> #{metadata['filename']}")
  if metadata["filename"] == "" then true else
    if metadata["filename"] == !prev then false else
      prev := metadata["filename"]
      true
    end
  end
end

out(playlist(check_next=check_next, "/tmp/music"))
```

**Comment by dbaelde** [comment] 2015-08-26 12:53
Sorry for the delay in getting back to you. I cannot reproduce the problem yet, but I think I see the problem: thanks.

**Comment by dbaelde** [comment] 2015-08-26 19:27
For the record I could actually reproduce easily by rejecting every other request.
```
prev = ref(false)
def check_next(r)
  prev := not(!prev)
  !prev
end
out(playlist(length=1.,check_next=check_next,"/tmp/playlist"))
```
I also used two files in the playlist directory, or reasonable length: about two minutes. The key is to skip, as in your example: in my first attempt I used short files and let them end normally. After the first skip it freezes systematically. I also noted that reloading the playlist (via telnet) unfreezes it.

**Comment by dbaelde** [comment] 2015-08-26 20:02
Okay the issue is fixed in a new commit in the LS-197 branch. Tell me if it works for you, anyway I'll have to double check this after some sleep. Also, this issue makes me think that it may be more natural to implement check_next using deeper hooks, which will have the side effect of working not only for local files.

By the way, I do not like the idea of adding a parameter for check_next that indicates the length of the playlist: it feels ad-hoc. However, we could consider putting this kind of info as part of the request metadata?

**Comment by giflw** [comment] 2015-08-28 04:18
Is this new option added to playlist.reloadable to?

**Comment by dbaelde** [comment] 2015-08-28 06:37
The `playlist.reloadable` source builds on `request.dynamic`, to which I did not add `check_next`.

I would not consider adding the same `check_next` as for playlists: this check is performed on files before they are preloaded, and for request.dynamic the user already has full control over the process at this stage.

In other words this feature could be obtained by tweaking the code of `playlist.reloadable` directly in `utils.liq`. I'm not sure I want to do this now. There seems to be a fair amount of redundancy already between `playlist` and `playlist.reloadable` and I don't like adding more. In fact I'd ask instead why keep `playlist.reloadable`? What does it do that you can't do with `playlist`? Shouldn't we consider merging the two sources?

If I were to extend `check_next` and implement it at the level of request resolution, then it'd be more powerful because you could filter requests after that they are preloaded, with all metadata available. It would then also make sense to make it available to all sources that preload requests. It seems to me that this feature may be implement as a specific protocol, but this is a bit complex and I don't think I'll do it for the next release.

**Comment by giflw** [comment] 2015-08-28 15:37
I think I got your point.

For your comment 2 days ago, I think its usefull to add the playlist lenght to request metadata, so one can prevents a playlist of one item stop playing.

For your last comment:

- About playlist.reload, I was thinking about playlist.reloadable and I realized that as one can reload a new URI each time, and the randomization is done just after load list and before playing, as long the playlist has no duplicates, there will be no playback twice in a raw. The problem could be when reloading with random mode, if both playlist have the same file. But, increasing the number of files will decrease significantly the probability of collision.
- About implementing in a request resolution level, seens to be great, but can be delayed for a next release. For now, this implementation for check_next suffices.
- About merging playlist with playlist.reloadable, I think this would be a mistake. For normal playlist, I see no way to change URI, as can be done in playlist.realodable using on_done hook. Besides, playlist.reloadable is a valuable example on how to implement a playlist programatically. Any one could use it, and extends it if necessary. I am a novice on liquidsoap, but as I can see, there is scenarios where playlist.reloadable is more suitable than common playlist, like dynamic URI. I will have to make some more test to see what better satisfied my current needs and what can and cannot be done with each type of source.

**Comment by dbaelde** [comment] 2015-08-28 18:04
Thanks for your comment, @giflw. You might consider yourself a novice but you're using liquidsoap more than I do these days, and you're being really helpful reporting and fixing problems.

I'll add metadata fields to playlist requests, I don't see why it wouldn't work. I propose "playlist_length" and "playlist_position", both containing integers. After this I will consider merging the branch and closing the issue. Did you get a chance to play again with the fixed implementation of check_next?

Regarding other comments:
  * You're right. It is actually possible to change a playlist URI through a server command (and thus from the script) but that may be less easy to use.
  * Ok then.
  * In fact, if a merge had to be done I'd do it the other way around: get rid of `playlist` and script it. This may not be quite possible right now, so let's leave it like that for the moment.

**Comment by dbaelde** [comment] 2015-08-28 18:51
The metadata has been added in the LS-197 branch because this will make merging easier.

**Comment by dbaelde** [comment] 2015-08-28 19:54
I have rebased again on top of the integrated features from #195, and added a test. (For reference LS-197 should now be at 4029d52.) I think check_next is ready for integration into master, but I'll merge only tomorrow: talk now or stay silent forever :)

**Comment by giflw** [comment] 2015-08-28 20:44
Thanks!

I have just teste with your last example. Its seems to be working fine. I'll have some time to test using a more sofisticated check_next like your first example in this weekend. I'll try to test playlist_position and playlist_lenght to.

**Comment by dbaelde** [comment] 2015-08-30 08:10
The check_next feature has been integrated into master, closing the issue now.

**Closed by dbaelde** 2015-08-30 08:10 UTC
Labels: enhancement, RC
