### ISSUE TITLE
Standard library not found

### ISSUE THREAD

**Issue by smimram** [savonet/liquidsoap#2433] opened 2022-06-03 06:58 UTC
Since the switch to `dune`, I get the following with an `opam` install (including with the latest):
```
$ liquidsoap -h playlist
Plugin not found!
```
which seems to indicate that the stadard library is not taken in account.

**Comment by toots** [comment] 2022-06-03 14:02
This is a duplicate of https://github.com/savonet/liquidsoap/issues/2431. I'll close the other one as this one has the more generic cause in its title. Follow-up with `dune` is here: https://github.com/ocaml/dune/issues/5814

**Comment by smimram** [comment] 2022-06-03 14:04
Thanks I had overseen this.

**Closed** 2022-06-03 14:50 UTC
