### ISSUE TITLE
input.ffmpeg with RTMP stream -> FFmpeg.Avutils.Error(Decoder not found)

### ISSUE THREAD

**Issue by gdhgdhgdh** [savonet/liquidsoap#1218] opened 2020-05-26 21:38 UTC
With liq 1.5.0+git@46bca387 (installed via `apt install liquidsoap-master`) on an Ubuntu 20.04 container (hence ffmpeg / libav 4.2.2) I get unpleasant errors as per the title:

```
2020/05/25 21:48:26 [decoder.ffmpeg:4] ffmpeg recognizes "rtmp://het1.de.faraway.dj/live/final" as: audio: {codec: aac, 44100Hz, 2 channel(s)}, video: {codec: h264, 1280x720, yuv420p}.
2020/05/25 21:48:26 [input(dot)ffmpeg:2] Feeding stopped: FFmpeg.Avutils.Error(Decoder not found).
```

The following is enough to reproduce

```
mcvid = input.ffmpeg("rtmp://het1.de.faraway.dj/live/final")
output.file(%ogg(%theora(quality=63),%vorbis), "ffmpeg-test.ogv", mksafe(mcvid))
```

This RTMP stream should be stable enough for testing.

**Comment by toots** [comment] 2020-05-27 03:44
I can decode the stream here:
```
output.file(
  fallible=true,
  %ffmpeg(format="flv",
    %audio(codec="aac"),
    %video(codec="h264_videotoolbox",b="3M")
  ),
  "/tmp/bla.flv",
  input.ffmpeg("rtmp://het1.de.faraway.dj/live/final")
)
```
It keeps disconnecting but I think that this is a different issue. Does the script above work for you?

**Comment by gdhgdhgdh** [comment] 2020-05-27 08:06
hm, I'm not sure what the 'keeps disconnecting' is about - I was able to run the stream in both VLC 3.0.8 and mplayer 1.3.0 (Ubuntu 18.04) for over five minutes without any glitches or disconnects.

That script (modified to use libx264 - I don't have a Mac) still fails as before:

```
root@Ubuntu-1804-bionic-64-minimal ~ # cat /usr/local/share/faraway/ffmpeg.liq 
#!/usr/bin/liquidsoap

set("init.allow_root",true)
output.file(
  fallible=true,
  %ffmpeg(format="flv",
    %audio(codec="aac"),
    %video(codec="libx264",b="3M")
  ),
  "/tmp/bla.flv",
  input.ffmpeg("rtmp://het1.de.faraway.dj/live/final")
)
root@Ubuntu-1804-bionic-64-minimal ~ # docker run --rm -v /usr/local/share/faraway:/host gdhgdh/liquidsoap-full:latest liquidsoap -v --debug /host/ffmpeg.liq
error: XDG_RUNTIME_DIR not set in the environment.
2020/05/27 08:02:22 >>> LOG START
2020/05/27 08:02:21 [main:3] Liquidsoap 1.5.0+git@46bca387
2020/05/27 08:02:21 [main:3] Using: bytes=[distributed with OCaml 4.02 or above] pcre=7.4.3 sedlex=2.1 menhirLib=20200211 dtools=0.4.2 duppy=0.9.0 cry=0.6.5 mm=0.6.0 xmlplaylist=0.1.4 lastfm=0.3.2 ogg=0.6.0 vorbis=0.7.1 opus=0.1.4 speex=0.3.0 mad=0.5.0 flac=0.2.0 flac.ogg=0.2.0 dynlink=[distributed with Ocaml] lame=0.3.4 shine=0.2.1 gstreamer=0.3.0 frei0r=0.1.2 fdkaac=0.3.2 theora=0.3.1 gavl=0.1.6 ffmpeg-avutil=0.5.0 ffmpeg-avcodec=0.5.0 ffmpeg-av=0.5.0 ffmpeg-avfilter=0.5.0 ffmpeg-swresample=0.5.0 ffmpeg-swscale=0.5.0 bjack=0.1.5 alsa=0.3.0 ao=0.2.2 samplerate=0.1.5 taglib=0.3.6 ssl=0.5.9 magic=0.7.3 camomile=1.0.2 inotify=2.3 yojson=1.7.0 faad=0.5.0 soundtouch=0.1.9 portaudio=0.2.1 pulseaudio=0.1.4 ladspa=0.2.0 dssi=0.1.3 tsdl=v0.9.7 tsdl_ttf=0 tsdl_image=0 camlimages=4.2.6 cohttp-lwt-unix=2.5.1 prometheus-app=0.7 srt.types=0.1.1 srt.stubs=0.1.1 srt.stubs=0.1.1 srt=0.1.1 lo=0.1.2 gd=1.0a5
2020/05/27 08:02:21 [main:3] 
2020/05/27 08:02:21 [main:3] DISCLAIMER: This version of Liquidsoap has been
2020/05/27 08:02:21 [main:3] compiled from a snapshot of the development code.
2020/05/27 08:02:21 [main:3] As such, it should not be used in production
2020/05/27 08:02:21 [main:3] unless you know what you are doing!
2020/05/27 08:02:21 [main:3] 
2020/05/27 08:02:21 [main:3] We are, however, very interested in any feedback
2020/05/27 08:02:21 [main:3] about our development code and committed to fix
2020/05/27 08:02:21 [main:3] issues as soon as possible.
2020/05/27 08:02:21 [main:3] 
2020/05/27 08:02:21 [main:3] If you are interested in collaborating to
2020/05/27 08:02:21 [main:3] the development of Liquidsoap, feel free to
2020/05/27 08:02:21 [main:3] drop us a mail at <savonet-devl@lists.sf.net>
2020/05/27 08:02:21 [main:3] or to join the slack chat at <http://slack.liquidsoap.info>.
2020/05/27 08:02:21 [main:3] 
2020/05/27 08:02:21 [main:3] Please send any bug report or feature request
2020/05/27 08:02:21 [main:3] at <https://github.com/savonet/liquidsoap/issues>.
2020/05/27 08:02:21 [main:3] 
2020/05/27 08:02:21 [main:3] We hope you enjoy this snapshot build of Liquidsoap!
2020/05/27 08:02:21 [main:3] 
2020/05/27 08:02:21 [gstreamer.loader:3] Loaded GStreamer 1.16.2 0
2020/05/27 08:02:22 [frame:3] Using 44100Hz audio, 25Hz video, 44100Hz master.
2020/05/27 08:02:22 [frame:3] Frame size must be a multiple of 1764 ticks = 1764 audio samples = 1 video samples.
2020/05/27 08:02:22 [frame:3] Targetting 'frame.duration': 0.04s = 1764 audio samples = 1764 ticks.
2020/05/27 08:02:22 [frame:3] Frames last 0.04s = 1764 audio samples = 1 video samples = 1764 ticks.
2020/05/27 08:02:22 [sandbox:3] Running inside a docker container, disabling sandboxing..
2020/05/27 08:02:22 [audio.converter:3] Using samplerate converter: ffmpeg.
2020/05/27 08:02:22 [video.converter:3] Using preferred video converter: gavl.
2020/05/27 08:02:22 [threads:4] Created thread "gstreamer_main_loop" (1 total).
2020/05/27 08:02:22 [threads:4] Created thread "generic queue #1" (1 total).
2020/05/27 08:02:22 [threads:4] Created thread "generic queue #2" (2 total).
2020/05/27 08:02:22 [threads:4] Created thread "non-blocking queue #1" (3 total).
2020/05/27 08:02:22 [threads:4] Created thread "non-blocking queue #2" (4 total).
2020/05/27 08:02:22 [clock:4] Currently 1 clocks allocated.
2020/05/27 08:02:22 [clock.main:4] Starting 1 sources...
2020/05/27 08:02:22 [source:4] Source output.file_20075 gets up.
2020/05/27 08:02:22 [source:4] Source input.ffmpeg_20074 gets up.
2020/05/27 08:02:22 [threads:4] Created thread "Ffmpeg input" (2 total).
2020/05/27 08:02:22 [threads:4] Created thread "clock_main" (3 total).
2020/05/27 08:02:22 [clock:4] Main phase starts.
2020/05/27 08:02:22 [clock.main:3] Streaming loop starts in auto-sync mode
2020/05/27 08:02:22 [clock.main:3] Delegating synchronisation to CPU clock
2020/05/27 08:02:23 [decoder.ffmpeg:4] ffmpeg recognizes "rtmp://het1.de.faraway.dj/live/final" as: audio: {codec: aac, 44100Hz, 2 channel(s)}, video: {codec: h264, 1280x720, yuv420p}.
2020/05/27 08:02:23 [input(dot)ffmpeg:2] Feeding stopped: FFmpeg.Avutils.Error(Decoder not found).
2020/05/27 08:02:24 [decoder.ffmpeg:4] ffmpeg recognizes "rtmp://het1.de.faraway.dj/live/final" as: audio: {codec: aac, 44100Hz, 2 channel(s)}, video: {codec: h264, 1280x720, yuv420p}.
2020/05/27 08:02:24 [input(dot)ffmpeg:2] Feeding stopped: FFmpeg.Avutils.Error(Decoder not found).
2020/05/27 08:02:26 [decoder.ffmpeg:4] ffmpeg recognizes "rtmp://het1.de.faraway.dj/live/final" as: audio: {codec: aac, 44100Hz, 2 channel(s)}, video: {codec: h264, 1280x720, yuv420p}.
2020/05/27 08:02:26 [input(dot)ffmpeg:2] Feeding stopped: FFmpeg.Avutils.Error(Decoder not found).
[...]
```

**Comment by gdhgdhgdh** [comment] 2020-05-27 08:08
`gdhgdh/liquidsoap-full:latest` is a public Docker image, please try it purely to reproduce the problem.

The Dockerfile is very simple:

```
FROM ubuntu:20.04
ARG LIQVER=master

RUN apt-get update && apt-get install -y ca-certificates gnupg && apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 20D63CCDDD0F62C2 && apt-get clean
RUN echo deb http://deb.liquidsoap.info/ubuntu focal main >> /etc/apt/sources.list.d/liquidsoap.list

RUN apt-get update && apt-get -y install ttf-bitstream-vera liquidsoap-${LIQVER} gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-plugins-good gstr
eamer1.0-tools nano gstreamer1.0-libav netbase gstreamer1.0-vaapi i965-va-driver-shaders && apt-get clean

ENV LIBVA_DRIVER_NAME=i965
```

**Comment by dromer** [comment] 2021-05-16 02:52
> I can decode the stream here:
> 
> ```
> output.file(
>   fallible=true,
>   %ffmpeg(format="flv",
>     %audio(codec="aac"),
>     %video(codec="h264_videotoolbox",b="3M")
>   ),
>   "/tmp/bla.flv",
>   input.ffmpeg("rtmp://het1.de.faraway.dj/live/final")
> )
> ```
> 
> It keeps disconnecting but I think that this is a different issue. Does the script above work for you?

So, I'm running in to this issue, LS responds when I start an rtmp but it just says `FFmpeg.Avutils.Error(Decoder not found)`.
I tried debugging this by trying to record to a file as you are doing here, but again it says `FFmpeg.Avutils.Error(Decoder not found)`

This is on current `main` docker image

**Comment by toots** [comment] 2021-05-16 14:49
It would be nice to be able to find out the format of that stream. I believe that:
```
ffprobe rtmp://het1.de.faraway.dj/live/final
```
Should give you this information. However, I cannot seem to connect to this address at the moment.

**Comment by dromer** [comment] 2021-05-16 16:05
The stream I was trying this with is from OBS:
```
  Metadata:
    Server          : NGINX RTMP (github.com/arut/nginx-rtmp-module)
    displayWidth    : 1920
    displayHeight   : 1080
    fps             : 30
    profile         : 
    level           : 
  Duration: 00:00:00.00, start: 27.287000, bitrate: N/A
    Stream #0:0: Audio: aac (LC), 48000 Hz, stereo, fltp, 196 kb/s
    Stream #0:1: Video: h264 (High), yuv420p(tv, bt709, progressive), 1920x1080 [SAR 1:1 DAR 16:9], 2560 kb/s, 30 fps, 30 tbr, 1k tbn, 60 tbc
```

**Comment by toots** [comment] 2021-05-18 18:13
That should be supported. Only question here, is that an issue with the local ffmpeg build or liquidsoap itself. From our perspective, it seems like to be from the ffmpeg build itself but we should confirm that.

**Comment by dromer** [comment] 2021-05-18 18:45
If I log into the container and manually run `ffmpeg -i rtmp://<ip>/stream/<key> /tmp/out.mp4` it records, so it seems to me that ffmpeg is fine.

**Comment by toots** [comment] 2021-05-23 14:15
I was able to reproduce and fix the error. It was due to the `ffmpeg` binding opening all available streams instead of the streams of concern, leading to this error being raised when some streams did not have a decoder but the streams of interest did. 

This should be fixed with the latest `ocaml-ffmpeg`. Thanks for reporting!

**Closed by toots** 2021-05-23 14:15 UTC
Labels: can't reproduce
