### ISSUE TITLE
Request leaks occuring in version 1.4.0 with playlist.once and playlist.reloadable

### ISSUE THREAD

**Issue by oranjebloom** [savonet/liquidsoap#1082] opened 2020-01-31 09:46 UTC
I'm am running Liquidsoap installed via opam on Debian 9. After upgrading from version 1.3.7 to 1.4.0, Liquidsoap spits out multiple warnings in the log about a possible request leak.

![Screen Shot 2020-01-29 at 8 44 26 pm](https://user-images.githubusercontent.com/46059094/73528888-7396ca80-4461-11ea-92c9-ea1c6078b599.png)

I did some investigation as to why and found the cause to be the playlists that use the playlist.once and playlist.reloadable operators. When all of the track URIs have been played, Liquidsoap doesn’t like it and complains about a possible request leak. The number of request leaks increase from 100 to 200 and upwards infinitely until I reset the playlist, which is not the expect behaviour I want. The relevant parts of my script are pin-pointed in red below.

![Screen Shot 2020-01-31 at 7 42 20 pm](https://user-images.githubusercontent.com/46059094/73529271-2ebf6380-4462-11ea-96b1-34eec51afb5f.png)

```
pl = playlist(mode="randomize", reload_mode = "rounds", reload=1)

osinterludes = pl("/ssr/ssr2/opensource/interludes")
fresh        = pl("/ssr/ssr2/opensource/fresh")
general      = pl("/ssr/ssr2/opensource/general")
archived     = pl("/ssr/ssr2/opensource/archived")
samples      = pl("/ssr/ssr2/opensource/samples")
ostxt        = playlist.once(reload_mode = "watch", "/ssr/ssr2/opensource/os.txt")

#BUILD Open Source#
ostrackloop = rotate([
  fresh,general,general,
  fresh,general,general,
  fresh,general,general,
  fresh,general,samples,archived
])

osinterlude = delay(1200.,osinterludes)
opensource = fallback(track_sensitive = true, [
 osinterlude,ostxt,ostrackloop
])
```

Can these warnings be safely ignored or are they signs of an underlying issue? I don't experience this in version 1.3.7

**Comment by smimram** [comment] 2020-01-31 17:11
I just did some testing and the bug does not seem to be present in the git version (where playlist operators have gone under heavy rewrite, in particular I can think of a change which might explain your problem). I'd advise you to update to this version...

**Comment by oranjebloom** [comment] 2020-02-01 04:41
Thanks for testing.

I’d like to install the dev version via opam.
Could you provide me with the instructions to do this?


Is it …
git clone https://github.com/savonet/liquidsoap.git
cd liquidsoap && git checkout 1.5.0 && opam pin add .


I looked at the change log for version 1.5.0 and I see the following … 

Removed playlist.once, its behavior can be achieved by passing "once" to the reload_mode argument of playlist

Based on the rewrite, I would need to change my script from …

ostxt        = playlist.once(reload_mode = "watch", "/ssr/ssr2/opensource/os.txt”)

to …

ostxt        = playlist(reload_mode = “once", "/ssr/ssr2/opensource/os.txt")

So my question is, how do I now apply ‘watch’ to this? 
Previously, when I make a change to the playlist, it would it reload.
In version 1.5.0, must I now manually reload a playlist that has reload_mode = “once”?

**Comment by oranjebloom** [comment] 2020-02-02 04:44
Thanks for testing.

I’d like to install the dev version via opam.
Could you provide me with the instructions to do this?

Is it …
```
git clone https://github.com/savonet/liquidsoap.git
cd liquidsoap && git checkout 1.5.0 && opam pin add .
```

I looked at the change log for version 1.5.0 and I see the following …

Removed playlist.once, its behavior can be achieved by passing "once" to the reload_mode argument of playlist

Based on the rewrite, I would need to change my script from …
```
ostxt        = playlist.once(reload_mode = "watch", "/ssr/ssr2/opensource/os.txt”)
```
to …
```
ostxt        = playlist(reload_mode = “once", "/ssr/ssr2/opensource/os.txt")
```
So my question is, how do I now apply ‘watch’ to this?
Previously, when I make a change to the playlist, it would it reload.
In version 1.5.0, must I now manually reload a playlist that has `reload_mode = “once”`?

**Comment by oranjebloom** [comment] 2020-02-12 08:55
Sorry to persist with this, but I'm still hoping for some information on this. It seems that playlst.once is deprecated in version 1.5.0 which means substantial changes to my script.

So here are my questions again... I support the idea of deprecating playlist.once and passing ‘once’ to the `reload_mode` in the `playlist` opeator instead... even though it means I will no longer be able to use `reload_mode="watch"` with playlist.once anymore ... this is a required feature in my script. Will there be an alternative way to do this in version 1.5.0? (I refer to the specifics in my previous comment about using "watch").

Also, I’d like to install the dev version via opam for testing ... according to https://www.liquidsoap.info/doc-dev/install.html, installing the dev version via opam is the same as for version 1.4.1 ... which seems incorrect to me.

**Comment by smimram** [comment] 2020-03-02 12:25
I'm sorry I don't really understand what you are trying to achieve with the combination of once and watch can you give me some examples? For instance,
- what happens if the file changes while the playlist is not completely loaded: do we discard songs in the playlist?
- what happens if the playlist has been played and has not changed?

Anyway, `playlist` is now implemented on top of `playlist.reloadable`, see https://github.com/savonet/liquidsoap/blob/master/libs/playlist.liq#L140 and you should be able to modify its definition to achieve whatever behavior you'd like.

**Comment by oranjebloom** [comment] 2020-03-03 11:13
Hi, in the attached screen shot of (the minimal version of) my liq script I use `playlist.once` inside a fallback. That `playlist.once` source is fed by a txt file of URIs (whereas the fallback source is just a `playlist `operator fed by a directory of randomized files). 

![db](https://user-images.githubusercontent.com/46059094/75761918-9cbeb980-5d85-11ea-9083-c4c35d5b40dd.png)

I use playlist.once with `reload_mode = "watch"` in this setup for the following simple reasons:

- Sometimes I want to interact with the stream in a more live sense and program tracks to play more immediately (rather than program them via the scheduler).
- If I leave the txt file empty, the playlist.once source sits dormant, and the fallback source plays randomized tracks instead. There are no issues with this in version 1.3.7 (which I still run for production)
- If I add track URIs to the txt file, then the stream will wait for the currently playing track to finish, and then play tracks in that txt file fed to `playlist.once`. When finished, it will fallback to the default `playlist` source in that fallback.
- The only issue that I have ever experienced with this setup is that, if for some unusual reason, the server goes down or is rebooted, the playlist.once source will reload and play before the fallback.

I'm currently running this setup in version 1.3.7 and am keeping a close eye on the direction of things in version 1.5.0. I think that adding the option to have `reload_mode = "once"` in version 1.5.0 is a great idea. It's just that having the following config in version 1.5.0:

`ostxt = playlist(reload_mode = “once", "/ssr/ssr2/opensource/os.txt")`

... would mean manually reloading it through telnet, instead of the automatic reloads that occur with the old configuration below .... 

`ostxt        = playlist.once(reload_mode = "watch", "/ssr/ssr2/opensource/os.txt”)`

The old method is automated and convenient. The development version is less automated for my needs

**Comment by smimram** [comment] 2020-03-03 11:51
I understand better, I think what you want is precisely
```
ostxt = playlist(reload_mode="watch", loop=false, "/ssr/ssr2/opensource/os.txt")
```
isn't it?

**Comment by oranjebloom** [comment] 2020-03-03 11:54
right! Is this currently an option in version 1.3.7 or 1.4.1

**Comment by smimram** [comment] 2020-03-03 14:26
Nope, this is 1.5.0.

**Comment by oranjebloom** [comment] 2020-03-05 09:37
no problem. I'll test this out on 1.5.0. thanks for making this capability possible. much appreciated

**Comment by smimram** [comment] 2020-03-05 09:52
Keep us posted!

**Comment by oranjebloom** [comment] 2020-04-03 16:53
I've been testing the use of `playlist(reload_mode="watch", loop=false, ...)` in version 1.5.0 with good results. I'm not seeing the request leaks that were occurring in version 1.4.0 and 1.4.1 which was apparent when using `playlist.once(reload_mode = "watch", ...)`. 

Is there any chance that the playlist operator changes can be made part of the upcoming 1.4.2 bug fix release? This issue is preventing me from upgrading from version 1.3.7 otherwise.

**Comment by smimram** [comment] 2020-04-03 16:56
Maybe @toots will think otherwise, but the change is pretty invasive and on an important operator (`playlist`) so I'd rather keep it for a major release...

**Comment by oranjebloom** [comment] 2020-04-03 17:00
I understand... so then is there anything that I can do in the mean time to deal with the request leak issue in version 1.4.0? Should I sit on version 1.3.7 until then?

**Comment by oranjebloom** [comment] 2020-04-03 22:16
... maybe a patch that will allow me to continue to use `playlist.once(reload_mode = "watch", ...)` until the major release happens.

**Comment by toots** [comment] 2020-04-03 23:17
Hi all!

Since the `playlist` operator in `1.5.0` is now fully scripted, it seems to me that a good solution would be to simply import the scripted version in your liquidsoap script and use it...

@smimram, would that work?

**Comment by smimram** [comment] 2020-04-04 09:39
You should try :) In principle it should, but it might be the case that some of the internals of Liquidsoap were modified since then...

**Comment by oranjebloom** [comment] 2020-04-04 10:03
Okay, I'll try it. Can I get your advice on the correct way to import. Is there a specific process to follow?

**Comment by smimram** [comment] 2020-04-04 10:30
You can copy the file https://github.com/savonet/liquidsoap/blob/master/libs/playlist.liq in you current directory and start your script with
```
%include "playlist.liq"
```

**Comment by oranjebloom** [comment] 2020-04-04 11:57
Thanks, I’ll test it out.

**Comment by oranjebloom** [comment] 2020-04-07 11:38
Hi, so I followed the advice above and ran Liquidsoap but got the following error message

```
At /home/amdin/liquidsoap-daemon/script/playlist.liq, line 65, char 138-156:
Error 6: Cannot apply that parameter because the function at /home/amdin/liquidsoap-daemon/script/playlist.liq, line 65, char 11-27 
has no argument labeled "available"!
```

**Comment by smimram** [comment] 2020-04-07 14:49
Yes, this is what I feared. I had to change some internal Liquidsoap functions in order for this to work. Let's wait 1.5.0 then :(

**Comment by oranjebloom** [comment] 2020-04-07 20:01
I understand. I’ll just stick with version 1.3.7 for now and keep testing the GIT version. Thanks anyway

**Comment by MaPePeR** [comment] 2020-04-22 17:44
If i look at the [code correctly](https://github.com/savonet/liquidsoap/releases) the leak warning wasn't present in 1.3.7. So the leaks might be happening in that version as well - without you knowing.

**Comment by oranjebloom** [comment] 2020-04-22 21:59
really? Good find! I did ask if it is safe to run it despite the log warnings. It seems that all we can do is wait until 1.5.0, unless Romain decides to implement a fix before then. But Samuel has indicated that it's quite a pervasive script edit.

**Comment by toots** [comment] 2020-04-23 16:07
Yes, there should be a fix for this in `1.4.2`. I decided to make a breaking change to address the source of all these issues, which is that it is currently not possible to tell` request.dynamic` that you have no more requests for it.

The breaking change is that, starting from `1.4.2`, the return type of a `request.dyamic` will be an array of requests. This allows the user to return no requests using an empty array.

Prior to that, we were returning `request.create("")` which was super hacky and lead to the request leak warnings. We decided that breaking the API on a minor release was worth in order to fix this problem.

Could any of y'all test out `1.4.2` and confirm that it fixes the issue on y'all end?

**Comment by MaPePeR** [comment] 2020-04-23 17:11
I tested it and it doesn't show the request leak warning for me anymore.

I wasn't able to reload a playlist that reached its end, though, but that might just be me, doing it wrong.

**Comment by toots** [comment] 2020-04-24 04:23
Great to hear! My quick testing on `playlist.reloadable` seems to show that the reload function is still working.. My test script:
```
let (reload, pl) = playlist.reloadable("~/documents/playlist")

def on_stop () =
  def f() =
    print("reload!")
    reload ()
    (-1.)
  end
  add_timeout(3., f)
end

output.ao(fallible=true, on_stop=on_stop, pl)
```

**Comment by MaPePeR** [comment] 2020-04-25 18:28
Yea, cannot reproduce it either. It was probably me misunderstanding what `on_track` does. I think i falsely assumed it would trigger at the end of a track, but that is not the case.

**Comment by toots** [comment] 2020-04-25 18:37
Sweet. Let's mark this issue as fixed. It'll go out with `1.4.2` which should happen soon. I've got a recent report on crossfade that I want to investigate but hopefully it'll be done and ready to go this weekend or early next week!

**Closed by toots** 2020-04-25 18:37 UTC
