### ISSUE TITLE
Trying to get harbor username and timestamp for dump filename

### ISSUE THREAD

**Issue by PB-SF** [savonet/liquidsoap#661] opened 2018-11-17 22:07 UTC
I set up a liquidsoap script for our radio station. Most things work really fine.
We use a input.harbor with authentication for our moderators

    #Moderatoren Authentifizierung
    def harbor_auth(port,user,password) = 
      (port == 8080 and user == "user1" and password == "pass1") or
      (port == 8080 and user == "user2" and password == "pass2")
    end
    auth1 = harbor_auth(8080)

    #Live Moderatoren Harbor
    moderator = input.harbor(id="Mod Harbor",port=8080,auth=auth1,icy=true,dumpfile="/path/to/recorded/dumps/$(user)_$(timestamp)-%m-%d-%Y-%H:%M:%S.mp3","modi")
    output.dummy(id="Mod Dummy",fallible=true, moderator)

Each connection of a moderator schould create a dump file for our archive.
Is there a way to get the current username from the authentication in a variable to use it in the dump function of the input.harbor? Also tagged with a timestamp? So that the files are stored according to moderator and time?

My current script write the file in exactly that string i used in code above.
I tryed several ways to get the right syntax, but nothing worked.
For help, I would be grateful :)

Liquidsoap verison 1.3.3 on a ubuntu 14.04 dedicated server.

**Comment by toots** [comment] 2018-11-19 15:38
Hi,

I believe that you should be able to keep a reference to the latest username used at login. Something like this:
```
last_user = ref ""

def harbor_auth(port,user,password) = 
  last_user := user
  (port == 8080 and user == "user1" and password == "pass1") or
  (port == 8080 and user == "user2" and password == "pass2")
end
auth1 = harbor_auth(8080)
```

This way, `last_user` keeps a reference to the latest username that you can use later in your script.

Secondly, you should look at `output.file` instead of the `dumpfile` parameter. `dumpfile` was mostly added for debugging purposes but `output.file` should have all you need.

I believe the simplest way to go would be use the `on_close` callback. Something like this:
```
moderator = input.harbor(id="Mod Harbor",port=8080,auth=auth1,icy=true,"modi")

def on_close(filename) =
  user = !last_user
  # Generate new file name:
  new_filename = "/path/to/recorded/dumps/#{user}_#{basename(filename)}"
  # Move to the new location
  system("mv #{filename} #{new_filename}")
end

output.file(on_close=on_close,%mp3,fallible=true,moderator)
```

The code isn't tested but it should give enough information to reproduce it. I'll close this ticket since I believe there's no new functionalities needed or bug to fix for it. All the best with your liquidsoap project!

**Closed by toots** 2018-11-19 15:38 UTC
