### ISSUE TITLE
How to filter out files without extension

### ISSUE THREAD

**Issue by madprops** [savonet/liquidsoap#904] opened 2019-07-30 23:08 UTC
Hi, sorry if this is a dumb question. When I had mpd to interface with icecast, and I wanted some songs to not be included in the playlist, I would just remove the extension (for instance .mp3) from the files, and they were not included. Is there a way to tell liquidsoap to ignore music files without extensions?

**Comment by smimram** [comment] 2019-08-02 14:26
Yes, but this depends on your actual script. For instance, if you use `playlist` operator, there is a `check_next` arguments which allows for filtering songs (with which you could filter out files with particular filenames, such as those having no extension).

**Comment by madprops** [comment] 2019-08-05 22:06
@smimram Can't seem to find the documentation about check_next. Can you provide an example?

**Comment by smimram** [comment] 2019-08-22 18:35
The documentation is [here](https://www.liquidsoap.info/doc-dev/reference.html#playlist). For instance, the following will only validate filenames containing a dot:
```
def check(r)
  fname = request.filename(r)
  string.match(pattern="^.*\\..*$", fname)
end
s = playlist(check_next=check, "~/Music/misc")
out(s)
```

**Comment by smimram** [comment] 2019-08-26 11:48
Closing this since a solution was provided. Feel free to reopen if needed.

**Closed by smimram** 2019-08-26 11:48 UTC
Labels: usage

**Comment by rrolla** [comment] 2020-05-05 14:56
@smimram I have question how can I ignore .gitkeep file for playlist, I tried: 
```
def check(r)
  fname = request.filename(r)
  fname != ".gitkeep"
end

songs = audio_to_stereo(playlist(check_next=check, mode="randomize", reload=1, reload_mode="rounds", "~/content/music"))
```

But anyway in logs full of:
```
rolla-liquidsoap | 2020/05/05 14:54:42 [music:3] Playlist is a directory.
rolla-liquidsoap | 2020/05/05 14:54:42 [decoder.wav/aiff:4] Invalid file extension for "/home/liquidsoap/content/music/.gitkeep"!
rolla-liquidsoap | 2020/05/05 14:54:42 [decoder:4] Trying method "AIFF" for "/home/liquidsoap/content/music/.gitkeep"...
rolla-liquidsoap | 2020/05/05 14:54:42 [decoder.wav/aiff:4] Invalid file extension for "/home/liquidsoap/content/music/.gitkeep"!
rolla-liquidsoap | 2020/05/05 14:54:42 [decoder:4] Trying method "MIDI" for "/home/liquidsoap/content/music/.gitkeep"...
rolla-liquidsoap | 2020/05/05 14:54:42 [decoder:4] Trying method "IMAGE" for "/home/liquidsoap/content/music/.gitkeep"...
rolla-liquidsoap | 2020/05/05 14:54:42 [decoder:4] Trying method "FLAC" for "/home/liquidsoap/content/music/.gitkeep"...
rolla-liquidsoap | 2020/05/05 14:54:42 [decoder.flac:4] Invalid file extension for "/home/liquidsoap/content/music/.gitkeep"!
rolla-liquidsoap | 2020/05/05 14:54:42 [decoder:4] Trying method "AAC" for "/home/liquidsoap/content/music/.gitkeep"...
rolla-liquidsoap | 2020/05/05 14:54:42 [decoder:4] Decoder "AAC" failed on "/home/liquidsoap/content/music/.gitkeep": Faad.Failed!
rolla-liquidsoap | 2020/05/05 14:54:42 [decoder:4] Trying method "MP4" for "/home/liquidsoap/content/music/.gitkeep"...
rolla-liquidsoap | 2020/05/05 14:54:42 [decoder:4] Decoder "MP4" failed on "/home/liquidsoap/content/music/.gitkeep": Faad.Failed!
rolla-liquidsoap | 2020/05/05 14:54:42 [decoder:4] Trying method "OGG" for "/home/liquidsoap/content/music/.gitkeep"...
rolla-liquidsoap | 2020/05/05 14:54:42 [decoder.ogg:4] Invalid file extension for "/home/liquidsoap/content/music/.gitkeep"!
rolla-liquidsoap | 2020/05/05 14:54:42 [decoder:4] Trying method "MAD" for "/home/liquidsoap/content/music/.gitkeep"...
rolla-liquidsoap | 2020/05/05 14:54:42 [decoder.mad:4] Invalid file extension for "/home/liquidsoap/content/music/.gitkeep"!
rolla-liquidsoap | 2020/05/05 14:54:42 [decoder:4] Trying method "GSTREAMER" for "/home/liquidsoap/content/music/.gitkeep"...
rolla-liquidsoap | 2020/05/05 14:54:42 [decoder.gstreamer:4] Invalid file extension for "/home/liquidsoap/content/music/.gitkeep"!
rolla-liquidsoap | 2020/05/05 14:54:42 [decoder:3] Unable to decode "/home/liquidsoap/content/music/.gitkeep" as {audio=1+;video=0;midi=0}!
rolla-liquidsoap | 2020/05/05 14:54:42 [music:3] Successfully loaded a playlist of 1 tracks.
rolla-liquidsoap | 2020/05/05 14:54:42 [decoder:4] Trying method "META" for "/home/liquidsoap/content/music/.gitkeep"...
rolla-liquidsoap | 2020/05/05 14:54:42 [decoder:4] Trying method "WAV" for "/home/liquidsoap/content/music/.gitkeep"...
rolla-liquidsoap | 2020/05/05 14:54:42 [music:3] Loading playlist...
rolla-liquidsoap | 2020/05/05 14:54:42 [decoder.wav/aiff:4] Invalid file extension for "/home/liquidsoap/content/music/.gitkeep"!
rolla-liquidsoap | 2020/05/05 14:54:42 [decoder:4] Trying method "AIFF" for "/home/liquidsoap/content/music/.gitkeep"...
rolla-liquidsoap | 2020/05/05 14:54:42 [music:3] Playlist is a directory.
rolla-liquidsoap | 2020/05/05 14:54:42 [decoder.wav/aiff:4] Invalid file extension for "/home/liquidsoap/content/music/.gitkeep"!
rolla-liquidsoap | 2020/05/05 14:54:42 [decoder:4] Trying method "MIDI" for "/home/liquidsoap/content/music/.gitkeep"...
rolla-liquidsoap | 2020/05/05 14:54:42 [decoder:4] Trying method "IMAGE" for "/home/liquidsoap/content/music/.gitkeep"...
rolla-liquidsoap | 2020/05/05 14:54:42 [decoder:4] Trying method "FLAC" for "/home/liquidsoap/content/music/.gitkeep"...
rolla-liquidsoap | 2020/05/05 14:54:42 [decoder.flac:4] Invalid file extension for "/home/liquidsoap/content/music/.gitkeep"!
rolla-liquidsoap | 2020/05/05 14:54:42 [decoder:4] Trying method "AAC" for "/home/liquidsoap/content/music/.gitkeep"...
rolla-liquidsoap | 2020/05/05 14:54:42 [decoder:4] Decoder "AAC" failed on "/home/liquidsoap/content/music/.gitkeep": Faad.Failed!
rolla-liquidsoap | 2020/05/05 14:54:42 [decoder:4] Trying method "MP4" for "/home/liquidsoap/content/music/.gitkeep"...

```

**Comment by smimram** [comment] 2020-05-06 07:00
The problem is that `request.filename` gives the full path including the directory: something like `/the/path/.gitkeep`. You should use the function `path.basename` to extract the filename only before comparing.

**Comment by rrolla** [comment] 2020-05-06 18:37
> The problem is that `request.filename` gives the full path including the directory: something like `/the/path/.gitkeep`. You should use the function `path.basename` to extract the filename only before comparing.

Thanks this works:
```
def check(r)
  fname = path.basename(request.filename(r))
  fname != ".gitkeep"
end

songs = audio_to_stereo(playlist(check_next=check, mode="randomize", reload=1, reload_mode="watch", "~/content/music"))
```
