### ISSUE TITLE
Registered command should default to the root namespace

### ISSUE THREAD

**Issue by codeofdusk** [savonet/liquidsoap#4222] opened 2024-11-24 07:08 UTC
### Description

When I call `server.register` to register custom commands for the telnet server, these command should default to the root command namespace (like in Liquidsoap 2.2.x).

### Steps to reproduce

1. Include this in a script with the telnet server enabled:
```
radio = playlist("/path/to/some/dir")
server.register(
usage="skip",
description="Skip the current song.",
"skip",
fun(_) -> begin radio.skip() "Done!" end
)
```
2. Start liquidsoap.
3. Connect to the telnet server, and enter `skip` at the prompt.

### Expected behavior

The skip command is called. On 2.3, I get

```
ERROR: unknown command, type "help" to get a list of commands.
```

To run the command, I must enter `.skip`.

### Liquidsoap version

```text
Commit b18d14a52a518f4b2ddf4a44c69a30698703b082
```

### Liquidsoap build config

```text
* Liquidsoap version  : rolling-release-v2.3.x-137-gb18d14a+dev

 * Compilation options
   - Release build       : false
   - Git SHA             : (none)
   - OCaml version       : 4.14.1
   - OS type             : Unix
   - Libs versions       : alsa=0.3.0 angstrom=0.16.1 asetmap=0.8.1 asn1-combinators=0.3.2 astring=0.8.5 base=v0.16.3 base.base_internalhash_types=v0.16.3 base.caml=v0.16.3 base.shadow_stdlib=v0.16.3 base64=3.5.1 bigarray=[distributed with Ocaml] bigarray-compat=1.1.0 bigstringaf=0.10.0 bos=0.2.1 bytes=[distributed with OCaml 4.02 or above] ca-certs=v1.0.0 camlp-streams camomile.lib=2.0 cohttp=5.3.1 cohttp-lwt=5.3.0 cohttp-lwt-unix=5.3.0 conduit=7.1.0 conduit-lwt=7.1.0 conduit-lwt-unix=7.1.0 cry=1.0.3 cstruct=6.2.0 ctypes=0.23.0 ctypes-foreign=0.23.0 curl=0.9.2 digestif.c=1.2.0 domain-name=0.4.0 domain_shims dtools=0.4.5 dune-build-info=3.16.1 dune-private-libs.dune-section=3.16.1 dune-site=3.16.1 dune-site.private=3.16.1 duppy=0.9.4 eqaf=0.10 ffmpeg-av=f978192 ffmpeg-avcodec=f978192 ffmpeg-avdevice=f978192 ffmpeg-avfilter=f978192 ffmpeg-avutil=f978192 ffmpeg-swresample=f978192 ffmpeg-swscale=f978192 fileutils=0.6.4 flac=107871f flac.decoder=107871f flac.ogg=107871f fmt=0.9.0 fpath=0.7.3 gen=1.1 gmap=0.3.0 integers ipaddr=5.6.0 ipaddr-sexp=5.6.0 ipaddr.unix=5.6.0 jemalloc kdf.hkdf=1.0.0 kdf.pbkdf=1.0.0 lame=0.3.7 liquidsoap-lang=rolling-release-v2.3.x-137-gb18d14a liquidsoap-lang.console=rolling-release-v2.3.x-137-gb18d14a liquidsoap_alsa=rolling-release-v2.3.x-137-gb18d14a-dirty liquidsoap_builtins=rolling-release-v2.3.x-137-gb18d14a-dirty liquidsoap_core=rolling-release-v2.3.x-137-gb18d14a-dirty liquidsoap_ffmpeg=rolling-release-v2.3.x-137-gb18d14a-dirty liquidsoap_flac=rolling-release-v2.3.x-137-gb18d14a-dirty liquidsoap_jemalloc=rolling-release-v2.3.x-137-gb18d14a-dirty liquidsoap_lame=rolling-release-v2.3.x-137-gb18d14a-dirty liquidsoap_mad=rolling-release-v2.3.x-137-gb18d14a-dirty liquidsoap_ndi=rolling-release-v2.3.x-137-gb18d14a-dirty liquidsoap_ogg=rolling-release-v2.3.x-137-gb18d14a-dirty liquidsoap_ogg_flac=rolling-release-v2.3.x-137-gb18d14a-dirty liquidsoap_optionals=rolling-release-v2.3.x-137-gb18d14a-dirty liquidsoap_opus=rolling-release-v2.3.x-137-gb18d14a-dirty liquidsoap_oss=rolling-release-v2.3.x-137-gb18d14a-dirty liquidsoap_prometheus=rolling-release-v2.3.x-137-gb18d14a-dirty liquidsoap_runtime=rolling-release-v2.3.x-137-gb18d14a-dirty liquidsoap_samplerate=rolling-release-v2.3.x-137-gb18d14a-dirty liquidsoap_sdl=rolling-release-v2.3.x-137-gb18d14a-dirty liquidsoap_sdl_log_level=rolling-release-v2.3.x-137-gb18d14a-dirty liquidsoap_ssl=rolling-release-v2.3.x-137-gb18d14a-dirty liquidsoap_stereotool=rolling-release-v2.3.x-137-gb18d14a-dirty liquidsoap_tls=rolling-release-v2.3.x-137-gb18d14a-dirty liquidsoap_vorbis=rolling-release-v2.3.x-137-gb18d14a-dirty logs=0.7.0 logs.fmt=0.7.0 logs.lwt=0.7.0 lwt lwt.unix macaddr=5.6.0 mad=0.5.3 magic-mime=1.3.1 mem_usage=0.1.1 menhirLib=20240715 metadata=0.3.0 mirage-crypto=1.1.0 mirage-crypto-ec=1.1.0 mirage-crypto-pk=1.1.0 mirage-crypto-rng=1.1.0 mirage-crypto-rng.unix=1.1.0 mm=0.8.6 mm.audio=0.8.6 mm.base=0.8.6 mm.image=0.8.6 mm.midi=0.8.6 mm.video=0.8.6 ndi=rolling-release-v2.3.x-137-gb18d14a-dirty ocplib-endian ocplib-endian.bigstring ogg=0.7.4 ogg.decoder=0.7.4 ohex opus=0.2.2 opus.decoder=0.2.2 ppx_compare.runtime-lib=v0.16.0 ppx_hash.runtime-lib=v0.16.0 ppx_sexp_conv.runtime-lib=v0.16.0 prometheus=1.2 prometheus-app=1.2 ptime=1.2.0 ptime.clock=1.2.0 ptime.clock.os=1.2.0 re=1.12.0 rresult=0.7.0 samplerate=0.1.6 saturn_lockfree=0.4.1 sedlex=3.3 seq=[distributed with OCaml 4.07 or above] sexplib0=v0.16.0 ssl=0.7.0 stdlib-shims=0.3.0 stereotool=rolling-release-v2.3.x-137-gb18d14a-dirty str=[distributed with Ocaml] stringext=1.6.0 threads=[distributed with Ocaml] threads.posix=[internal] tls=1.0.4 tsdl=v1.1.0 tsdl-image=0.5 tsdl-ttf=0.6 unix=[distributed with Ocaml] uri=4.4.0 uri-sexp=4.4.0 uri.services=4.4.0 vorbis=0.8.0 vorbis.decoder=0.8.0 x509=1.0.5 zarith=1.14
   - architecture        : amd64
   - host                : x86_64-pc-linux-gnu
   - target              : x86_64-pc-linux-gnu
   - system              : linux
   - ocamlopt_cflags     : -O2 -fno-strict-aliasing -fwrapv -pthread -fPIC
   - native_c_compiler   : gcc -O2 -fno-strict-aliasing -fwrapv -pthread -fPIC -D_FILE_OFFSET_BITS=64
   - native_c_libraries  : -lm

 * Configured paths
   - mode              : default
   - standard library  : (set by dune-site)
   - scripted binaries : (set by dune-site)
   - rundir            : (set by dune-site)
   - logdir            : (set by dune-site)
   - user cache        : $HOME/.cache/liquidsoap (override with $LIQ_CACHE_USER_DIR)
   - system cache      : (set by dune-site) (override with $LIQ_CACHE_SYSTEM_DIR)
   - camomile files    : (set by dune-site)

 * Supported input formats
   - MP3               : yes
   - AAC               : no (requires faad)
   - Ffmpeg            : yes
   - Flac (native)     : yes
   - Flac (ogg)        : yes
   - Opus              : yes
   - Speex             : no (requires speex)
   - Theora            : no (requires theora)
   - Vorbis            : yes
   - WAV/AIFF          : yes (native)

 * Supported output formats
   - FDK-AAC           : no (requires fdkaac)
   - FFmpeg            : yes
   - MP3               : yes
   - MP3 (fixed-point) : no (requires shine)
   - Flac (native)     : yes
   - Flac (ogg)        : yes
   - Opus              : yes
   - Speex             : no (requires speex)
   - Theora            : no (requires theora)
   - Vorbis            : yes
   - WAV/AIFF          : yes (native)

 * Tags
   - AAC               : no (requires faad)
   - FFmpeg            : yes
   - FLAC (native)     : yes
   - Flac (ogg)        : yes
   - Native decoder    : yes
   - Vorbis            : yes

 * Input / output
   - ALSA              : yes
   - AO                : no (requires ao)
   - FFmpeg            : yes
   - JACK              : no (requires bjack)
   - NDI               : yes
   - OSS               : yes
   - Portaudio         : no (requires portaudio)
   - Pulseaudio        : no (requires pulseaudio)
   - SRT               : no (requires srt)

 * Audio manipulation
   - FFmpeg            : yes
   - LADSPA            : no (requires ladspa)
   - Lilv              : no (requires lilv)
   - Samplerate        : yes
   - SoundTouch        : no (requires soundtouch)
   - StereoTool        : yes

 * Video manipulation
   - camlimages        : no (requires camlimages)
   - FFmpeg            : yes
   - frei0r            : no (requires frei0r)
   - ImageLib          : no (requires imagelib)
   - SDL               : yes

 * MIDI manipulation
   - DSSI              : no (requires dssi)

 * Visualization
   - GD                : no (requires gd)
   - Graphics          : no (requires graphics)
   - SDL               : yes

 * Additional libraries
   - FFmpeg filters    : yes
   - FFmpeg devices    : yes
   - inotify           : no (requires inotify)
   - irc               : no (requires irc-client-unix)
   - jemalloc          : yes
   - lastfm            : no (requires lastfm)
   - lo                : no (requires lo)
   - memtrace          : no (requires memtrace)
   - osc               : no (requires osc-unix)
   - ssl               : yes
   - sqlite3           : no (requires sqlite3)
   - tls               : yes
   - posix-time2       : no (requires posix)
   - windows service   : no (requires winsvc)
   - YAML support      : no (requires yaml)
   - XML playlists     : no (requires xmlplaylist)

 * Monitoring
   - Prometheus        : yes
```

### Additional Info

Built with Opam by pinning a source checkout on Debian testing/unstable.

**Comment by codeofdusk** [comment] 2024-11-24 07:10
CC @toots.

**Comment by toots** [comment] 2024-11-24 16:09
Have you looked at the list of commands via `help`?

**Comment by vitoyucepi** [comment] 2024-11-24 18:20
Hi,
I can't confirm this issue on my side. Here's my config
1. `compose.yaml`

**Comment by gAlleb** [comment] 2024-11-24 19:07
```
 * Liquidsoap version  : rolling-release-v2.3.x-1-gfaffb13+dev

 * Compilation options
   - Release build       : false
   - Git SHA             : (none)
   - OCaml version       : 4.14.2
   - OS type             : Unix
```

OPAM. Tried on what is installed at the moment. I `can` confirm the issue with Vito's script.

**Comment by gAlleb** [comment] 2024-11-24 19:20
Updated to

```
 * Liquidsoap version  : rolling-release-v2.3.x-2-gb18d14a+dev

 * Compilation options
   - Release build       : false
   - Git SHA             : (none)
   - OCaml version       : 4.14.2
   - OS type             : Unix
```
Issue persists

```
Available commands:
| .skip
| ao.metadata
| ao.remaining
| ao.skip
| exit
| help [<command>]
| music.next
| music.reload
| music.skip
| music.uri [<uri>]
| quit
| request.all
| request.metadata <rid>
| request.resolving
| request.trace <rid>
| runtime.gc.compact
| runtime.gc.full_major
| runtime.memory
| uptime
| var.get
| var.list
| var.set <name> = <value>
| version

```

**Comment by toots** [comment] 2024-11-24 19:38
I cannot reproduce with `main` here at the latest commit (b18d14a)

**Comment by gAlleb** [comment] 2024-11-24 19:47
Just insalled main - `Liquidsoap version  : rolling-release-v2.3.x-2-gb18d14a+dev 

Issue persists

```
liquidsoap % liquidsoap --build-config

 * Liquidsoap version  : rolling-release-v2.3.x-2-gb18d14a+dev

 * Compilation options
   - Release build       : false
   - Git SHA             : (none)
   - OCaml version       : 4.14.2
   - OS type             : Unix
   - Libs versions       : angstrom=0.16.1 ao=0.2.4 base=v0.16.3 base.base_internalhash_types=v0.16.3 base.caml=v0.16.3 base.shadow_stdlib=v0.16.3 bigarray=[distributed with Ocaml] bigstringaf=0.10.0 bytes=[distributed with OCaml 4.02 or above] camlp-streams camomile.lib=2.0 cry=1.0.3 curl=0.9.2 domain_shims dtools=0.4.5 dune-build-info=3.16.1 dune-private-libs.dune-section=3.16.1 dune-site=3.16.1 dune-site.private=3.16.1 duppy=0.9.4 ffmpeg-av=1.2.1 ffmpeg-avcodec=1.2.1 ffmpeg-avdevice=1.2.1 ffmpeg-avfilter=1.2.1 ffmpeg-avutil=1.2.1 ffmpeg-swresample=1.2.1 ffmpeg-swscale=1.2.1 fileutils=0.6.4 gen=1.1 lame=0.3.7 lastfm=0.3.4 liquidsoap-lang=rolling-release-v2.3.x-2-gb18d14a liquidsoap-lang.console=rolling-release-v2.3.x-2-gb18d14a liquidsoap_ao=rolling-release-v2.3.x-2-gb18d14a-dirty liquidsoap_builtins=rolling-release-v2.3.x-2-gb18d14a-dirty liquidsoap_core=rolling-release-v2.3.x-2-gb18d14a-dirty liquidsoap_ffmpeg=rolling-release-v2.3.x-2-gb18d14a-dirty liquidsoap_lame=rolling-release-v2.3.x-2-gb18d14a-dirty liquidsoap_lastfm=rolling-release-v2.3.x-2-gb18d14a-dirty liquidsoap_optionals=rolling-release-v2.3.x-2-gb18d14a-dirty liquidsoap_runtime=rolling-release-v2.3.x-2-gb18d14a-dirty liquidsoap_xmlplaylist=rolling-release-v2.3.x-2-gb18d14a-dirty magic-mime=1.3.1 mem_usage=0.1.1 menhirLib=20240715 metadata=0.3.0 mm=0.8.6 mm.audio=0.8.6 mm.base=0.8.6 mm.image=0.8.6 mm.midi=0.8.6 mm.video=0.8.6 ppx_compare.runtime-lib=v0.16.0 ppx_hash.runtime-lib=v0.16.0 ppx_sexp_conv.runtime-lib=v0.16.0 re=1.12.0 saturn_lockfree=0.4.1 sedlex=3.3 seq=[distributed with OCaml 4.07 or above] sexplib0=v0.16.0 stdlib-shims=0.3.0 str=[distributed with Ocaml] stringext=1.6.0 threads=[distributed with Ocaml] threads.posix=[internal] unix=[distributed with Ocaml] uri=4.4.0 xmlm=1.4.0 xmlplaylist=0.1.5
   - architecture        : amd64
   - host                : x86_64-apple-darwin22.6.0
   - target              : x86_64-apple-darwin22.6.0
   - system              : macosx
   - ocamlopt_cflags     : -O2 -fno-strict-aliasing -fwrapv -pthread
   - native_c_compiler   : cc -O2 -fno-strict-aliasing -fwrapv -pthread -D_FILE_OFFSET_BITS=64
   - native_c_libraries  : -lm

 * Configured paths
   - mode              : default
   - standard library  : (set by dune-site)
   - scripted binaries : (set by dune-site)
   - rundir            : (set by dune-site)
   - logdir            : (set by dune-site)
   - user cache        : $HOME/.cache/liquidsoap (override with $LIQ_CACHE_USER_DIR)
   - system cache      : (set by dune-site) (override with $LIQ_CACHE_SYSTEM_DIR)
   - camomile files    : (set by dune-site)

 * Supported input formats
   - MP3               : no (requires mad)
   - AAC               : no (requires faad)
   - Ffmpeg            : yes
   - Flac (native)     : no (requires flac)
   - Flac (ogg)        : no (requires ogg)
   - Opus              : no (requires opus)
   - Speex             : no (requires speex)
   - Theora            : no (requires theora)
   - Vorbis            : no (requires vorbis)
   - WAV/AIFF          : yes (native)

 * Supported output formats
   - FDK-AAC           : no (requires fdkaac)
   - FFmpeg            : yes
   - MP3               : yes
   - MP3 (fixed-point) : no (requires shine)
   - Flac (native)     : no (requires flac)
   - Flac (ogg)        : no (requires ogg)
   - Opus              : no (requires opus)
   - Speex             : no (requires speex)
   - Theora            : no (requires theora)
   - Vorbis            : no (requires vorbis)
   - WAV/AIFF          : yes (native)

 * Tags
   - AAC               : no (requires faad)
   - FFmpeg            : yes
   - FLAC (native)     : no (requires flac)
   - Flac (ogg)        : no (requires ogg)
   - Native decoder    : yes
   - Vorbis            : no (requires vorbis)

 * Input / output
   - ALSA              : no (requires alsa)
   - AO                : yes
   - FFmpeg            : yes
   - JACK              : no (requires bjack)
   - NDI               : no (requires ctypes-foreign)
   - OSS               : no (requires oss)
   - Portaudio         : no (requires portaudio)
   - Pulseaudio        : no (requires pulseaudio)
   - SRT               : no (requires srt)

 * Audio manipulation
   - FFmpeg            : yes
   - LADSPA            : no (requires ladspa)
   - Lilv              : no (requires lilv)
   - Samplerate        : no (requires samplerate)
   - SoundTouch        : no (requires soundtouch)
   - StereoTool        : no (requires ctypes-foreign)

 * Video manipulation
   - camlimages        : no (requires camlimages)
   - FFmpeg            : yes
   - frei0r            : no (requires frei0r)
   - ImageLib          : no (requires imagelib)
   - SDL               : no (requires tsdl-image & tsdl-ttf)

 * MIDI manipulation
   - DSSI              : no (requires dssi)

 * Visualization
   - GD                : no (requires gd)
   - Graphics          : no (requires graphics)
   - SDL               : no (requires tsdl-image & tsdl-ttf)

 * Additional libraries
   - FFmpeg filters    : yes
   - FFmpeg devices    : yes
   - inotify           : no (requires inotify)
   - irc               : no (requires irc-client-unix)
   - jemalloc          : no (requires jemalloc)
   - lastfm            : yes
   - lo                : no (requires lo)
   - memtrace          : no (requires memtrace)
   - osc               : no (requires osc-unix)
   - ssl               : no (requires ssl)
   - sqlite3           : no (requires sqlite3)
   - tls               : no (requires tls-liquidsoap)
   - posix-time2       : no (requires posix)
   - windows service   : no (requires winsvc)
   - YAML support      : no (requires yaml)
   - XML playlists     : yes

 * Monitoring
   - Prometheus        : no (requires prometheus)
```

**Comment by toots** [comment] 2024-11-24 23:14
I was able to reproduce!

**Comment by toots** [comment] 2024-11-24 23:16
I think 60a2ee1b9 should have fixed it. I'm suspecting some difference in the new regular expression module that we use now.

**Comment by vitoyucepi** [comment] 2024-11-24 23:40
I've tracked the commit using bisect. 4cfb499a

**Comment by toots** [comment] 2024-11-25 00:00
Yep, thanks. Confirmed fixed in 1e3d1e6b8

**Comment by toots** [comment] 2024-11-25 00:00
I also added an entry about regexp behavior changes in the migration doc: https://github.com/savonet/liquidsoap/commit/bee3179f35157131d4b3ef9152633b7803dea181

**Closed by toots** 2024-11-25 00:00 UTC
Labels: bug

**Comment by codeofdusk** [comment] 2024-11-25 01:34
All working now, thanks!
