### ISSUE TITLE
rolling-release-2.2.x parse error with empty comment before block of code

### ISSUE THREAD

**Issue by brenc** [savonet/liquidsoap#3093] opened 2023-05-19 19:20 UTC
Working on upgraded to the 2.2.x rolling release and hit what looks to be a parser bug or something.

This causes a parse error:
```
# 
# TEST
#
thread.run(every=1.0, {
  ngr.util.set_if_live(set_is_live, [ngr.inputs.harbor, ngr.inputs.harbor_ssl])
}) <-- line 73
```

```
INFO: Loading Sdl_image, Target = linux
INFO: Loading Sdl_ttf, Target = linux
At /app/main.liq, line 73, char 0:
})
Error 2: Parse error
```

But this parses OK:
```
# 
# TEST
thread.run(every=1.0, {
  ngr.util.set_if_live(set_is_live, [ngr.inputs.harbor, ngr.inputs.harbor_ssl])
})
```

- OS: Docker
- Version: savonet/liquidsoap:rolling-release-v2.2.x

**Comment by vitoyucepi** [comment] 2023-05-19 19:46
Hi @brenc,

It seems the only difference is here
```diff
 # 
 # TEST
-#
 thread.run(every=1.0, {
   ngr.util.set_if_live(set_is_live, [ngr.inputs.harbor, ngr.inputs.harbor_ssl])
 })
```

What's the version you are running? `liquidsoap --version`

**Comment by brenc** [comment] 2023-05-19 20:11
```
INFO: Loading Sdl_image, Target = linux
INFO: Loading Sdl_ttf, Target = linux
Liquidsoap 2.2.0+git@3e11a18cc
Copyright (c) 2003-2023 Savonet team
Liquidsoap is open-source software, released under GNU General Public License.
See <http://liquidsoap.info> for more information.
```

Already running latest rolling release.

This error does not exist in 2.1.4. That's the version we're running now. This is one of the issues with the config that I had to fix with 2.2.x.

**Comment by vitoyucepi** [comment] 2023-05-19 20:27
Could you check if the same problem exists in 
- `savonet/liquidsoap:842c6b4`
- `savonet/liquidsoap:471bd7c`

**Comment by vitoyucepi** [comment] 2023-05-19 20:52
The problem caused by #2792.

1. ```ruby
   #
   thread.run({
   })
   ```
   becomes
   ```ruby
   #thread.run({
   })
   ```
1. ```ruby
   #
   a = {
   }
   ```
   becomes
   ```ruby
   #a = {
   }
   ```
1. ```ruby
   #
   print(1)
   print(2)
   ```
   becomes
   ```ruby
   #print(1)
   print(2)
   ```

**Comment by gabsoftware** [comment] 2023-05-19 23:36
I noticed this too but forgot to report.

**Comment by toots** [comment] 2023-05-19 23:59
Thanks y'all. It pretty very interesting to learn that unicode standard includes line breaks in their white space characters, which was not our assumption. This is fixed in https://github.com/savonet/liquidsoap/pull/3094

**Closed** 2023-05-20 15:34 UTC
