### ISSUE TITLE
Firefox fails to connect to secured harbor's websocket

### ISSUE THREAD

**Issue by NTShop** [savonet/liquidsoap#402] opened 2017-02-17 15:30 UTC
Hi, I got liquidsoap installed via the opam way, nice !   It's version 1.2.1 however it doesn't appear to have the new **input.harbor.ssl** support referenced in issue #376  where it shows that the mod was merged into the master branch. When I try to use input.harbor.ssl I get an error: 

`the variable input.harbor.ssl used here has not been previously defined`

Do I need to install something extra via opam for this to work, or is it that the opam packages aren't in sync with the master branch?  Or?

**Comment by NTShop** [comment] 2017-02-17 15:39
I installed the ssl package via opam

`opam install ssl`

That was installed fine: 

`The following actions will be performed:
  ∗  install   conf-openssl 1                 [required by ssl]
  ∗  install   conf-which   1                 [required by ssl]
  ∗  install   ssl          0.5.3
  ↻  recompile cry          0.4.1             [uses ssl]
  ↻  recompile liquidsoap   1.2.1             [uses ssl]
===== ∗  3   ↻  2 =====
Do you want to continue ? [Y/n] y

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[cry] Archive in cache
[liquidsoap] Archive in cache
[default] https://opam.ocaml.org/archives/ssl.0.5.3+opam.tar.gz downloaded

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
⊘  removed   liquidsoap.1.2.1
∗  installed conf-openssl.1
∗  installed conf-which.1
⊘  removed   cry.0.4.1
∗  installed ssl.0.5.3
∗  installed cry.0.4.1
∗  installed liquidsoap.1.2.1
Done.`

But still trying to use input.harbor.ssl throws the same error: 

`the variable input.harbor.ssl used here has not been previously defined`

**Comment by hairmare** [comment] 2017-02-17 15:42
`opam install` [installs the latest released version](https://opam.ocaml.org/doc/Usage.html).

https://github.com/savonet/liquidsoap/commit/2ae98c2b4bc832bb63b87d8200609426fba998af is not in a tagged release yet, you can see this next to the fork symbol below the commit message where it will reference any tags the commit made it into and the original pr.

opam can probably also install master, maybe someone who is better versed in opam can explain how?

**Comment by toots** [comment] 2017-03-18 17:32
You can pin a recent `liquidsoap` repository:
```
git clone https://github.com/savonet/liquidsoap.git
cd liquidsoap
opam pin add liquidsoap.
```

That should do it!

**Comment by hairmare** [comment] 2017-03-18 18:17
Thanks!

**Comment by NTShop** [comment] 2017-03-20 23:24
I tried the above instructions for pinning today and got it compiled. But, it won't run with SSL (I created a self-signed cert for testing). Here's my start.liq file and below that is the error output from liquidsoap. I don't know what it means, @toots can you please explain what I'm doing wrong? 

=== CREATE CERT ===
openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -days 365

=== START.LIQ FILE ===

set( "log.file.path", "/tmp/liquidsoap")
set( 'log.level', 5 )
set( 'harbor.verbose', true )
set( "harbor.bind_addr", "0.0.0.0" )
set( "harbor_ssl_certificate", '/etc/ssl/cert.pem' );
set( "harbor.ssl.private_key", '/etc/ssl/key.pem' );
set( "harbor.ssl.password", 'test' );
live = input.harbor.ssl( 'live', port=9000, user="source", password="hackme")
radio = fallback( track_sensitive=false, [live] )
out = output.icecast( %mp3(bitrate=64, samplerate=48000, id3v2=true), fallible=true, host="localhost", port=8000, user="source", password="hackme", mount="listen.mp3", radio )

==== ERROR OUTPUT =====

Line 18, char 1: Unknown error!
Fatal error: exception Ssl.Certificate_error
Raised by primitive operation at file "harbor/harbor_ssl.ml", line 72, characters 10-133
Called from file "tools/tutils.ml", line 80, characters 16-19
Re-raised at file "tools/tutils.ml", line 82, characters 33-40
Called from file "harbor/harbor_ssl.ml" (inlined), line 64, characters 2-496
Called from file "sources/harbor_input_ssl.ml", line 27, characters 22-44
Called from file "sources/harbor_input.ml", line 46, characters 13-27
Called from file "sources/harbor_input.ml", line 452, characters 10-282
Called from file "lang/lang.ml", line 391, characters 30-37
Called from file "lang/lang.ml", line 402, characters 8-15
Called from file "lang/lang_values.ml", line 964, characters 14-20
Called from file "lang/lang_values.ml", line 1029, characters 18-31
Called from file "lang/lang.ml", line 630, characters 14-38
Called from file "tools/tutils.ml", line 85, characters 14-18
Re-raised at file "tools/tutils.ml", line 85, characters 48-55
Called from file "lang/lang.ml", line 656, characters 8-12
Re-raised at file "lang/lang.ml", line 765, characters 43-50
Called from file "lang/lang.ml", line 778, characters 8-242
Called from file "lang/lang.ml", line 788, characters 4-76
Called from file "main.ml", line 113, characters 34-40
Called from file "main.ml", line 615, characters 6-16
Called from file "runner.ml", line 30, characters 14-31

**Comment by NTShop** [comment] 2017-03-20 23:29
Oh wait!  I think it works. Apparently the command I used to gen a self-signed cert didn't create a cert/key that liquidsoap could load, or so it seems, I regenerated the cert using this command below and liquidsoap starts so I'll test now to see if I can connect to it via wss:// 

openssl req -new -x509 -days 365 -nodes -out /etc/ssl/cert.pem -keyout /etc/ssl/cert.key

**Comment by NTShop** [comment] 2017-03-21 03:12
Well it sort of works. I can start liquidsoap using a Letsencrypt SSL cert that is valid for the host that liquidsoap is running on (Apache works with it, NodeJS works with). However, when I try using Webcaster/Webcast.js the connection to Liquidsoap via wss://user:hackme@blahblah.tld:9000/live it doesn't totally connect. I see in the liquidsoap console "New client connection on port ... [etc etc]" but it just sits there, and debug in my browser is telling me that the connection is not open yet. If I click the Refresh button in the browser to refresh the page then interestingly enough, in the liquidsoap logging I see this: 

2017/03/21 03:05:15 [harbor:4] New client on port 9000: X.X.X.X  [ADDRESS REDACTED]
2017/03/21 03:05:32 [harbor:4] Header: Host, value: host.domain.tld: 9000. [DOMAIN REDACTED]
2017/03/21 03:05:32 [harbor:4] Header: Connection, value: Upgrade.
2017/03/21 03:05:32 [harbor:4] Header: Pragma, value: no-cache.
2017/03/21 03:05:32 [harbor:4] Header: Cache-Control, value: no-cache.
2017/03/21 03:05:32 [harbor:4] Header: Upgrade, value: websocket.
2017/03/21 03:05:32 [harbor:4] Header: Origin, value: https://host.domain.tld:9002.
2017/03/21 03:05:32 [harbor:4] Header: Sec-WebSocket-Version, value: 13.
2017/03/21 03:05:32 [harbor:4] Header: User-Agent, value: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.98 Safari/537.36.
2017/03/21 03:05:32 [harbor:4] Header: Accept-Encoding, value: gzip, deflate, sdch, br.
2017/03/21 03:05:32 [harbor:4] Header: Accept-Language, value: en-US,en;q=0.8.
2017/03/21 03:05:32 [harbor:4] Header: Cookie, value: dashboard_cookie=s%3Aj%3A%7B%22tookeystuff%22%3A%22s%3A09879684983752668.eASsAgoUxPA%2Fa2CUv0khwqvQIrzy5%2FuHCr4tmmikhxw%22%7D.wP3pXAAmK1jYnUoJD72IqSqd8tijt9UaR4w7tGI8Xpc; 2017/03/21 03:05:32 [harbor:4] Header: Sec-WebSocket-Key, value: oxnfa9VPJCRRXaAxnQR9eg==.
2017/03/21 03:05:32 [harbor:4] Header: Sec-WebSocket-Extensions, value: permessage-deflate; client_max_window_bits.
2017/03/21 03:05:32 [harbor:4] Header: Sec-WebSocket-Protocol, value: webcast.

HOWEVER, if I start chrome from a command line to disable all of its "insecure origin checking" stuff using the command below, THEN I connect to liquidsoap via wss://etcetcetc .. 

`/usr/bin/google-chrome-stable --unsafely-treat-insecure-origin-as-secure="http://host.domain.tld:9002" --user-data-dir=/tmp/google`


Any idea why this is happening?

**Comment by toots** [comment] 2017-03-21 04:12
Are you connecting from a HTTP or HTTPS origin/webpage?

**Comment by toots** [comment] 2017-03-21 04:13
Also, websocket connections should start like a normal HTTP request, later upgraded to websocket. Do you see anything in the network panel in your browser's debugging console?

**Comment by NTShop** [comment] 2017-03-21 15:49
The origin page is loaded over SSL for this test. The only think I saw in the network section of the debug console was: For Chrome, nothing. For Firefox, after some amount of time (maybe 15 to 30 second) Firefox would emit an error saying that it couldn't connect to the liquidsoap socket. 

To be clear, this was using the master branch from GIT. Has the master branch been tested for SSL connections over harbor.input.ssl? Or should I be using the code from #2ae98c2 instead? 

https://github.com/savonet/liquidsoap/tree/2ae98c2b4bc832bb63b87d8200609426fba998af

As a workaround, I decided to use stunnel4 on the same remote server as liquidsoap to proxy the connection, so stunnel4 takes a SSL connection from the browser then tunnels that connection into liquidsoap over a non-SSL harbor.input(). This works and allows me to use SSL from the client out to the remote server running liquidsoap without Chrome or Firefox complaining about insecure socket connections. Yay!

**Comment by NTShop** [comment] 2017-03-24 21:41
**Update:** Re-tested today, Chrome (v57.0.2987.110) works fine it connects as expected. Firefox (v52.0.1) does not. Firefox hangs during the connection negotiation and the Liquidsoap console simply shows "New client on port 9000: [IP ADDRESS REDACTED]" ... it never proceeds past that. While waiting to see what happens, after 25 seconds Firefox emits this into the debug console: "Firefox can’t establish a connection to the server at wss://host.domain.tld:9000/live." (I redacted the actual host name).

These tests were done against a remote server running liquidsoap using input.harbor.ssl() with a valid Letsencrypt SSL certificate. Local client system running Ubuntu 16.04.  The entire remote server is SSL, that means Apache, Node/Express, Liquidsoap, everything with an open port. The Node system is serving up Webcaster/Webcast.js over SSL to the client. All that works fine. Except Firefox won't connect to Liquidsoap and Chrome will.

**Comment by toots** [comment] 2017-03-28 14:34
Thanks for keeping track of this. Are you able to connect with Firefox in non-SSL mode? Trying to figure out if this is an issue with the implementation of web sockets or in the SSL encryption layer..

**Comment by NTShop** [comment] 2017-03-28 23:04
Yes, I can connect with Firefox to liquidsoap over plain HTTP, it's only the SSL that doesn't connect.

**Comment by NTShop** [comment] 2017-04-05 02:51
Ok I test again using Webcaster/Webcast/Liquidsoap. Firefox definitely fails to connect, Chrome connects Ok. And since Webcast is using the browser's native Websocket to make the connect to Liquidsoap I'd say the Firefox implementation is different than Chrome. You should either figure out what it is about the Firefox Websocket or maybe switch to using something like socket.io instead if possible.

**Comment by toots** [comment] 2017-04-06 18:42
Ok thanks for all this testing. I plan on looking at this very seriously before the next release (soon!)

**Comment by toots** [comment] 2017-04-11 21:44
Ok, I've managed to make it work with Firefox. I had to:
* Use the same certificate and key for the webcaster test server (pushing commit adding `make ssl` there in a sec) and liquidsoap's `input.harbor`
* Open `https://localhost:8000` in Firefox, adding security exception for my self-signed certificate
* Open `https://localhost:8080` in Firefox to add security exception for the certificate as served by `input.harbor`
* Update websocket address to start with `wss://..` in webcaster's page.
* Start streaming

Could you try to reproduce these steps? I know that you've been using a proper let's encrypt certificate but if you can confirm that it works this way, at least we'd have narrowed the problem down to the actual certificate file.. Thanks!

**Comment by NTShop** [comment] 2017-04-14 01:59
Ok, I'll try that tomorrow (Friday).

**Comment by NTShop** [comment] 2017-04-14 15:42
Not sure why, but when I clone to github repo, pin it, and then try to run opam to install it I get this error message: 
`git clone https://github.com/savonet/liquidsoap.git
cd liquidsoap
opam pin add liquidsoap .
liquidsoap is now path-pinned to /home/evengii/liquidsoap

[WARNING] Rsync partially failed:
          symlink has no referent: "/home/evengii/liquidsoap/bootstrap"
          rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1183) [sender=3.1.1]

[liquidsoap] /home/evengii/liquidsoap/ synchronized
[liquidsoap] Installing new package description from /home/test/liquidsoap

liquidsoap needs to be installed.
The following actions will be performed:
  ∗  install conf-pkg-config 1.0              [required by conf-libpcre]
  ∗  install conf-m4         1                [required by ocamlfind]
  ∗  install ocamlbuild      0.11.0           [required by camlp4, cppo, pcre]
  ∗  install conf-libpcre    1                [required by pcre]
  ∗  install ocamlfind       1.7.1            [required by liquidsoap]
  ∗  install camlp4          4.04+1           [required by duppy]
  ∗  install mm              0.3.0            [required by liquidsoap]
  ∗  install dtools          0.3.2            [required by liquidsoap]
  ∗  install base-bytes      base             [required by cppo, pcre]
  ∗  install pcre            7.2.3            [required by liquidsoap]
  ∗  install cppo            1.4.1            [required by camomile]
  ∗  install duppy           0.5.2            [required by liquidsoap]
  ∗  install camomile        0.8.5            [required by liquidsoap]
  ∗  install liquidsoap      dev*  
===== ∗  14 =====
Do you want to continue ? [Y/n] 

`

**Comment by toots** [comment] 2017-04-14 15:58
Yeah, you need to enable the submodules:

git submodule init
git submodule update

(from memory)

2017-04-14 10:42 GMT-05:00 NT Shop <notifications@github.com>:

**Comment by NTShop** [comment] 2017-04-14 16:58
It works on localhost using a self-signed certs. I will test on a server on the net using a LetsEncrypt cert.

**Comment by NTShop** [comment] 2017-04-14 17:56
Well I can't seem to get it to work on a live server on the net, I see the same symptoms. 

If you want, you can test this on a server on the net fairly easy by getting the cheapest server at Linode.com, which only costs $0.08 USD per hour (so if you only use it for 2 hours then remove it you pay $0.16). You'd need to create the server, install an OS image, set a root password, then SSH in and install a LAMP stack which is easy enough. Then set up Letsencrypt (free SSL certs) and there is a script for that if you use Ubuntu - use the doc at DigitalOcean linked below, it's the same process on any Ubuntu system (you simply install a python script via apt-get to automatically get the cert and install it in /etc/letencrypt, plus it configs apache ssl for you), you do need a live domain of course so you that can add a DNS record to point a hostname at your Linode server IP (Letsencrypt won't issue a cert for localhost ).

https://www.digitalocean.com/community/tutorials/how-to-secure-apache-with-let-s-encrypt-on-ubuntu-16-04

If you do that, letsencrypt puts the cert stuff into files named cert.pem, fullchain.pem, and privkey.pem. I've tried using cert.pem / privkey.pem, and fullchain.pem / privkey.pem -- neither combo works. I don't think it's a cert problem, but maybe I'm wrong.

**Comment by NTShop** [comment] 2017-04-14 18:08
Just a thought, I don't know a lot about SSL under the hood, but I know SSL2 is being deprecated in favor of SSL3. Could it be you're not supporting SSL3?

**Comment by toots** [comment] 2017-04-15 14:46
Thanks for your perseverance. I'm gonna try it, it's about time I get a try at this Let's Encrypt thing :-)

**Comment by toots** [comment] 2017-04-15 16:17
So, I was able to make it work from this page: [https://dev.liquidsoap.fm:8000/](https://dev.liquidsoap.fm:8000/), streaming to: `wss://source:hackme@dev.liquidsoap.fm:8080/test`. It worked with Firefox 49 and 52:

```
2017/04/15 16:15:41 [harbor:4] New client on port 8080: 172.30.0.79
2017/04/15 16:15:41 [harbor:4] Header: Host, value: dev.liquidsoap.fm:8080.
2017/04/15 16:15:41 [harbor:4] Header: User-Agent, value: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:52.0) Gecko/20100101 Firefox/52.0.
2017/04/15 16:15:41 [harbor:4] Header: Accept, value: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8.
2017/04/15 16:15:41 [harbor:4] Header: Accept-Language, value: en-US,en;q=0.5.
2017/04/15 16:15:41 [harbor:4] Header: Accept-Encoding, value: gzip, deflate, br.
2017/04/15 16:15:41 [harbor:4] Header: Sec-WebSocket-Version, value: 13.
2017/04/15 16:15:41 [harbor:4] Header: Origin, value: https://dev.liquidsoap.fm:8000.
2017/04/15 16:15:41 [harbor:4] Header: Sec-WebSocket-Protocol, value: webcast.
2017/04/15 16:15:41 [harbor:4] Header: Sec-WebSocket-Extensions, value: permessage-deflate.
2017/04/15 16:15:41 [harbor:4] Header: Sec-WebSocket-Key, value: i5QckWkUZo4m4hTRRaZWYw==.
2017/04/15 16:15:41 [harbor:4] Header: Connection, value: keep-alive, Upgrade.
2017/04/15 16:15:41 [harbor:4] Header: Pragma, value: no-cache.
2017/04/15 16:15:41 [harbor:4] Header: Cache-Control, value: no-cache.
2017/04/15 16:15:41 [harbor:4] Header: Upgrade, value: websocket.
2017/04/15 16:15:42 [harbor:4] Mime type: audio/mpeg
2017/04/15 16:15:42 [harbor:4] Mount point: /test
2017/04/15 16:15:42 [harbor:4] Client logged in.
2017/04/15 16:15:42 [decoder:4] Trying method "WAV" for "audio/mpeg"...
2017/04/15 16:15:42 [decoder:4] Trying method "AIFF" for "audio/mpeg"...
2017/04/15 16:15:42 [decoder:4] Trying method "PCM/BASIC" for "audio/mpeg"...
2017/04/15 16:15:42 [decoder:4] Trying method "RAW AUDIO" for "audio/mpeg"...
2017/04/15 16:15:42 [decoder:4] Trying method "OGG" for "audio/mpeg"...
2017/04/15 16:15:42 [decoder:4] Trying method "MAD" for "audio/mpeg"...
2017/04/15 16:15:42 [decoder:3] Method "MAD" accepted "audio/mpeg".
2017/04/15 16:15:42 [threads:3] Created thread "harbor source feeding" (2 total).
2017/04/15 16:15:42 [input(dot)harbor(dot)ssl_6047:3] Decoding...
```

**Comment by l1n** [comment] 2017-04-15 19:36
I can confirm that we use firefox + webcaster.js + liquidsoap + wss in production.

**Comment by toots** [comment] 2017-04-15 19:43
Ok, thanks @l1n! I'm gonna close the issue, then. @NTShop, feel free to add more information if you anything more to share.

**Comment by NTShop** [comment] 2017-04-15 20:28
The post referenced secure (SSL / wss:// ) connections, which only
    recently were enabled in the core code. 
    
    
    On 04/15/2017 01:36 PM, Lin wrote:
    
    
      I can confirm that we use firefox + webcaster.js + liquidsoap +
        wss in production.
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/savonet/liquidsoap","title":"savonet/liquidsoap","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/savonet/liquidsoap"}},"updates":{"snippets":[{"icon":"PERSON","message":"@l1n in #402: I can confirm that we use firefox + webcaster.js + liquidsoap + wss in production."}],"action":{"name":"View Issue","url":"https://github.com/savonet/liquidsoap/issues/402#issuecomment-294313587"}}}

**Comment by toots** [comment] 2017-04-15 21:31
That's true. @l1n: are y'all using SSL websockets?

**Comment by NTShop** [comment] 2017-04-15 22:20
Possibly a platform related issue for Firefox, which operating system are you testing with? I'm using Ubuntu 16.04.

**Comment by l1n** [comment] 2017-04-15 22:57
@toots: Yes, we are.

**Comment by NTShop** [comment] 2017-04-15 23:16
So I tried your server on my Firefox, using this `wss://source:hackme@dev.liquidsoap.fm:8080/test` and it works. Apparently there's something wrong with my build or config. 

Did you use the Letsencrypt fullchain.pem or cert.pem? 

Also here's how I did the build for liquidsoap: 

- Made sure .opam dir in the user's directory was deleted
- opam init --comp=4.04.0
- eval `opam config env`
- git clone https://github.com/savonet/liquidsoap.git
- cd liquidsoap
- git submodule init
- git submodule update
- opam pin add liquidsoap .

At that point opam says liquidsoap needs to be rebuilt, so I respond Y and it did some stuff. Then I installed dependencies: 

- opam install taglib mad lame vorbis cry ssl
- cd ocaml-duppy
- opam pin add duppy .

duppy rebuilds, then:

- opam install liquidsoap

After the build I use a simple startup.liq file and run the newly built liquidsoap binary (testserver.me below is a fictitious domain, actual domain redacted since this post is public) : 

set( 'harbor.verbose', true )
set( "harbor.bind_addr", "0.0.0.0" )
set( "harbor.ssl.certificate", '/etc/letsencrypt/archive/testserver.me/**fullchain3.pem**' );
set( "harbor.ssl.private_key", '/etc/letsencrypt/archive/testserver.me/**privkey3.pem**' );
live = input.harbor.ssl( 'live', port=8080, user="source", password="hackme")
out = output.icecast( %mp3(bitrate=64, samplerate=48000, id3v2=true), fallible=true, host="testserver.me", port=8000, user="source", password="hackme", mount="listen.mp3", radio)

Then I try to connect with Firefox and Webcaster to wss://source:hackme@testserver.me:8080/live. 

Same result. Won't fully connect. I see that it connects to liquidsoap but the connection is never upgraded to a websocket. 

Did I do the build wrong or use the wrong opam compiler version?

**Comment by toots** [comment] 2017-04-15 23:24
Unfortunately, that looks exactly like the steps that I followed. I also did it in a Ubuntu 10.04. Only difference is my Firefox client runs in OSX.. :-/

**Comment by toots** [comment] 2017-04-15 23:24
I used the certbot client to generate the certificate: https://certbot.eff.org/

**Comment by NTShop** [comment] 2017-04-15 23:27
I'll gen a new cert using certbot and try again. Could be the cert, dunno, the cert works for the web site itself no problem.

**Comment by NTShop** [comment] 2017-04-15 23:47
Oh, looks like I was wrong, when testing your dev site I didn't wait long enough for any sort of error report. _Firefox did not connect to liquidsoap, after nearly 60 seconds I get the same error that I see when testing on my own server: `Firefox can’t establish a connection to the server at wss://dev.liquidsoap.fm:8080/test.`

I then decided to dust off my Windows 10 box, boot that machine, and tried it there with Firefox 52.0.2 -- same error.

**Comment by toots** [comment] 2017-04-15 23:49
@NTShop: I have stopped the harbor running there. Just restarted it if you want to test again.

**Comment by NTShop** [comment] 2017-04-15 23:49
Ok, I will retest now.

**Comment by toots** [comment] 2017-04-15 23:58
Looks like it did work:

```
2017/04/15 23:55:58 [harbor:4] New client on port 8080: 172.30.0.79
2017/04/15 23:55:58 [harbor:4] Header: Host, value: dev.liquidsoap.fm:8080.
2017/04/15 23:55:58 [harbor:4] Header: User-Agent, value: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0.
2017/04/15 23:55:58 [harbor:4] Header: Accept, value: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8.
2017/04/15 23:55:58 [harbor:4] Header: Accept-Language, value: en-US,en;q=0.5.
2017/04/15 23:55:58 [harbor:4] Header: Accept-Encoding, value: gzip, deflate, br.
2017/04/15 23:55:58 [harbor:4] Header: Sec-WebSocket-Version, value: 13.
2017/04/15 23:55:58 [harbor:4] Header: Origin, value: https://dev.liquidsoap.fm:8000.
2017/04/15 23:55:58 [harbor:4] Header: Sec-WebSocket-Protocol, value: webcast.
2017/04/15 23:55:58 [harbor:4] Header: Sec-WebSocket-Extensions, value: permessage-deflate.
2017/04/15 23:55:58 [harbor:4] Header: Sec-WebSocket-Key, value: pCdxxZ5gMVIGCSCEQImtJQ==.
2017/04/15 23:55:58 [harbor:4] Header: Connection, value: keep-alive, Upgrade.
2017/04/15 23:55:58 [harbor:4] Header: Pragma, value: no-cache.
2017/04/15 23:55:58 [harbor:4] Header: Cache-Control, value: no-cache.
2017/04/15 23:55:58 [harbor:4] Header: Upgrade, value: websocket.
2017/04/15 23:55:58 [harbor:4] Mime type: audio/mpeg
2017/04/15 23:55:58 [harbor:4] Mount point: /test
2017/04/15 23:55:58 [harbor:4] Client logged in.
```

**Comment by NTShop** [comment] 2017-04-16 00:10
Ok, retested on Ubuntu and Windows 10, works on both via Firefox. That leaves something wrong in my build (I did try a new cert via certbot, same result). But I have no idea what it might be. You have any ideas? I used opam compiler 4.04.0 as someone had told me to do that since I didn't have any compiler on my system, was that version Ok?

**Comment by toots** [comment] 2017-04-16 00:21
I don't think it matters much but for what it's worth, I used the packaged compiled (`ocaml-nox`). My suggestion would be more to look at the network layer. Is there anything special about this server? Mine is an EC2 instance running behind a load balancer.

**Comment by NTShop** [comment] 2017-04-16 00:26
It's a server sitting directly on the net, nothing in front of it, not even a firewall. It's a throw-away test box at Linode. I can connect to other websockets on the same system, for example a NodeJS service.

**Comment by NTShop** [comment] 2017-04-16 02:39
Ok, after rebuilding several times using various approaches I finally got it to work. So your SSL implementation works on Ubuntu/Firefox!  Thanks for your patience on this. 

Any idea when you intend to do a new version release and put it in the opam repository?

**Comment by toots** [comment] 2017-04-16 15:20
Good to hear! Were you able to maybe point to a couple of possible sources for your issue?

I plan on releasing a new version soon. All the bindings/modules have been released already, I'm now focused on fixing bugs (which yours was on top) and writing some documentation..

**Closed by toots** 2017-04-16 15:20 UTC

**Comment by NTShop** [comment] 2017-04-16 18:40
I'm not entirely sure how I got it to work, I was trying to do the opam install but on liquidsoap compilation was failing with an exit code 127 or similar and no info about why. So then I decided maybe I can build it manually so I cloned a second copy and started doing the manual build and got to the point of an error saying duppy version needed to be newer, then I had an ah ha! moment and realized the opam build was failing for the same reason. Then I stopped working on the manual build, went back to the 1st copy, cloned ocaml-duppy, pinned it, and then did the opam install. That worked, then I got a cert, did the config, and tried it, it worked.

So today I went back and did a complete manual build with a new user and that works too after setting up SSL and input.harbor.ssl() : 

- opam init --comp=4.04.0
- eval \`opam config env\`
- opam install taglib mad lame vorbis cry ssl liquidsoap
- git clone https://github.com/savonet/liquidsoap.git
- cd liquidsoap
- git submodule init
- git submodule update
- cd../
- git clone https://github.com/savonet/ocaml-duppy.git
- cd ocaml-duppy
- git submodule init
- git submodule update
- opam pin add duppy .
- cd ../liquidsoap
- ./bootstrap
- ./configure
- ./make
- ./make install

**Comment by NTShop** [comment] 2017-04-16 18:52
One note about certs, they must be readable by the user account liquidsoap runs under. But on many systems the certs in /etc/ssl ( or /etc/letsencrypt if that's being used) are limited to root and/or ssl-cert group (name may vary depending on OS). An easy way to grant access is to add the liquidsoap user to the ssl-cert group (or whichever group has read access to the cert dir/files. This is helpful particularly when using Letsencrypt since their certs are only valid for 90 days, so cert updates can happen several times a year, meaning if you decide to simply copy certs for the liquidsoap user then a re-copy needs to be done every time the certs updates. So it's easy to just grant read access via the group that can read certs.
