### ISSUE TITLE
Ongoing Issue with Skipping to Next Track After Live DJ Disconnects

### ISSUE THREAD

**Issue by SlvrEagle23** [savonet/liquidsoap#1548] opened 2021-03-24 19:34 UTC
We've had an ongoing issue with AzuraCast honestly for many years now, and we've never been able to find a solution to this issue, but I have several users filing issues in our repositories about this problem and I've never been able to give them a reliable update on the progress of this situation, so I wanted to follow up and see how things are going with regard to it.

Basically, the issue is that when a live DJ disconnects from the stream, we don't want the AutoDJ to just keep playing the track it was playing before the DJ connected. In many cases, a station will have multiple DJs over the course of multiple hours, separated only by a few seconds between each of them, which means the same song will continue to play, a few seconds at a time, over the course of a full day, which not only wreaks havoc with our "Now Playing" API scripts but also is a fairly unpleasant experience for the listener.

We're aware of the existence of `fallback.skip` as an existing operator, but we've never been able to get it to work correctly (it never refers to a track that we specify via our "Next Song" script, it always falls back to the fallback playlists instead, which is not what we want to happen); I've been informed from other users that Centova Cast also attempted and was unable to solve this problem, instead simply not implementing it in their code.

If anyone can provide any code examples to play with, or can provide any insight into why the existing `fallback.skip` doesn't work in our situation or possible solutions to that issue, it would be greatly appreciated.

The latest version of our AzuraCast auto-generated Liquidsoap configuration script is included below for reference:

```
# WARNING! This file is automatically generated by AzuraCast.
# Do not update it directly!


set("init.daemon", false)
set("init.daemon.pidfile.path","/var/azuracast/stations/azuratest_radio/config/liquidsoap.pid")
set("log.stdout", true)
set("log.file", false)
set("server.telnet",true)
set("server.telnet.bind_addr","0.0.0.0")
set("server.telnet.port", 8004)
set("harbor.bind_addrs",["0.0.0.0"])

set("tag.encodings",["UTF-8","ISO-8859-1"])
set("encoder.encoder.export",["artist","title","album","song"])

setenv("TZ", "UTC")

azuracast_api_auth = ref "(PASSWORD)"
ignore(azuracast_api_auth)

autodj_is_loading = ref true
ignore(autodj_is_loading)

autodj_ping_attempts = ref 0
ignore(autodj_ping_attempts)

playlist_sequential_test = playlist(id="playlist_sequential_test",mode="normal",reload_mode="watch",conservative=true,default_duration=10.,length=20.,"/var/azuracast/stations/azuratest_radio/playlists/playlist_sequential_test.m3u")
playlist_sequential_test = audio_to_stereo(id="stereo_playlist_sequential_test", playlist_sequential_test)
playlist_sequential_test = cue_cut(id="cue_playlist_sequential_test", playlist_sequential_test)

# Standard Playlists
radio = random(id="standard_playlists", weights=[3], [playlist_sequential_test])

# AutoDJ Next Song Script
def autodj_next_song() =
    uri = list.hd(get_process_lines(env=[("API_AUTH", !azuracast_api_auth)], 'curl -s --request POST --url http://web/api/internal/1/nextsong --form api_auth="$API_AUTH"'), default="")
    log("AzuraCast Raw Response: #{uri}")

    if uri == "" or string.match(pattern="Error", uri) then
        []
    else
        r = request.create(uri)
        if request.resolve(r) then
            [r]
        else
            []
       end
    end
end

# Delayed ping for AutoDJ Next Song
def wait_for_next_song(autodj)
    autodj_ping_attempts := !autodj_ping_attempts + 1
    delay = ref 0.5

    if source.is_ready(!autodj) then
        log("AutoDJ is ready!")

        autodj_is_loading := false
        delay := -1.0
    elsif !autodj_ping_attempts > 200 then
        log("AutoDJ could not be initialized within the specified timeout.")

        autodj_is_loading := false
        delay := -1.0
    end

    !delay
end

dynamic = request.dynamic.list(id="next_song", timeout=20., retry_delay=2., autodj_next_song)
dynamic = audio_to_stereo(id="stereo_next_song", dynamic)
dynamic = cue_cut(id="cue_next_song", dynamic)

dynamic_startup = fallback(
    id = "dynamic_startup",
    track_sensitive = false,
    [
        dynamic,
        at(
            fun()-> !autodj_is_loading,
            blank(id = "autodj_startup_blank", duration = 120.)
        )
    ]
)
radio = fallback(id="autodj_fallback", track_sensitive = true, [dynamic_startup, radio])

ref_dynamic = ref dynamic;
add_timeout(0.25,fun()->wait_for_next_song(ref_dynamic))

requests = request.queue(id="requests")
requests = audio_to_stereo(id="stereo_requests", requests)
requests = cue_cut(id="cue_requests", requests)

radio = fallback(id="requests_fallback", track_sensitive = true, [requests, radio])
add_skip_command(radio)

radio = crossfade(smart=false, duration=3.00,fade_out=2.00,fade_in=2.00,radio)

# DJ Authentication
live_enabled = ref false
last_authenticated_dj = ref ""
live_dj = ref ""

def dj_auth(auth_user,auth_pw) =
    user = ref ""
    password = ref ""

    if (auth_user == "source" or auth_user == "") and (string.match(pattern="(:|,)+", auth_pw)) then
        auth_string = string.split(separator="(:|,)", auth_pw)

        user := list.nth(default="", auth_string, 0)
        password := list.nth(default="", auth_string, 2)
    else
        user := auth_user
        password := auth_pw
    end

    log("Authenticating DJ: #{!user}")

    ret = list.hd(get_process_lines(env=[("DJ_USER", !user), ("DJ_PASSWORD", !password), ("API_AUTH", !azuracast_api_auth)], 'curl -s --request POST --url http://web/api/internal/1/auth --form dj-user="$DJ_USER" --form dj-password="$DJ_PASSWORD" --form api_auth="$API_AUTH"'), default="")
    log("AzuraCast DJ Auth Response: #{ret}")

    authed = bool_of_string(ret)
    if (authed) then
        last_authenticated_dj := !user
    end

    authed
end

def live_connected(header) =
    dj = !last_authenticated_dj
    log("DJ Source connected! Last authenticated DJ: #{dj} - #{header}")

    live_enabled := true
    live_dj := dj

    ret = list.hd(get_process_lines(env=[("DJ_USER", dj), ("API_AUTH", !azuracast_api_auth)], 'curl -s --request POST --url http://web/api/internal/1/djon --form dj-user="$DJ_USER" --form api_auth="$API_AUTH"'), default="")
    log("AzuraCast Live Connected Response: #{ret}")
end

def live_disconnected() =
    dj = !live_dj

    log("DJ Source disconnected! Current live DJ: #{dj}")

    ret = list.hd(get_process_lines(env=[("DJ_USER", dj), ("API_AUTH", !azuracast_api_auth)], 'curl -s --request POST --url http://web/api/internal/1/djoff --form dj-user="$DJ_USER" --form api_auth="$API_AUTH"'), default="")
    log("AzuraCast Live Disconnected Response: #{ret}")

    live_enabled := false
    last_authenticated_dj := ""
    live_dj := ""
end

# A Pre-DJ source of radio that can be broadcast if needed',
radio_without_live = radio
ignore(radio_without_live)

# Live Broadcasting
live = audio_to_stereo(input.harbor("/", id = "input_streamer", port = 8005, auth = dj_auth, icy = true, icy_metadata_charset = "UTF-8", metadata_charset = "UTF-8", on_connect = live_connected, on_disconnect = live_disconnected, buffer = 5.00, max = 10.00))
ignore(output.dummy(live, fallible=true))

radio = fallback(id="live_fallback", replay_metadata=false, track_sensitive=false, [live, radio])

# Allow for Telnet-driven insertion of custom metadata.
radio = server.insert_metadata(id="custom_metadata", radio)

# Apply amplification metadata (if supplied)
radio = amplify(override="liq_amplify", 1., radio)

radio = fallback(id="safe_fallback", track_sensitive = false, [radio, single(id="error_jingle", "/usr/local/share/icecast/web/error.mp3")])

# Send metadata changes back to AzuraCast
def metadata_updated(m) =
    def f() =
        if (m["song_id"] != "") then
            ret = list.hd(get_process_lines(env=[("SONG", m["song_id"]), ("MEDIA", m["media_id"]), ("PLAYLIST", m["playlist_id"]), ("API_AUTH", !azuracast_api_auth)], 'curl -s --request POST --url http://web/api/internal/1/feedback --form song="$SONG" --form media="$MEDIA" --form playlist="$PLAYLIST" --form api_auth="$API_AUTH"'), default="")
            log("AzuraCast Feedback Response: #{ret}")
        end
        (-1.)
    end

    add_timeout(fast=false, 0., f)
end

radio = on_metadata(metadata_updated,radio)

# Local Broadcasts
output.icecast(%mp3(samplerate=44100, stereo=true, bitrate=128, id3v2=true), id="local_1", host = "127.0.0.1", port = 8000, password = "(PASSWORD)", mount = "/radio.mp3", name = "AzuraTest Radio", description = "A test radio station.", genre = "", public = false, encoding = "UTF-8", radio)
output.icecast(%mp3(samplerate=44100, stereo=true, bitrate=64, id3v2=true), id="local_2", host = "127.0.0.1", port = 8000, password = "(PASSWORD)", mount = "/mobile.mp3", name = "AzuraTest Radio", description = "A test radio station.", genre = "", public = false, encoding = "UTF-8", radio)
```

**Comment by martinkirch** [comment] 2021-03-24 20:27
Hello, 
I had a similar issue, and also wanted to crossfade between sources because it's much nicer. The only working implementation I found uses this transition function:

```ocaml
def crossfade_3s(a,b)
    faded = add(normalize=false, [
        fade.in(duration=3., type="exp", b),
        amplify(mkfade(duration=3., start=1., stop=0., type="exp", a) ,a)
    ])
    add_timeout(10., { source.skip(a) ; -1.})
    faded
end

radio = fallback([live_stream, playlists], transitions=[crossfade_3s, crossfade_3s] ...
```
notes:
 * I'm avoiding `fade.out` because it fades only when it detects the end of the track (or maybe not: #1547)
 * skipping only happens if timeout is significantly greater than fade duration - I don't know why

hope this helps !

**Comment by smimram** [comment] 2021-03-24 20:33
Another option is to poll regularly the DJ source and see whether it is available or not (with `source.is_ready`). When it goes from not available to available, we know that the switch will occur and we have to skip. Here is the implementation I have just committed:
```
def fallback.skip(~input,f)
  avail = ref(true)
  def check()
    old = !avail
    avail := source.is_ready(input)
    if not old and !avail then
      source.skip(f)
    end
  end
  s = fallback(track_sensitive=false, [input,f])
  source.on_frame(s, check)
end
```
Instead of using `source.on_frame` to check at every frame you could use `add_timeout` to check at, say, every 1 second, which should be largely enough.

**Comment by smimram** [comment] 2021-03-24 20:34
BTW, in case it helps, here is my test:
```
live = source.available(sine(), {time() mod 5. <= 1.})
music = playlist("~/Music")
radio = fallback.skip(input=live, music)
output(radio)
```
the "live" gets available for 1 second every 5 seconds and I do year my music tracks starting at beginning.

**Comment by SlvrEagle23** [comment] 2021-03-24 20:37
@smimram While I'm sure this would work, this just falls back to a _different_ problem, which is that skipping causes Liquidsoap to "jump the rails" off the `request.dynamic.list` and fall back to a track that isn't provided by the "next song" script. This fundamentally prevents anything that depends on `.skip` from working as we expect.

I'm not sure if there's any fix for that planned or on the roadmap.

**Comment by smimram** [comment] 2021-03-24 20:48
I am not sure I understand exactly what you mean here. In my example, I am using the `playlist` operator which is actually implemented using `request.dynamic`. Would it be possible for you to come up with a minimal example?

We really need to rework `fallback` / `switch` in depth, but this is very sensitive and I fear this will be for post-2.0...

**Comment by SlvrEagle23** [comment] 2021-03-24 20:56
@smimram if I have time to do so, I'll look into it, but the easiest examples I can provide are the ones generated by AzuraCast itself (including the one listed above), as these are the users and scenarios I support on a regular basis.

Basically, what happens is that if you call `skip` on a `request.dynamic.list`, it doesn't wait for the command to return the next track it's supposed to play. In the absence of a track being immediately provided by that script, it instead falls back to the fallback playlists for a single track; a few seconds later, the command returns the next song to play, and so the song following the fallback song is one again properly following the request queue. This means any time skip is called, one track in the playback history isn't one of the ones we've specified from our own AutoDJ script, which throws our APIs off quite badly.

I realize these issues may require further development time, and I've brought them up a few times in the past, but I haven't heard anything new about them. To be honest, these two issues (skip song not working correctly, and thus `fallback.skip` not working as expected) represent a significant percentage of the issues we have reported to us on a regular basis via our GitHub. Getting these nailed down and solved would represent a HUGE relief of our support workload and a significant fix to a long-standing issue.

**Comment by martinkirch** [comment] 2021-03-25 06:42
> Basically, what happens is that if you call skip on a request.dynamic.list, it doesn't wait for the command to return the next track it's supposed to play. In the absence of a track being immediately provided by that script, it instead falls back to the fallback playlists for a single track; a few seconds later, the command returns the next song to play, and so the song following the fallback song is one again properly following the request queue.

Then I even more suggest you try my transition operator with `add_timeout` (maybe what you described is why timeout is important :thinking: )

**Comment by smimram** [comment] 2021-03-25 08:33
Ok I could reproduce with
```
files = ref(list.shuffle(playlist.files("~/Music")))
def next_song()
  f = list.hd(!files)
  files := list.tl(!files)
  print("Next song: #{f}")
  request.create(f)
end
s = request.dynamic(conservative=true, {sleep(2.); next_song()})
radio = fallback([s, chop(duration=2., sine(amplitude=.5))])
output(radio)
thread.run(delay=7., every=15., {print("Skipping") ; s.skip()})
```
I have commited two fixes to help with this kind of situtations:
- in 6a10c762ced225fd2d47a303ec17be5e8ec3a578, when you set `conservative=true`, once the current song is playing it should correctly see that the queue is empty and thus fetch a request in advance (i.e. it makes the above example work)
- in 64b31f09f201ae46257ec60e05bb5855b4176da3 I have added some functions to perform this manually: given `s` created by `request.dynamic` you can see the size of the queue with `s.queue_size()` and force prefetching a request with `s.prefetch()`. This means that even if you have `conservative=false` (i.e. the queue thinks there is enough data, but this won't be the case after the skip) you can ensure manually that there is at least one available request:
```
files = ref(list.shuffle(playlist.files("~/Music")))
def next_song()
  f = list.hd(!files)
  files := list.tl(!files)
  print("Next song: #{f}")
  request.create(f)
end
s = request.dynamic({sleep(2.); next_song()})
radio = fallback([s, chop(duration=2., sine(amplitude=.5))])
output(radio)
def skipper ()
  if s.queue_size() == 0 then
    print("Prefetching")
    s.prefetch()
  end
  print("Skipping")
  s.skip()
end
thread.run(delay=7., every=15., skipper)
```

**Comment by SlvrEagle23** [comment] 2021-03-25 18:40
@smimram It looks like the last few commits from the last half hour or so have added a `prefetch` setting to `native.request.queue.list` that likely solves this problem as well. All of the commits have been on the master branch, so I'm assuming this is the development branch for LS 2.0, not necessarily something we can be including directly in our application currently?

**Comment by smimram** [comment] 2021-03-25 18:57
Yes, this is in liq 2.0, and should be part of next release. For current version, I'd suggest trying @martinkirch's suggestion.

**Comment by DJ-Lynx** [comment] 2021-11-05 13:56
This needs fixing as its not productive for users of azuracast to have there live dj title sticking on there streaming players when auto dj kicks back in all other panels have it working its been a long time now and this should have been resolved years back someone actually made a workaround liquidsocap script to add to the azuracast panel 2 yeays back and it worked but since the newer versions of luquidsoap it became redundant please try to fix this issue its very important to me my listeners and my DJ's

**Comment by SlvrEagle23** [comment] 2021-11-18 08:58
Hey all, revisiting this issue now that AzuraCast has shipped Liquidsoap 2.0 and its prefetch mechanism means that the underlying issue preventing this from working properly should be resolved.

I've been able to get a working implementation (the code that @martinkirch suggested near the top of this thread), but it isn't a particularly clean solution, in that you can hear an abrupt cutoff of the live stream, followed a few seconds later by the start of the next song. I'd imagine even this would be preferable to the current situation (of just jumping halfway back into the existing song), so I may end up shipping some equivalent of this.

When I try to go for a cleaner solution (adding `source.skip()` to the `on_disconnect` function), the AutoDJ fades from the live DJ source to the previous playing song, then fades from that to a new track, which is also not what we want.

I'd use `fallback.skip`, but it has no support for the `id` parameter...it seems it wasn't set up to have the full superset of properties that `fallback` has. This may be something that's worthwhile for @smimram or others on the team to look into prior to shipping the 2.0.1 branch, which we plan to use in our next stable release.

All in all, LS 2.0 has brought us _much_ closer to having a perfect working solution for this, so again hats off to the whole team for their hard work on bringing that to a reality. <3

**Comment by SlvrEagle23** [comment] 2021-11-18 10:08
Update: I manually re-implemented the `fallback.skip` to add in the missing things that we use, basically something that looks like:

```
def live_fallback_skip(s,fallback)
    avail = ref(true)
    def check()
        old = !avail
        avail := source.is_ready(s)
        if not old and !avail then
            source.skip(fallback)
        end
    end
    s = stdlib_fallback(id="live_fallback", replay_metadata=false, track_sensitive=false, [s, fallback])
    source.on_frame(s, check)
end

radio = live_fallback_skip(live, radio)
```

...and now, while it does skip the song immediately after transitioning away from the live DJ, it still invokes the crossfade function, so you hear the previous song immediately fade out as the new one plays, and this is also not the expected functionality.

**Comment by DJ-Lynx** [comment] 2021-11-18 15:41
Well this sounds like a great step in the right direction so ive aske my provider if he will set me up a trial so ii can test it :)

**Comment by DJ-Lynx** [comment] 2021-11-21 19:38
Well im testing azuracast as an end user now latest rolling release and nothing is working its just as before Live dj title stays how it is as if im still online live when auto dj comes back on ans song doesnt skip to next one when i disconnect live stream so what exactly has been achieved here i dont understand

**Comment by DJ-Lynx** [comment] 2021-11-21 19:39
and none of this code is in azuracasts liquidsoap config at all def live_fallback_skip(s,fallback)
    avail = ref(true)
    def check()
        old = !avail
        avail := source.is_ready(s)
        if not old and !avail then
            source.skip(fallback)
        end
    end
    s = stdlib_fallback(id="live_fallback", replay_metadata=false, track_sensitive=false, [s, fallback])
    source.on_frame(s, check)
end

radio = live_fallback_skip(live, radio)

This modified version of the transition code from above accomplishes the exact same thing, without the periodic "ping":

def live_in(a,b)
            sequence([a, b])
        end
        
        def live_out(a,b)
            faded = sequence([b, a])
            thread.run.recurrent(delay=10., { source.skip(a) ; -1.})
            faded
        end
        
        radio = fallback(id="live_fallback", replay_metadata=false, track_sensitive=false, transitions=[live_out,

**Comment by DJ-Lynx** [comment] 2021-11-21 19:40
???

**Comment by SlvrEagle23** [comment] 2021-11-21 19:43
@DJ-Lynx I didn't say in my issue that I had actually implemented these things into AzuraCast in any release channel; I haven't, and I indeed am waiting on a response from _this thread_ on how to fix issues relating to crossfading before I do.

As a reminder, again, you're not in the AzuraCast repository, this is the Liquidsoap repository, a tool that AzuraCast happens to use; please don't post here asking about AzuraCast. We have our own GitHub repository and issues section.

**Comment by DJ-Lynx** [comment] 2021-11-21 19:47
ok i must have misread it sorry about that

**Comment by toots** [comment] 2021-11-23 21:15
Hi all!

I'm gonna go ahead and close this issue. Please know that we are doing our best to work with @SlvrEagle23 and AzuraCast to ship all the changes they need as soon as possible!

**Closed by toots** 2021-11-23 21:15 UTC
