### ISSUE TITLE
Liquidsoap CPU to 100% and then crashes

### ISSUE THREAD

**Issue by illestrater** [savonet/liquidsoap#628] opened 2018-09-17 10:55 UTC
I'm unsure if this is a memory leak or if it's an issue with not properly shutting down dynamic transcoders...

Does source.shutdown() completely destroy the transcoder?

Here's my script:

```
set("server.telnet", true)

dyn_sources = ref []

def add_source(uri) =
  url = mksafe(input.http("http://illestrater.com:1337/#{uri}"))
  source = output.icecast(
    %mp3(bitrate=128),
    mount="#{uri}-mp3",
    host="illestrater.com",
    port=1337,
    password="*******",
    fallible=true
  )

  output = source(url)

  dyn_sources := 
      list.append( [(uri, output)],
                    !dyn_sources )
  "transcoding #{uri}"
end

def remove_source(uri) =
  def search(x, y) =
    current_uri = fst(y)
    if current_uri == uri then
      test = snd(y)
      source.shutdown(test)
      (["#{uri} closed"])
    else
      ([])
    end
  end
  result = list.fold(search, ([]), !dyn_sources)
  "#{result}"
end

server.register(namespace="sources",
                description="Start a new dynamic playlist.",
                usage="add <uri>",
                "add",
                add_source)
server.register(namespace="sources",
                description="Start a new dynamic playlist.",
                usage="remove <uri>",
                "remove",
                remove_source)

output.dummy(blank())
```

Any help would be much appreciated!! Thanks :)

**Comment by toots** [comment] 2018-09-17 14:19
Your script looks great, there must be a bug in liquidsoap. I'll try to test it locally. Could you share some of the logs as well? Thks!

**Comment by toots** [comment] 2018-09-19 23:07
Hi,

Quick testing here seems fine with `1.3.4`.
* What version of `liquidsoap` are you using?
* Do you have some reproduction steps/logs to share?

Thanks!

**Comment by illestrater** [comment] 2018-10-01 01:17
hi @toots , thanks for the quick reply! My issue must likely be occurring because I'm using v1.1.1

Apologies for the late response, been working on other things, but now I'm back to working on my streaming services :) I'll rebuild with 1.3.4 and report back!

**Comment by illestrater** [comment] 2018-10-04 03:31
@toots, I've rebuilt Liquidsoap 1.3.3-1 and am running into the same issues. The way that I tested was by running my script and, as it uses telnet for dynamic source creation, created 20 transcoders (telnet command: "sources.add randomstring"), and then killed the 20 transcoders ("sources.remove randomstring"). Monitoring the memory usage, it went up and never came back down.

Provided are some logs: https://pastebin.com/Ga83f3mp

My check of the memory not decreasing is performed by around line ~490 I believe.

**Comment by illestrater** [comment] 2018-10-19 21:15
@toots Apologies for the mention again, but could you look into this one more time? It's a show stopper for my audio platform to be able to scale. It won't work out if I have to manually restart liquidsoap every few days.

**Comment by toots** [comment] 2018-11-10 14:32
Hey. I'm back from a short liquidsoap break. I actually just pushed a fix I believe might have affected all users. Any chance you could try it? You can do it this way, via opam:
```
git clone --recursive https://github.com/savonet/ocaml-duppy.git
cd ocaml-duppy
opam pin add .
```

**Comment by toots** [comment] 2018-11-10 14:47
Ok, nevermind, I think I found your issue. You also need to remove the source from the `dyn_sources` list, otherwise it never gets garbage collected. Just add `dyn_sources := list.remove_assoc(uri,!dyn_sources)` to your script:

```
set("server.telnet", true)

dyn_sources = ref []

def add_source(uri) =
  url = mksafe(input.http("http://illestrater.com:1337/#{uri}"))
  source = output.icecast(
    %mp3(bitrate=128),
    mount="#{uri}-mp3",
    host="illestrater.com",
    port=1337,
    password="*******",
    fallible=true
  )

  output = source(url)

  dyn_sources := 
      list.append( [(uri, output)],
                    !dyn_sources )
  "transcoding #{uri}"
end

def remove_source(uri) =
  def search(x, y) =
    current_uri = fst(y)
    if current_uri == uri then
      test = snd(y)
      source.shutdown(test)
      (["#{uri} closed"])
    else
      ([])
    end
  end
  result = list.fold(search, ([]), !dyn_sources)
  dyn_sources := list.remove_assoc(uri,!dyn_sources)
  "#{result}"
end

server.register(namespace="sources",
                description="Start a new dynamic playlist.",
                usage="add <uri>",
                "add",
                add_source)
server.register(namespace="sources",
                description="Start a new dynamic playlist.",
                usage="remove <uri>",
                "remove",
                remove_source)

output.dummy(blank())
```

If you set the log level to `4`, you can monitor the garbage collection calls and you should see your dynamic sources get cleaned up. It might not happen immediately, though, but as memory grows, the application will eventually reclaim their memory.

I'm closing here since I believe that was the issue. Please reopen if you still see an issue.

**Closed by toots** 2018-11-10 14:47 UTC

**Comment by illestrater** [comment] 2018-11-11 01:36
@toots Thank you for returning to this! Apologies for inquiring your help again, but by using remove_assoc() I am encountering a code error:

```
Starting liquidsoap channels: transcoder.liq At line 39, char 41-53:
  this value has type
    [(_*active_source(_))] (inferred at line 6, char 19-20)
  but it should be a subtype of (the type of the value at /usr/lib/liquidsoap/1.1.1/utils.liq, line 37, char 26)
    [(_*string)] (inferred at /usr/lib/liquidsoap/1.1.1/utils.liq, line 14, char 4)
```

I hate to ask for coding advice, but it's quite difficult for me to understand this language and its errors, but I'm thinking since the list isn't a typical key value pair and its key is actually (uri, output), this is why I'm having troubles? Any advice here?

**Comment by toots** [comment] 2018-11-12 03:10
It looks like you are using an old version of liquidsoap. In version `1.1.1`, `list.remove_assoc` was not as generic and could only process lists of the type: `[(string*string)]`.

However, you can rewrite the operator this way:
```
def list.remove_assoc(label, l) =
  def f(result,element) =
    current_label = fst(element)
    if current_label == label then
      result
    else
      list.add(element,result)
    end
  end
  list.fold(f,[],l)
end
```

**Comment by illestrater** [comment] 2018-11-12 09:01
@toots thank you. I've upgraded our production liquidsoap to 1.3.4 and am using the native function now, and initial tests are showing substantial improvement as you expected! :) Will report back after some time has elapsed, and will test your latest fix for ocaml-duppy if the issue persists before getting back to you.

This has been a huge relief and will allow me to move forward with my project. If you're interested in what we're using liquidsoap for, I'm building a live streaming platform for DJs to play to an online audience called CUE Music (https://cue.dj). We hope to be successful and change how music is consumed, and we most definitely will donate to your project once we start seeking for some sort of revenue and have the means to. Much appreciated.

**Comment by toots** [comment] 2018-11-12 18:48
Glad to hear it's working! Good luck with your project, it looks awesome. As I was saying in the release email, we're hoping to be able to provide a consulting service fairly soon.
