### ISSUE TITLE
Gstreamer.hls keeps trying Forbidden HTTP status URLs

### ISSUE THREAD

**Issue by alexandre1985** [savonet/liquidsoap#762] opened 2019-04-29 11:03 UTC
**Describe the bug**
I am getting a youtube live stream using `gstreamer.hls`.
It is working, but ....
After 6 hours the youtube `.m3u8` URL expires (gives an forbidden status, 403 I guess) and after I can't find a way for `gstreamer.hls` to stop. Actually I want to restart the stream fetching, but I already have coded that in my script.

**To Reproduce**
Here goes my library function that handles youtube live streams. It is called `youtube_live()`.
The script has `youtube-dl` and `jq` programs as dependencies.
```
def youtube_source(ytid) =

	url = get_process_output("youtube-dl -f 93 -g https://youtu.be/#{ytid}")
	json = get_process_output("youtube-dl -j https://youtu.be/#{ytid}")

	title = string.trim(get_process_output("echo '#{json}' | jq -r '.fulltitle'"))
	uploader = string.trim(get_process_output("echo '#{json}' | jq -r '.uploader'"))

	
	def add_title(m)
		[("title","[YouTube] #{title}"),("artist","#{uploader}")]
	end
	
	video_source = gstreamer.hls(url)
	
	audio_source = drop_video(video_source)
	
	map_metadata(strip=true, add_title, audio_source)
end

def youtube_live(ytid) =
	fallback(track_sensitive=false, [youtube_source(ytid), youtube_source(ytid)])
end
```

**Expected behavior**
There should be a parameter `on_error` or something that could make the stream stop instead of keep trying using the same URL, at least the streams that have a Fordibben status.

**Version details**
 - OS: Manjaro Linux Deepin
 - Liquidsoap Version: 1.3.7
 - Opam version: 2.0.4

**Install method**
OPAM

**Comment by mylselgan** [comment] 2019-04-30 13:45
Hi,
I too have issues with gstreamer.hls
toots suggests to use ffmpeg2wav to use the youtube video as a audio track like `"ffmpeg2wav:youtube-dl:-IYXYB0r-Ww"`
Check these 2 issues. https://github.com/savonet/liquidsoap/issues/726 and https://github.com/savonet/liquidsoap/issues/623

I don't know how to use ffmpeg2wav
help me too if you succeed.

**Comment by alexandre1985** [comment] 2019-04-30 14:16
I believe @toots said that if you want use youtube videos as audio you could use `ffmpeg2wav`. But I already have a `drop_video()` in my script, that transforms the video source into audio only source. So that isn't the problem here.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
Em Terça-feira, Abril 30, 2019 1:45 PM, mylselgan <notifications@github.com> escreveu:

**Comment by toots** [comment] 2019-05-03 16:45
I think HLS is the wrong approach for youtube videos since the URL do expire. Using a request-based source seems more appropriate as the video will be re-fetched and processed each time it is needed. Something like:
```
s = single("youtube-dl:<ID>")
```

I'm gonna close this issue since I don't think that there is anything wrong with the HLS input. It is not designed to reload its url. Feel free to continue the conversation here.

**Comment by alexandre1985** [comment] 2019-05-05 06:46
@toots I have tried using
```
s = single("youtube-dl:<LIVE_YOUTUBE_ID>")
```
but it doesn't work.
I seems that `youtube-dl:` cannot handle live youtube streams.

So, if HLS is the wrong approach, what would be the approach to take to handle with youtube live stream?

**Closed** 2019-05-16 16:00 UTC

**Comment by smimram** [comment] 2019-05-16 16:02
I have just added the possibility of chaning the pipeline on a an error. You can now do something like this
```
set("log.file",false)
set("log.stdout",true)
set("log.level",5)

p = ref "uridecodebin uri=file:///badurl/file.mp3"

def on_error(e) =
  print("got an error: #{e}\nCorrecting file name\n\n\n")
  p := "uridecodebin uri=file:///path/to/test.mp3"
  3.
end

s = input.gstreamer.audio(pipeline={!p},on_error=on_error)
output.pulseaudio(mksafe(s))
```
and a similar logic should apply to `gstreamer.hls` (not tested but it uses the above functions).

**Comment by toots** [comment] 2019-05-16 16:07
Wow, very nice!

**Comment by alexandre1985** [comment] 2019-05-16 18:12
@smimram Will try to test this funcionality on my script when I have the time to.
1. I never seen the `ref` and the `{!p}` in any liquidsoap script. Are these OCaml language constructs?
2. Can LiquidSoap accept OCaml language commands?

**Comment by smimram** [comment] 2019-05-17 07:15
No, the Liquidsoap and OCaml language are a completely different thing (Liquidsoap happens to be implemented in OCaml but that's all).
- `ref` creates a reference (a value that you can modify)
- `!` means get the value of the reference
- `:=` means set the value of the reference
- `#{x}` in a string is replaced by the value of `x`
I hope this helps!

**Comment by alexandre1985** [comment] 2019-05-17 08:53
@smimram Yes, it does, thank you.
I would like to know where are those aspects (the ones that you refered) of LiquidSoap documented?

So that I can learn more.

**Comment by mylselgan** [comment] 2019-05-17 16:54
@smimram the pipeline parameter can not be passed to gstreamer.hls

```
At line 23, char 38-41: cannot apply that parameter because the function
  (at line 23, char 14-28) has no argument labeled "pipeline"!
```

how can we use this on gstreamer.hls please give me a simple test script to test in my environment.

**Comment by smimram** [comment] 2019-05-17 18:01
Yes, `gstreamer.hls` simply takes the stream url iin argument. You should do something like this:
```
url = ref "initial url"
def on_error(e) =
  print("got an error: #{e}\n\n\n\n")
  url := "new url....";
  3.
end

s = gstreamer.hls(on_error=on_error,{!url})
output.pulseaudio(mksafe(s))
```

**Comment by mylselgan** [comment] 2019-05-18 03:32
but before testing this script this recent commit breaks my already working script

My script which worked previously
```
url = "http://path to m3u8")
video_source = mksafe(gstreamer.hls(url))
audio_only = drop_video(video_source)
s = fallback(track_sensitive=false, [audio_only])
output.icecast(s)
```
output
```
At line 8, char 36:
  this value has type
    string (inferred at /home/radio/.opam/default/lib/liquidsoap/lib/liquidsoap/scm/utils.liq, line 200 char 74 - line 201 char 79)
  but it should be a subtype of (the type of the value at /home/radio/.opam/default/lib/liquidsoap/lib/liquidsoap/scm/gstreamer.liq, line 29, char 40)
    ()->_ (inferred at /home/radio/.opam/default/lib/liquidsoap/lib/liquidsoap/scm/gstreamer.liq, line 30, char 14)
```

**Comment by mylselgan** [comment] 2019-05-18 08:00
> but before testing this script this recent commit breaks my already working script
> 
> My script which worked previously
> 
> ```
> url = "http://path to m3u8")
> video_source = mksafe(gstreamer.hls(url))
> audio_only = drop_video(video_source)
> s = fallback(track_sensitive=false, [audio_only])
> output.icecast(s)
> ```
> 
it works if change to `video_source = mksafe(gstreamer.hls({url}))` is this expected behavior?.

When testing the following script 

```
url = ref "initial url"
def on_error(e) =
  print("got an error: #{e}\n\n\n\n")
  url := "new url....";
  3.
end

s = gstreamer.hls(on_error=on_error,{!url})
output.pulseaudio(mksafe(s))
```

I get the this error

```
At line 22, char 38:
  this value has type
    (_)->_ (inferred at line 12 char 18 - line 16 char 4)
  but it should be a subtype of (the type of the value at /home/radio/.opam/default/lib/liquidsoap/lib/liquidsoap/scm/gstreamer.liq, line 29, char 26)
    ()->float (inferred at /home/radio/.opam/default/lib/liquidsoap/lib/liquidsoap/scm/gstreamer.liq, line 29, char 35-38)
```

but the stream started without any issue when I change 
`s = gstreamer.hls(on_error={3.},{!url})`
Is this the right approach? will this change the pipeline after 3 retries on_error?

**Comment by smimram** [comment] 2019-05-18 08:28
Thanks for noticing this, it should now be corrected: your old code and my example should go through.

Can you confirm this?

**Comment by mylselgan** [comment] 2019-05-18 15:53
Yes, both works now. I started the test script. I will report here tomorrow how changing pipeline works on error. Thanks.

**Comment by alexandre1985** [comment] 2019-05-21 07:52
I would like to test this new functionality made by @smimram . I have `liquidsoap` installed by `opam`.
When will I be able to test this functionality?

**Comment by smimram** [comment] 2019-05-21 08:45
As explained [here](https://www.liquidsoap.info/doc-dev/install.html), you can build the git version easily:
```
git clone --recursive https://github.com/savonet/liquidsoap.git
cd liquidsoap
opam pin add liquidsoap .
```
We should eventually make a release, but it might take some time.

**Comment by alexandre1985** [comment] 2019-05-21 09:07
Thank you @smimram .

And if I want to revert to my OPAM version should I just `cd` into the git clone directory and then do:
```
opam unpin liquidsoap .
```
? Thank you

**Comment by mylselgan** [comment] 2019-05-21 10:15
> Thank you @smimram .
> 
> And if I want to revert to my OPAM version should I just `cd` into the git clone directory and then do:
> 
> ```
> opam unpin liquidsoap .
> ```
> 
> ? Thank you

`Opam pin remove liquidsoap`
