### ISSUE TITLE
Relaying Another Stream

### ISSUE THREAD

**Issue by bayubad** [savonet/liquidsoap#797] opened 2019-05-25 19:22 UTC
By relaying another stream, I will use a remote streaming server as the source for my broadcast, and rebroadcasting that server's stream as my own.
But it's by design that Liquidsoap saves a copy of that stream locally, which can eventually fill up your server if it's a constant ongoing stream that you don't interrupt with other content. 

Is there any solution to only allocate xGB of space for storing the stream and after reaching the threshold to overwrite it?

**Comment by smimram** [comment] 2019-05-26 17:30
I don't think that Liquidsoap stores a significant portion of an http stream by default. Could you share more of your script? Do you have something quite different from something like
```
output.icecast(input.http(...))
```
?

**Comment by bayubad** [comment] 2019-05-27 08:36
It's a an issue while using AzuraCast. 
https://github.com/AzuraCast/AzuraCast/issues/1586

**Comment by bayubad** [comment] 2019-05-27 11:36
Liquidsoap Log:

Warning: unused variable radio at line 73, character 7.
Warning: unused variable radio at line 63, character 7.
Warning: unused variable radio at line 61, character 7.
Warning: unused variable radio at line 58, character 7.
Warning: unused variable radio at line 55, character 7.
Warning: unused variable radio at line 44, character 7.
Warning: unused variable radio at line 37, character 7.
No output defined, nothing to do.

**Comment by bayubad** [comment] 2019-05-27 18:08
`# WARNING! This file is automatically generated by AzuraCast.
# Do not update it directly!


set("init.daemon", false)
set("init.daemon.pidfile.path","/var/azuracast/stations/radio/config/liquidsoap.pid")
set("log.stdout", true)
set("log.file", false)
set("server.telnet",true)
set("server.telnet.bind_addr","0.0.0.0")
set("server.telnet.port", 8044)
set("harbor.bind_addrs",["0.0.0.0"])

set("tag.encodings",["UTF-8","ISO-8859-1"])
set("encoder.encoder.export",["artist","title","album","song"])

setenv("TZ", "Europe")

# AutoDJ Next Song Script
def azuracast_next_song() =
  uri = list.hd(get_process_lines("curl -s --request POST --url http://web/api/internal/8/nextsong --form api_auth="^quote("TEST")^""), default="")
  log("AzuraCast Raw Response: #{uri}")
  
  if uri == "" or string.match(pattern="Error", uri) then
    log("AzuraCast Error: Delaying subsequent requests...")
    system("sleep 5")
    request.create("")
  else
    request.create(uri)
  end
end

playlist_default = audio_to_stereo(mksafe(input.http(max=10., "http://stream.domain.com")))

# Standard Playlists
radio = random(weights=[3], [playlist_default])

dynamic = audio_to_stereo(request.dynamic(id="radio_next_song", timeout=20., azuracast_next_song))
dynamic = cue_cut(id="radio_cue_cut", dynamic)

error_song = sequence([blank(duration=5.), single("/usr/local/share/icecast/web/error.mp3")])
requests = audio_to_stereo(request.queue(id="radio_requests"))
radio = fallback(id="radio_autodj_fallback", track_sensitive = true, [requests, dynamic, radio, error_song])

# Handle Jingle Mode
def handle_jingle_mode(m) =
  if (m["jingle_mode"] == "true") then
    log("Jingle mode; stripping metadata...")
    []
  else
    m
  end
end
radio = map_metadata(handle_jingle_mode,update=false,strip=true,insert_missing=false,radio)

# Allow for Telnet-driven insertion of custom metadata.
radio = server.insert_metadata(id="custom_metadata", radio)

# Apply amplification metadata (if supplied)
radio = amplify(1., radio)

# Send metadata changes back to AzuraCast
def metadata_updated(m) =
  if (m["song_id"] != "") then
    ret = list.hd(get_process_lines("curl -s --request POST --url http://web/api/internal/8/feedback --form song="^quote(m["song_id"])^" --form media="^quote(m["media_id"])^" --form playlist="^quote(m["playlist_id"])^" --form api_auth="^quote("TEST")^""), default="")
    log("AzuraCast Feedback Response: #{ret}")
  end
end

radio = on_metadata(metadata_updated,radio)

# Local Broadcasts
output.icecast(%mp3(samplerate=44100, stereo=true, bitrate=128, id3v2=true), id="radio_local_1", host = "127.0.0.1", port = 8040, password = "test", mount = "/radio.mp3", name = "Radio", description = "Radio", genre = "Test", url = "https://domain.com", public = false, encoding = "UTF-8", radio)

# Remote Relays`

**Comment by bayubad** [comment] 2019-05-27 18:11
```
# WARNING! This file is automatically generated by AzuraCast.
# Do not update it directly!


set("init.daemon", false)
set("init.daemon.pidfile.path","/var/azuracast/stations/radio/config/liquidsoap.pid")
set("log.stdout", true)
set("log.file", false)
set("server.telnet",true)
set("server.telnet.bind_addr","0.0.0.0")
set("server.telnet.port", 8044)
set("harbor.bind_addrs",["0.0.0.0"])

set("tag.encodings",["UTF-8","ISO-8859-1"])
set("encoder.encoder.export",["artist","title","album","song"])

setenv("TZ", "Europe")

# AutoDJ Next Song Script
def azuracast_next_song() =
  uri = list.hd(get_process_lines("curl -s --request POST --url http://web/api/internal/8/nextsong --form api_auth="^quote("TEST")^""), default="")
  log("AzuraCast Raw Response: #{uri}")
  
  if uri == "" or string.match(pattern="Error", uri) then
    log("AzuraCast Error: Delaying subsequent requests...")
    system("sleep 5")
    request.create("")
  else
    request.create(uri)
  end
end

playlist_default = audio_to_stereo(mksafe(input.http(max=10., "http://stream.domain.com")))

# Standard Playlists
radio = random(weights=[3], [playlist_default])

dynamic = audio_to_stereo(request.dynamic(id="radio_next_song", timeout=20., azuracast_next_song))
dynamic = cue_cut(id="radio_cue_cut", dynamic)

error_song = sequence([blank(duration=5.), single("/usr/local/share/icecast/web/error.mp3")])
requests = audio_to_stereo(request.queue(id="radio_requests"))
radio = fallback(id="radio_autodj_fallback", track_sensitive = true, [requests, dynamic, radio, error_song])

# Handle Jingle Mode
def handle_jingle_mode(m) =
  if (m["jingle_mode"] == "true") then
    log("Jingle mode; stripping metadata...")
    []
  else
    m
  end
end
radio = map_metadata(handle_jingle_mode,update=false,strip=true,insert_missing=false,radio)

# Allow for Telnet-driven insertion of custom metadata.
radio = server.insert_metadata(id="custom_metadata", radio)

# Apply amplification metadata (if supplied)
radio = amplify(1., radio)

# Send metadata changes back to AzuraCast
def metadata_updated(m) =
  if (m["song_id"] != "") then
    ret = list.hd(get_process_lines("curl -s --request POST --url http://web/api/internal/8/feedback --form song="^quote(m["song_id"])^" --form media="^quote(m["media_id"])^" --form playlist="^quote(m["playlist_id"])^" --form api_auth="^quote("TEST")^""), default="")
    log("AzuraCast Feedback Response: #{ret}")
  end
end

radio = on_metadata(metadata_updated,radio)

# Local Broadcasts
output.icecast(%mp3(samplerate=44100, stereo=true, bitrate=128, id3v2=true), id="radio_local_1", host = "127.0.0.1", port = 8040, password = "test", mount = "/radio.mp3", name = "Radio", description = "Radio", genre = "Test", url = "https://domain.com", public = false, encoding = "UTF-8", radio)

# Remote Relays
```

**Comment by bayubad** [comment] 2019-05-27 18:13
Streaming fill up my server without overwriting. 
@smimram

**Comment by toots** [comment] 2019-05-27 18:52
I don't see anything here that writes to the disk. I believe that this is an AzuraCast issue so I'm reassigning it to them. cc/ @SlvrEagle23, @Vaalyn

**Comment by toots** [comment] 2019-05-27 18:53
Looks like I can't reassign. I've pinged them. I suggest that you bring it over to them next. Thanks for reporting tho!

**Comment by SlvrEagle23** [comment] 2019-05-27 19:02
@toots We actually redirected the user in question over to you guys, because I believe the source of the problem is here:

```
playlist_default = audio_to_stereo(mksafe(input.http(max=10., "http://stream.domain.com")))
```

We've received some other reports that because this remote stream is then mixed into a radio signal that can include other playlists and live DJ connections, the contents of the stream are temporarily cached (perhaps via cURL?) somewhere local on the system, and this cache is overflowing and filling up server hard drives.

Since any stream going in through this process and out through `output.icecast` doesn't even touch AzuraCast at any part of that process, we suspected this was something in how Liquidsoap was handling the remote streaming process.

**Comment by toots** [comment] 2019-05-27 19:10
Ok I see. I don't think that there is anything hitting the hard drive in this operator but I'll reopen and will look at it again.

**Comment by SlvrEagle23** [comment] 2019-05-27 19:21
@toots Is it possible that `mksafe` is basically caching the incoming stream locally?

I'm not sure that there's any other way to integrate that kind of stream into a larger collection of playlists/live streams without `mksafe` though.

**Comment by toots** [comment] 2019-05-27 19:22
No, that shouldn't be the case.

**Comment by dhannyz** [comment] 2019-05-29 07:27
I don't see how this would be a liquidsoap issue. I's using input.http in a similar manner without a problem on upward of 5 servers and 25 instances.
I would look at anywhere that you are making external system calls

**Comment by bayubad** [comment] 2019-05-30 15:15
> I don't see how this would be a liquidsoap issue. I'm using input.http in a similar manner without a problem on upward of 5 servers and 25 instances.
> I would look at anywhere that you are making external system calls

Could share your Liquidsoap config file?

**Comment by toots** [comment] 2019-05-31 07:41
I definitely agree with @dhannyz. We're trying to cleanup open issues in preparation for the coming `beta` cycle so I'll close this one for now. Feel free to continue the discussion and/or reopen if more evidence arise.

**Closed by toots** 2019-05-31 07:41 UTC
