### ISSUE TITLE
List typing with methods

### ISSUE THREAD

**Issue by toots** [savonet/liquidsoap#1390] opened 2020-10-23 14:37 UTC
The following currently does not pass the type checker:
```ruby
def f(l) =
  def add_condition(s) =
    s.skip()
    ({true}, s)
  end

  s = switch(l = list.map(add_condition,l))

  list.add(s, l)
end
```

Error:
![Screen Shot 2020-10-23 at 3 44 01 PM](https://user-images.githubusercontent.com/871060/97052417-96649400-1546-11eb-9d74-f3d29428bf55.png)

To reproduce:
* Checkout the `source-methods` branch
* Run the script as: `./liquidsoap  ../libs/error.liq ../libs/list.liq /tmp/test.liq`

**Comment by smimram** [comment] 2020-10-29 08:32
I don't have time to properly test your example right now, but let me comment on what I understand:
- the source `s` has a method `id`
- the elements of the list `l` don't have the method `id`
- the type of `list.add` is `('a, ['a]) -> 'a`
therefore typing fails.

A simpler testcase to reproduce:
```
s = 3
let s.id = "hello"
l = [2]
xxx = list.add(s, l)
```

Is it really what is going on in your example? If so can this be fixed by adding `id` to the source? Otherwise, we could drop the `id` method when typing, but this is not going to be easy to implement since this is non-local... (let me think about this)

**Comment by toots** [comment] 2020-10-29 13:16
It's a type inference, the sources do have `id` method but since it's not called in the code the type inference doesn't add it to the computed type for the function.

**Comment by smimram** [comment] 2020-10-30 15:52
NB: with an explicit cast it works:
```
s = 3
let s.id = "hello"
l = [2]
xxx = list.add((s:int), l)
```

**Comment by toots** [comment] 2020-10-30 19:17
The plot thickens!
```
# l = [];;
l : ['a] = []
# list.add(s, l);;
- : [int.{id : string}] = [3.{id = "hello"}]
```

**Comment by toots** [comment] 2020-10-30 20:13
```
# x = 1;;
at line 1, char 4 (1): assigned type var ?404
at line 1, char 0-5 (()): assigned type var ?405
at line 1, char 0-5 (<?>): assigned type var ?406
int <: ?404
int <: ?407
unit <: ?405
unit <: ?406
Added toplevel x : int
x : int = 1
# let x.foo = "bla";;
at line 2, char 16 ("bla"): assigned type var ?408
at line 2, char 0-17 (()): assigned type var ?409
at line 2, char 0-17 (<?>): assigned type var ?410
string <: ?408
string <: ?411
unit <: ?409
unit <: ?410
Added toplevel x.foo : string
x.foo : string = "bla"
# [x];;
at line 3, char 1 (x): assigned type var ?412
at line 3, char 0-3 ([x]): assigned type var ?413
int.{foo : string} <: ?412
Instantiate x[-1] : int.{foo : string} becomes int.{foo : string}
int <: ?414
int.{foo : string} <: int
int <: int
[int] <: ?413
- : [int] = [1.{foo="bla"}]
```

**Closed** 2020-11-06 00:45 UTC
Labels: bug
