### ISSUE TITLE
segmentation Fault inmediately after launch

### ISSUE THREAD

**Issue by ogomez92** [savonet/liquidsoap#561] opened 2018-06-09 15:30 UTC
Hello all,
I am getting a really strange error over here.
This thing worked fine forever, but now after transferring files to this new server it stopped working.
It did work once on this same server before transferring the rest of the files so I have no idea what's going on.
Basically I launch a script and I get segmentation fault, nothing more, no log is even created, no root security exit, nothing.
It is very strange.
And here is my radio.liq file.

```
set("log.file.path","/home/radio/<script>.log")
set("server.telnet",false)
set("log.stdout",true)
def crossfade(~start_next,~fade_in,~fade_out,s)
  s = fade.in(duration=fade_in,s)
  s = fade.out(duration=fade_out,s)
  fader = fun (a,b) -> add(normalize=false,[b,a])
  cross(duration=start_next,fader,s)
end
radio=mksafe(fallback([request.queue(id="q"),
eat_blank(playlist("/home/radio/songs"))]))
recradio=mksafe(fallback([request.queue(id="q"),
playlist("/var/www/oriolgomez.com/web/beatpacks")]))
radio=smooth_add(delay=0.5,p=0.2,normal=radio, special=switch([({0m0s},single('/home/radio/songs/horas/'^list.hd(get_process_lines('date +"%I"'))^".mp3"))]))
full =
  fallback(track_sensitive=false,[input.http("http://radiolavila.com:8000/live.mp3"),
radio])

           output.icecast(%mp3.cbr(bitrate=160),
id="ice",
             host="localhost",port=8000,password="password",
             mount="stream.mp3",full)
           output.icecast(%mp3.cbr(bitrate=192),
id="rec",
             host="localhost",port=8000,password="password",
             mount="beats.mp3",recradio)
 ```

**Comment by 5chdn** [comment] 2018-06-12 20:25
Duplicate of #526 - mp3 does not work anymore.

**Comment by toots** [comment] 2018-07-01 15:08
Thanks for the reference @5chdn. I want to focus on `1.3.4` so I'm gonna close this. @ogomez92 would you mind re-opening or submitting a new one if that still occurs with `1.3.3`? Thks!

**Closed by toots** 2018-07-01 15:08 UTC
