### ISSUE TITLE
crossfade duration not updated via API / Azuracast

### ISSUE THREAD

**Issue by davidkamp** [savonet/liquidsoap#1152] opened 2020-04-12 12:08 UTC
Hi,
I posted an issue with incorrect crossfade durations (impossible to set any duration) on the Azuracast github. They confirmed the issue exists, but their code is apparently 100% following your API  so it might be an upstream issue, something within the liquidsoap API causing this? 

Here is the thread: https://github.com/AzuraCast/AzuraCast/issues/2632

Could you look into this?

Thanks so much,
David Kamp.

**Comment by toots** [comment] 2020-04-12 16:14
Hi! Thanks for reporting. Could you add a description of the script that is being executed? Are you trying to crossfade on a live source like `input.harbor`?

**Comment by davidkamp** [comment] 2020-04-13 11:45
Hi toots, I am just user but I mentioned in the other thread over at Azuracast (linked above) that you asked this. I am not sure what the most efficient way to solve this is for you and the azuaracast devs?

Thanks again.

**Comment by davidkamp** [comment] 2020-04-13 11:50
In regard to what I am personally doing: I have a simple playlist with a few audiofiles, created within azuracast. For that playlist there is a setting of "crossfade duration" within azuracast. Entering a value (e.g. 20 seconds) there does nothing, but the azuracast devs say it should in theory. I am doing nothing else. I am afraid that is all I can tell you from a user perspective.

**Comment by Vaalyn** [comment] 2020-04-15 13:01
@toots Here is the liquidsoap.liq that we generate when live streaming is enabled and with crossfading set to 20 seconds on our demo installation at https://demo.azuracast.com

The crossfade is applied before adding the `input.harbor` for live sources so that shouldn't influence the crossfading.

I've tested what it sounds like on the demo installation with the crossfade set to 20 seconds and it sounds like I expected it to sound. When a song is nearing its end you will start hearing the next song becoming louder and the current song becoming quieter.

@davidkamp would you mind also posting the liquidsoap.liq that is generated for your installation?
Remember to redact all `password` and `api_auth` values from that.

```
set("init.daemon", false)
set("init.daemon.pidfile.path","/var/azuracast/stations/azuratest_radio/config/liquidsoap.pid")
set("log.stdout", true)
set("log.file", false)
set("server.telnet",true)
set("server.telnet.bind_addr","0.0.0.0")
set("server.telnet.port", 8004)
set("harbor.bind_addrs",["0.0.0.0"])

set("tag.encodings",["UTF-8","ISO-8859-1"])
set("encoder.encoder.export",["artist","title","album","song"])

setenv("TZ", "UTC")


playlist_default = playlist(id="playlist_default",mode="randomize",reload_mode="watch",conservative=true,default_duration=10.,length=20.,"/var/azuracast/stations/azuratest_radio/playlists/playlist_default.m3u")
playlist_default = audio_to_stereo(id="stereo_playlist_default", playlist_default)
playlist_default = cue_cut(id="cue_playlist_default", playlist_default)

# Standard Playlists
radio = random(id="azuratest_radio_standard_playlists", weights=[3], [playlist_default])

# AutoDJ Next Song Script
def azuracast_next_song() =
    uri = list.hd(get_process_lines("curl -s --request POST --url http://web/api/internal/1/nextsong --form api_auth="^string.quote("xxx")^""), default="")
    log("AzuraCast Raw Response: #{uri}")
    
    if uri == "" or string.match(pattern="Error", uri) then
        log("AzuraCast Error: Delaying subsequent requests...")
        system("sleep 2")
        request.create("")
    else
        request.create(uri)
    end
end

dynamic = request.dynamic(id="azuratest_radio_next_song", timeout=20., azuracast_next_song)
dynamic = audio_to_stereo(id="azuratest_radio_stereo_next_song", dynamic)
dynamic = cue_cut(id="azuratest_radio_cue_next_song", dynamic)
radio = fallback(id="azuratest_radio_autodj_fallback", track_sensitive = true, [dynamic, radio])

requests = request.queue(id="azuratest_radio_requests")
requests = audio_to_stereo(id="azuratest_radio_stereo_requests", requests)
requests = cue_cut(id="azuratest_radio_cue_requests", requests)
radio = fallback(id="azuratest_radio_requests_fallback", track_sensitive = true, [requests, radio])

add_skip_command(radio)

radio = fallback(id="azuratest_radio_safe_fallback", track_sensitive = false, [radio, single(id="error_jingle", "/usr/local/share/icecast/web/error.mp3")])

radio = crossfade(smart=false, duration=30.,fade_out=20.,fade_in=20.,radio)

# DJ Authentication
live_enabled = ref false
last_authenticated_dj = ref ""
live_dj = ref ""

def dj_auth(auth_user,auth_pw) =
    user = ref ""
    password = ref ""
  
    if (auth_user == "source" or auth_user == "") and (string.match(pattern="(:|,)+", auth_pw)) then
        auth_string = string.split(separator="(:|,)", auth_pw)
        
        user := list.nth(default="", auth_string, 0)
        password := list.nth(default="", auth_string, 2)
    else
        user := auth_user
        password := auth_pw
    end
    
    log("Authenticating DJ: #{!user}")
    
    ret = list.hd(get_process_lines("curl -s --request POST --url http://web/api/internal/1/auth --form dj-user="^string.quote(!user)^" --form dj-password="^string.quote(!password)^" --form api_auth="^string.quote("xxx")^""), default="")
    log("AzuraCast DJ Auth Response: #{ret}")
    
    authed = bool_of_string(ret)
    if (authed) then
        last_authenticated_dj := !user
    end
    
    authed
end

def live_connected(header) =
    dj = !last_authenticated_dj
    log("DJ Source connected! Last authenticated DJ: #{dj} - #{header}")
    
    live_enabled := true
    live_dj := dj
    
    ret = list.hd(get_process_lines("curl -s --request POST --url http://web/api/internal/1/djon --form dj-user="^string.quote(dj)^" --form api_auth="^string.quote("xxx")^""), default="")
    log("AzuraCast Live Connected Response: #{ret}")
end

def live_disconnected() = 
    dj = !live_dj
    
    log("DJ Source disconnected! Current live DJ: #{dj}")
    
    ret = list.hd(get_process_lines("curl -s --request POST --url http://web/api/internal/1/djoff --form dj-user="^string.quote(dj)^" --form api_auth="^string.quote("xxx")^""), default="")
    log("AzuraCast Live Disconnected Response: #{ret}")
    
    live_enabled := false
    last_authenticated_dj := ""
    live_dj := ""
end 

# A Pre-DJ source of radio that can be broadcast if needed
radio_without_live = radio
ignore(radio_without_live)

# Live Broadcasting
live = audio_to_stereo(input.harbor("/", id = "azuratest_radio_input_streamer", port = 8005, auth = dj_auth, icy = true, icy_metadata_charset = "UTF-8", metadata_charset = "UTF-8", on_connect = live_connected, on_disconnect = live_disconnected, buffer = 5., max = 10.))
ignore(output.dummy(live, fallible=true))

radio = fallback(id="azuratest_radio_live_fallback", track_sensitive=false, [live, radio])

# Allow for Telnet-driven insertion of custom metadata.
radio = server.insert_metadata(id="custom_metadata", radio)

# Apply amplification metadata (if supplied)
radio = amplify(override="liq_amplify", 1., radio)

# Send metadata changes back to AzuraCast
def metadata_updated(m) =
    if (m["song_id"] != "") then
        ret = list.hd(get_process_lines("curl -s --request POST --url http://web/api/internal/1/feedback --form song="^string.quote(m["song_id"])^" --form media="^string.quote(m["media_id"])^" --form playlist="^string.quote(m["playlist_id"])^" --form api_auth="^string.quote("xxx")^""), default="")
        log("AzuraCast Feedback Response: #{ret}")
    end
end

radio = on_metadata(metadata_updated,radio)

# Local Broadcasts
output.icecast(%mp3(samplerate=44100, stereo=true, bitrate=128, id3v2=true), id="azuratest_radio_local_1", host = "127.0.0.1", port = 8000, password = "xxx", mount = "/test", name = "AzuraTest Radio", description = "A test radio station.", genre = "", public = false, encoding = "UTF-8", radio)

# Remote Relays
```

**Comment by davidkamp** [comment] 2020-04-15 13:20
Hi,
First to clarify: It is crossfading in my installation too, but with the crossfade duration as set in the field. 
When I set it to 30s I expect the current song to start fading out 30s before its end, while at the same moment the next song starts playing and fades in for the next 30s while the previous one keeps fading out. right?

`

set("init.daemon", false)
set("init.daemon.pidfile.path","/var/azuracast/stations/earth/config/liquidsoap.pid")
set("log.stdout", true)
set("log.file", false)
set("server.telnet",true)
set("server.telnet.bind_addr","0.0.0.0")
set("server.telnet.port", 8004)
set("harbor.bind_addrs",["0.0.0.0"])

set("tag.encodings",["UTF-8","ISO-8859-1"])
set("encoder.encoder.export",["artist","title","album","song"])

setenv("TZ", "UTC")
playlist_earth_single = playlist(id="playlist_earth_single",mode="random",reload_mode="watch",conservative=true,default_duration=10.,length=20.,"/var/azuracast/stations/earth/playlists/playlist_earth_single.m3u")
playlist_earth_single = audio_to_stereo(id="stereo_playlist_earth_single", playlist_earth_single)
playlist_earth_single = cue_cut(id="cue_playlist_earth_single", playlist_earth_single)

playlist_earth___random = playlist(id="playlist_earth___random",mode="randomize",reload_mode="watch",conservative=true,default_duration=10.,length=20.,"/var/azuracast/stations/earth/playlists/playlist_earth_-_random.m3u")
playlist_earth___random = audio_to_stereo(id="stereo_playlist_earth___random", playlist_earth___random)
playlist_earth___random = cue_cut(id="cue_playlist_earth___random", playlist_earth___random)

# Standard Playlists
radio = random(id="earth_standard_playlists", weights=[3, 3], [playlist_earth_single, playlist_earth___random])

# AutoDJ Next Song Script
def azuracast_next_song() =
    uri = list.hd(get_process_lines("curl -s --request POST --url http://web/api/internal/1/nextsong --form api_auth="^string.quote("fxxxxxxxxxxx")^""), default="")
    log("AzuraCast Raw Response: #{uri}")
    
    if uri == "" or string.match(pattern="Error", uri) then
        log("AzuraCast Error: Delaying subsequent requests...")
        system("sleep 2")
        request.create("")
    else
        request.create(uri)
    end
end

dynamic = request.dynamic(id="earth_next_song", timeout=20., azuracast_next_song)
dynamic = audio_to_stereo(id="earth_stereo_next_song", dynamic)
dynamic = cue_cut(id="earth_cue_next_song", dynamic)
radio = fallback(id="earth_autodj_fallback", track_sensitive = true, [dynamic, radio])

requests = request.queue(id="earth_requests")
requests = audio_to_stereo(id="earth_stereo_requests", requests)
requests = cue_cut(id="earth_cue_requests", requests)
radio = fallback(id="earth_requests_fallback", track_sensitive = true, [requests, radio])

add_skip_command(radio)

radio = fallback(id="earth_safe_fallback", track_sensitive = false, [radio, single(id="error_jingle", "/usr/local/share/icecast/web/error.mp3")])
radio = crossfade(smart=true, duration=45.,fade_out=30.,fade_in=30.,radio)

# Allow for Telnet-driven insertion of custom metadata.
radio = server.insert_metadata(id="custom_metadata", radio)

# Apply amplification metadata (if supplied)
radio = amplify(override="liq_amplify", 1., radio)
# Send metadata changes back to AzuraCast
def metadata_updated(m) =
    if (m["song_id"] != "") then
        ret = list.hd(get_process_lines("curl -s --request POST --url http://web/api/internal/1/feedback --form song="^string.quote(m["song_id"])^" --form media="^string.quote(m["media_id"])^" --form playlist="^string.quote(m["playlist_id"])^" --form api_auth="^string.quote("faaca580f4d402524abb1b93e206eb9b911f37f12f7e74844a287313a9757f87cb93c88e0584dc05c3e540d6b4f8aa17e56f")^""), default="")
        log("AzuraCast Feedback Response: #{ret}")
    end
end

radio = on_metadata(metadata_updated,radio)

# Local Broadcasts
output.icecast(%mp3(samplerate=44100, stereo=true, bitrate=192, id3v2=true), id="earth_local_1", host = "127.0.0.1", port = 8000, password = "QLm9hC2y", mount = "/radio.mp3", name = "EARTH", description = "", genre = "", public = false, encoding = "UTF-8", radio)

# Remote Relays

Powered by AzuraCast • v0.9.9, #8e66034 (2020-04-02 21:22) • Docker • PHP 7.4
Like our software? Donate to support AzuraCast!
`

**Comment by Vaalyn** [comment] 2020-04-15 13:34
> When I set it to 30s I expect the current song to start fading out 30s before its end, while at the same moment the next song starts playing and fades in for the next 30s while the previous one keeps fading out. right?

Yep, when I set the crossfade to 20s that's what happened in the demo installation.

When looking at your liquidsoap.liq one difference that stands out to me is that you are using the `smart` crossfade and I tested with the `normal` one. This might be the source of the issue. Would you mind switching that to `normal` to test if my assumption is correct?

**Comment by davidkamp** [comment] 2020-04-15 13:41
Thanks, but no difference. I tried all possible combinations of crossfade modes before posting my initial report.

**Comment by davidkamp** [comment] 2020-04-17 14:51
Just bumping this again -  any other ideas what is going on here @Vaalyn @toots ?
Would love to get this sorted since my radio is live and kind of depending on long fades....

**Comment by toots** [comment] 2020-04-27 00:50
Hi there.

I'd like to get this fixed for `1.4.2`. Do you have a ways to test this version? Here's a simple method via `opam`:
```
git clone --recursive https://github.com/savonet/liquidsoap.git
cd liquidsoap && git checkout 1.4.2
opam install -y .
```
It is possible that the bug is already fixed there..

Next, I'll need some logs showing what's going on around the issue with at least level 4 or if possible 5: `set("log.level",5)`

Finally, the most efficient way for me to deal with it is to be able to reproduce locally. A small script than can reproduce the issue and, if needed, the files that cause it, possibly sent via email (toots@rastageeks.org)

Let me know & let's fix this!

**Comment by davidkamp** [comment] 2020-04-27 18:03
Hi @toots 
Great, do you mean I should try it in my digital ocean install?
I can probably try it through console.

**Comment by toots** [comment] 2020-04-27 21:59
If you can. At the very least, some logs extracts would be great to start investigating..

**Comment by davidkamp** [comment] 2020-04-27 22:22
Thanks, when trying your commands in my console I get what you see in the attached screenshot.
Any ideas why? (No expert on this stuff, sorry)

![Screenshot 2020-04-28 at 00 20 25](https://user-images.githubusercontent.com/7592127/80426547-3918be80-88e6-11ea-9cbc-d8f0e1a718b7.jpg)

**Comment by toots** [comment] 2020-04-28 14:01
No, I'm not sure what's going on, I would need more background regarding your install. Could we start with some logs then? Run with `set("log.level",5)` and send me some logs printed during a failed crossfade transition..

**Comment by davidkamp** [comment] 2020-04-28 15:44
Hi @toots 
Sorry, I am not sur ehow to do that. I am using a docker install and only use the GUI normally so no ideas where to set this...

Under administration / system maintenance / system logs it says:

"Because you are running Docker, some system logs can only be accessed from a shell session on the host computer. You can run docker-compose logs -f (nginx|web|stations|...) to access container logs from the terminal.

But if you fixed the issue (it existed on your end and no longer exists now) why not just update?

I'll also need to check how I can actually update my install, not sure how that works with docker.

**Comment by Vaalyn** [comment] 2020-04-28 16:15
@davidkamp You can add the `set("log.level",5)` via the `Utilities` -> `Edit Liquidsoap Configuration` page like this: 
![image](https://user-images.githubusercontent.com/13745863/80510984-c8bc7c80-897b-11ea-906a-1d94551deb8c.png)

You'll need to `Restart Broadcasting` after saving the configuration in order for it to be applied.

The log that @toots want's to see is the `Liquidsoap Log` on the `Utilities` -> `Log Viewer` page.

**Comment by davidkamp** [comment] 2020-04-28 20:27
Unfortunately all I see under "liquidsoap log" is 
"error: Log file not found!"

**Comment by davidkamp** [comment] 2020-04-29 13:33
Hi @toots @Vaalyn So regardless of my issue with the log files, once @toots updated the release version with his fix,   how can I update my azuracast installation?
@toots when will the update be live?
Thanks for all your help.

**Comment by Vaalyn** [comment] 2020-05-02 17:01
@davidkamp Regarding the updating you'll just have to run the update commands when we released a new version:
```
cd /var/azuracast
./docker.sh update-self
./docker.sh update
```

Could you check for the logs manually via SSH / console?

Here are the commands you'll need:

Go to the AzuraCast directory via `cd /var/azuracast` and run the command to enter the bash shell: `./docker.sh bash`.

When inside the bash shell of the container you go to the config directory of your station via `cd /var/azuracast/stations/your_station_name/config` (don't forget to replace the `your_station_name` with the one your station uses. Check the `Advanced Base Station Directory` field of your station profile under the `Administration` tab).

Now check what files are available inside this directory via `ls -la`. There should be a file with the name `liquidsoap.log`. To view its content use this command: `cat liquidsoap.log`.

**Comment by toots** [comment] 2020-05-02 17:26
`1.4.2` is coming up today or tomorrow at the latest! Preparing the windows build as I write this..

**Comment by davidkamp** [comment] 2020-05-02 17:29
> @davidkamp Regarding the updating you'll just have to run the update commands when we released a new version:
> 
> ```
> cd /var/azuracast
> ./docker.sh update-self
> ./docker.sh update
> ```
> 
> Could you check for the logs manually via SSH / console?
> 
> Here are the commands you'll need:
> 
> Go to the AzuraCast directory via `cd /var/azuracast` and run the command to enter the bash shell: `./docker.sh bash`.
> 
> When inside the bash shell of the container you go to the config directory of your station via `cd /var/azuracast/stations/your_station_name/config` (don't forget to replace the `your_station_name` with the one your station uses. Check the `Advanced Base Station Directory` field of your station profile under the `Administration` tab).
> 
> Now check what files are available inside this directory via `ls -la`. There should be a file with the name `liquidsoap.log`. To view its content use this command: `cat liquidsoap.log`.

Thanks but unfortunately there are log files in that folder. So the "error: log file not found!" in the gui is true.

**Comment by davidkamp** [comment] 2020-05-02 17:30
> `1.4.2` is coming up today or tomorrow at the latest! Preparing the windows build as I write this..

Perfect, So in a few days I can run:
cd /var/azuracast
./docker.sh update-self
./docker.sh update

Right?

**Comment by Vaalyn** [comment] 2020-05-02 17:59
> Thanks but unfortunately there are no log files in that folder. So the "error: log file not found!" in the gui is true.

@davidkamp that's rather strange, there should be logs from liquidsoap and icecast in that directory. Is it completely empty? Would you mind posting a screenshot of the output from the `ls -la` command?

> Perfect, So in a few days I can run:
> cd /var/azuracast
> ./docker.sh update-self
> ./docker.sh update
>
> Right?

Yes, as soon as we release the update on the AzuraCast side which might not be immediately when 1.4.2 is out.

**Comment by davidkamp** [comment] 2020-05-02 18:02
Sure here you go:
![Screenshot 2020-05-02 at 20 01 10](https://user-images.githubusercontent.com/7592127/80872055-e5c0ba80-8caf-11ea-95c4-69b781c7940a.jpg)
![Screenshot 2020-05-02 at 20 00 57](https://user-images.githubusercontent.com/7592127/80872057-e6f1e780-8caf-11ea-9368-eddd3d35f85d.jpg)

**Comment by Vaalyn** [comment] 2020-05-02 18:20
That's really weird...
Can you see any errors in the `AzuraCast Application Log` under the `System Logs` in the Administration?
Where those logs always missing or did they stop working after some time?
Is there anything customized about your installation?
When did you last update you installation and which version are you currently running?
(Trying to find out why those logs are gone. They should not be missing and diagnosing other issues without them is very hard or impossible.)

**Comment by davidkamp** [comment] 2020-05-02 18:28
> That's really weird...
> Can you see any errors in the `AzuraCast Application Log` under the `System Logs` in the Administration?

yes - Azuracast apllication logs are there.

> Where those logs always missing or did they stop working after some time?
Never looked at them, no idea.

> Is there anything customized about your installation?

no.

> When did you last update you installation and which version are you currently running?

I only installed the docker container as available on digitalocean roughly one month ago. no updates.
Then I tried the commands listed by @toots above 5 days ago. (that partially failed).

Currently: running as listed in the azuracast gui:
AzuraCast • v0.9.9, #8e66034 (2020-04-02 21:22) • Docker • PHP 7.4

> (Trying to find out why those logs are gone. They should not be missing and diagnosing other issues without them is very hard or impossible.)

**Comment by davidkamp** [comment] 2020-05-09 12:30
Just checking in on this @Vaalyn @toots @SlvrEagle23 @dbeiner. Is there an update yet or what is the ETA?
Thanks a lot,
David.

**Comment by SlvrEagle23** [comment] 2020-05-10 02:20
@davidkamp AzuraCast 0.10.2 has been released which includes Liquidsoap 1.4.2. You can update any installation type to take advantage of the latest updates.

**Comment by davidkamp** [comment] 2020-05-10 08:56
@SlvrEagle23 Perfect- thanks so much. Do you happen to know with which commandline command I would update my docker installation without loosing my stations etc?

**Comment by davidkamp** [comment] 2020-05-10 09:11
Now liquidsoap does not work at all anymore.

**Comment by davidkamp** [comment] 2020-05-10 09:22
I updated, now no Broadcast works....
 @Vaalyn @toots @SlvrEagle23 @dbeiner After the update Liquidsoap in my docker following the Azuracast docker update directions here https://www.azuracast.com/administration/system/updating.html#docker-installations

My stations do not work at all. My two live stations are now offline, embedded players show an error message. This is really frustrating. What should I do?

I am attaching a few screenshots of the error messages I am getting when trying to start/restart Liquadsoap autoDJ.

![Screenshot 2020-05-10 at 11 16 23](https://user-images.githubusercontent.com/7592127/81495388-5703fd00-92b0-11ea-82e2-ad13d923acbc.jpg)
![Screenshot 2020-05-10 at 11 14 51](https://user-images.githubusercontent.com/7592127/81495389-579c9380-92b0-11ea-94c9-da7d794dce6e.jpg)
![Screenshot 2020-05-10 at 11 12 10](https://user-images.githubusercontent.com/7592127/81495391-59665700-92b0-11ea-8867-0689e8fdc13f.jpg)
![Screenshot 2020-05-10 at 11 11 59](https://user-images.githubusercontent.com/7592127/81495393-59feed80-92b0-11ea-98f2-f26de7c60907.jpg)

**Comment by davidkamp** [comment] 2020-05-10 09:25
If I click skip song manually I get:
![Screenshot 2020-05-10 at 11 24 15](https://user-images.githubusercontent.com/7592127/81495483-d85b8f80-92b0-11ea-90af-2f0999e00a62.jpg)

None of this was the case before running the update. (and doing nothing else except restarting the digitalocean droplet that I use to run the Azuracast docker.

**Comment by davidkamp** [comment] 2020-05-10 09:31
@Vaalyn @toots @SlvrEagle23 @dbeiner 
I just noticed that while when I am logged into my Azuracast install on docker it say in the footer of the azuracast frontend:
 AzuraCast • v0.10.2, #5102ce8 (2020-05-10 7:34) • Docker • PHP 7.4

But if I look the droplet within digitalocean it says:
in  Radio / 2 GB Memory / 50 GB Disk / LON1 - AzuraCast 0.9.8.1 on Ubuntu 18.04

![Screenshot 2020-05-10 at 11 28 37](https://user-images.githubusercontent.com/7592127/81495604-b6aed800-92b1-11ea-94d1-bba1d6688a21.jpg)

What does this mean?

**Comment by SlvrEagle23** [comment] 2020-05-10 21:38
@davidkamp Please don't use the Liquidsoap GitHub repository for issues with AzuraCast. You already have an existing issue pending with us in our repository; please follow that for updates and do not disturb our upstream project maintainers.

**Comment by davidkamp** [comment] 2020-05-11 08:59
@SlvrEagle23 Sorry, did not mean to disturb.

Here is what solved it for me: 
-Creating a new station with exactly the same files and  settings (station profile, playlist, autodj etc)  as the one I had before the update.
This newly created one works, the station created on the previous azuracast did not work no matter the settings.

Also it seems the crossfade duration now works as expected which is great!

**Comment by toots** [comment] 2020-07-23 04:24
Any update on this one? I'm gonna revisit it with the upcoming `1.4.3` release. There are a couple of similar issues already pending.

**Comment by toots** [comment] 2020-07-25 15:58
Hi!

We just fixed https://github.com/savonet/liquidsoap/issues/1074 that was a crossfade-related bug. Any chance you could try with the latest `v1.4.3-pre-release` branch? You can either use `opam pin` mechanism or one of the build that should appear shortly at: https://github.com/savonet/liquidsoap/releases/tag/v1.4.3-pre-release

Thanks!

**Comment by SlvrEagle23** [comment] 2020-07-25 21:01
AzuraCast has been updated to the latest 1.4.3 prerelease build; please update your AzuraCast installation and let us know if the issue is resolved.

**Comment by toots** [comment] 2020-07-26 00:27
Thanks for that @SlvrEagle23 ! When you get a chance, would you mind updating the image one more time? I let some changes in the commit fixing the issue that shouldn't have been in, just reverted them.. Sorry about that!

**Comment by SlvrEagle23** [comment] 2020-07-26 03:07
@toots Done, just rebuilt the image with the latest commit in the 1.4.3-prerelease branch.

**Comment by toots** [comment] 2020-08-02 14:22
Any update on this one?

**Comment by toots** [comment] 2020-08-14 05:25
Hi! I might close this issue if we don't hear back in a couple of days, presuming it closed through the recent work on crossfade. Let me know if that isn't the case!

**Comment by toots** [comment] 2020-08-29 14:58
I'm marking this one as closed, please re-open if needed.

**Closed by toots** 2020-08-29 14:58 UTC
Labels: bug
