### ISSUE TITLE
Interactive.harbor missing or moved ?

### ISSUE THREAD

**Issue by Russsgithub** [savonet/liquidsoap#2431] opened 2022-06-02 06:01 UTC
Using ```interactive.harbor()``` in a script receives this error after recent github main (2.1.0) updates

```
At test.liq, line 1, char 0-11:
interactive.harbor()

Error 4: Undefined variable interactive
```

**Version details**
 - OS: [e.g. Debian, OSX] - Ubuntu 20.04
 - Version [e.g. `1.3.4`] 2.1.0 (github 2/6/22)

Installed with Opam

**Comment by vitoyucepi** [comment] 2022-06-02 16:04
You are building from `main` branch, right?
In the 9d224741822e3762b02598e79b3f10601807cabc path to `libs` has changed. I think this is the cause of your issue.
Check if other functions are still available.

**Comment by toots** [comment] 2022-06-02 16:15
Yes. We just switched to `dune` for the building system and there still are some things to iron out. If you can give me some details on how you install and plan to use the binary I can give more guidance. Otherwise, I would suggest to stick to `rolling-release-v2.1.x` for the time being.

**Comment by toots** [comment] 2022-06-02 16:15
Ha I see you installed via `opam`. Yes, there's an issue with `dune` and the utility it provides to find specific files. We have raised it here: https://github.com/ocaml/dune/issues/5814

**Comment by toots** [comment] 2022-06-03 14:03
There's a more generic issue here: https://github.com/savonet/liquidsoap/issues/2433. Closing this one as a duplicate.

**Closed by toots** 2022-06-03 14:03 UTC
