### ISSUE TITLE
opam install problem on Debian testing

### ISSUE THREAD

**Issue by mustafejen** [savonet/liquidsoap#1095] opened 2020-02-15 22:10 UTC
I tried to post this on the mailing list but my yandex mail account was SPAM listed by sourceforge as usual. Hope it's OK to post here!

Hello!

I am trying to install 1.4.1 with opam.

The install gets stuck at :
```
# /usr/bin/install -c -d /usr/share/bash-completion/completions
# /usr/bin/install: cannot change permissions of
‘/usr/share/bash-completion/completions’: Read-only file system
# make: *** [Makefile:84: install-local] Error 1
```

I don't know how to remount the whole file system read-write. Maybe it's
something in the Debian /etc/bash.bashrc which doesn't look for the
completions in the right place.

Regards,

Per Gunnarsson

**Comment by toots** [comment] 2020-02-16 17:29
Hi,

We've had issues with this in the past: https://github.com/savonet/liquidsoap/issues/980 and I thought this was fixed but it looks like the fix broke debian stable install..

**Comment by toots** [comment] 2020-02-16 17:30
@mustafejen Could you send the full logs of `opam install -v liquidsoap`? Thks!

**Comment by mustafejen** [comment] 2020-02-16 18:16
[log.txt](https://github.com/savonet/liquidsoap/files/4210524/log.txt)

**Comment by smimram** [comment] 2020-02-23 22:33
I can confirm this problem, which means that the current opam is completely broken on at least all linux machines: HIGH PRIORITY!...

**Comment by smimram** [comment] 2020-02-23 22:35
The culprit is likely to be 238a4bd59619d8b86f3e2a5ec630075f1cb3cc34 (which overwrites 238a4bd59619d8b86f3e2a5ec630075f1cb3cc34).

**Comment by toots** [comment] 2020-03-01 03:52
`liquidsoap.1.4.1-1` has been accepted in the `opam` repository and should fix this issue. I'll close the ticket here once this hits their server.

**Comment by toots** [comment] 2020-03-01 16:06
Fixed now, thanks for reporting! http://opam.ocaml.org/packages/liquidsoap/liquidsoap.1.4.1-1/

**Comment by smimram** [comment] 2020-03-02 08:50
Looks like it does not:
```
#=== ERROR while installing liquidsoap.1.4.1-1 ================================#
# context     2.0.5 | linux/x86_64 | ocaml-base-compiler.4.08.0 | https://opam.ocaml.org#329ac381
# path        ~/.opam/4.08.0/.opam-switch/build/liquidsoap.1.4.1-1
# command     ~/.opam/opam-init/hooks/sandbox.sh install make install
# exit-code   2
# env-file    ~/.opam/log/liquidsoap-974314-d2d111.env
# output-file ~/.opam/log/liquidsoap-974314-d2d111.out
### output ###
# [...]
# /usr/bin/install -c scripts/extract-replaygain /home/smimram/.opam/4.08.0/lib/liquidsoap/share/liquidsoap/1.4.1/bin
# find libs | grep '\.liq$' | while read l; do \
#   /usr/bin/install -c -m 644 $l /home/smimram/.opam/4.08.0/lib/liquidsoap/share/liquidsoap/1.4.1/libs ; \
# done
# /usr/bin/install -c -d /home/smimram/.opam/4.08.0/lib/liquidsoap/etc/liquidsoap
# /usr/bin/install -c -m 644 examples/radio.liq /home/smimram/.opam/4.08.0/lib/liquidsoap/etc/liquidsoap/radio.liq.example
# /usr/bin/install -c -d /home/smimram/.opam/4.08.0/lib/liquidsoap/etc/logrotate.d
# /usr/bin/install -c -m 644 scripts/liquidsoap.logrotate /home/smimram/.opam/4.08.0/lib/liquidsoap/etc/logrotate.d/liquidsoap
# /usr/bin/install -c -d /usr/share/bash-completion/completions
# /usr/bin/install -c -m 644 scripts/bash-completion /usr/share/bash-completion/completions/liquidsoap
# /usr/bin/install: cannot create regular file '/usr/share/bash-completion/completions/liquidsoap': Read-only file system
# make: *** [Makefile:85: install-local] Error 1



<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
┌─ The following actions failed
│ ∗ install liquidsoap 1.4.1-1
└─ 
```

**Comment by toots** [comment] 2020-03-04 17:24
Wow.

**Comment by toots** [comment] 2020-03-08 01:27
I cannot reproduce on ubuntu `18.04`. Gonna test on debian testing next.

**Comment by toots** [comment] 2020-03-08 01:48
Confirmed with debian testing.. What a mess..

**Comment by toots** [comment] 2020-03-08 02:00
Ok, PR tested and confirmed to fix the issue. Just merged it, opam package update submitted here: https://github.com/ocaml/opam-repository/pull/15961 Will close here when it is accepted into opam.

**Comment by smimram** [comment] 2020-03-09 16:14
The patch has now been accepted in opam!
```
<><> liquidsoap.1.4.1-2 installed successfully ><><><><><><><><><><><><><><><><>
=> ✨ Congratulations on installing liquidsoap! ✨
```

**Closed by smimram** 2020-03-09 16:14 UTC
Labels: bug

**Comment by kmahelona** [comment] 2020-03-10 04:18
Huh... wow... it's crazy when you're working on something and it's just patched hours before. I had this issue in Ubuntu 19.10. I just did an `opam update` and I'm still seeing version 1.4.1-1 which fails to install. But the `apt remove bash-completion` trick worked for me. Thx.

**Comment by smimram** [comment] 2020-03-10 08:44
You should do `opam update` in order to have access to 1.4.1-2.
