### ISSUE TITLE
input.srt in caller mode increases CPU load

### ISSUE THREAD

**Issue by yan-sag** [savonet/liquidsoap#3573] opened 2023-11-28 13:23 UTC
**Describe the bug**
`srt.input` in caller mode tries to reconnect to the server (`output.srt` in listener mode) until the server is up (correct behavior).
When the server is down or there's a network issue, `srt.input` loops and increases slowly the CPU usage indefinitely.
That can cause 'must catchup' errors.

**To Reproduce**
```
emergency = mksafe(id="safe_pl", playlist('/home/primitive/musique'))

srt_input = input.srt(
    id="input_srt",
    content_type="application/ffmpeg;format=s16le,ch_layout=stereo,sample_rate=48000",
    clock_safe=false,
    mode="caller"
)

#srt_input = buffer(id="buffer_srt", buffer=.5, srt_input)    # not a buffer issue
#srt_input = blank.strip(max_blank=15., srt_input)     # doesnt work / not a blank.strip issue

radio = fallback(
    track_sensitive=false,
    [ srt_input, emergency ]
)

output.alsa(
    id="output_alsa",
    device='plughw:2,0',
    fallible=true,
    radio
)
```

**Expected behavior**
`srt.input` should trying to reconnect to host without CPU overload.

**Version details**
- Debian bookworm, Raspberry Pi OS (bookworm)
- Liquidsoap 2.2.3+dev

**Install method**
opam

**Comment by toots** [comment] 2023-11-28 13:41
Hi,

Would you mind trying again on `main` with commit b26aedf90b93b74907ca427d567572602e5192ae ? The fix for the previous issues had not been backported there yet and will most likely apply to this issue as well.

**Comment by yan-sag** [comment] 2023-11-28 14:52
Not sure if I do it correctly : I cloned the repo, checked-out on [`b26aedf`](https://github.com/savonet/liquidsoap/commit/b26aedf90b93b74907ca427d567572602e5192ae), opam-pinned liquidsoap and upgraded.

Still have the issue, it's running for one hour and the script is 50 %CPU (i3 @ 3GHz).
Not clear if that the server's status (up/down) is changing something on the caller side.

**Comment by toots** [comment] 2023-12-05 20:23
Hi, I believe that the issue is now fixed in `main` and `rolling-release-v2.2.x`. Please reopen if needed!

**Closed by toots** 2023-12-05 20:23 UTC

**Comment by yan-sag** [comment] 2023-12-07 13:41
Tried with `main`, I confirm the issue is fixed.
Thanks

**Comment by toots** [comment] 2023-12-07 18:56
`rolling-release-v2.2.x` yes. I would like `2.3.0` to come out as soon as possible but I cannot give a timeline at the moment.
