### ISSUE TITLE
inaudible beeps?

### ISSUE THREAD

**Issue by mooseh** [savonet/liquidsoap#559] opened 2018-06-06 21:16 UTC
Hi 
we are running an input harbor
and we are falling back to a playlist.

we are then passing back to our internal icecast
but we have noticed that the inaudible beeps we receive from the icecast feed somehow dont get pushed to the internal icecast from the harbor?

we tried pulling from an external icecast server and the beeps were there.
so this must be the harbor only

is there a way around this?

**Comment by toots** [comment] 2018-07-01 15:34
I'm not sure what the issue is here. Do you guys add inaudible beeps in the stream? Do you have some script and liquidsoap version to share?

**Comment by smimram** [comment] 2019-05-28 18:48
This report is quite old and lacks feedback. I'm closing, please reopen if the bug still applies.

**Closed by smimram** 2019-05-28 18:48 UTC
Labels: incomplete
