### ISSUE TITLE
duplicate last.fm submissions

### ISSUE THREAD

**Issue by oranjebloom** [savonet/liquidsoap#1241] opened 2020-06-10 03:02 UTC
Hi,
I am running liquidsoap 1.4.2 on debian 9 installed via opam.
Since the upgrade to version 1.4.2, I have noticed duplicate submissions for quite a number of tracks that play on my radio stream and which get scrobbled to last.fm. It appears to be happening every 10 tracks or so.

I've added a a screen shot of this happening. 
![Screen Shot 2020-06-10 at 12 58 24](https://user-images.githubusercontent.com/46059094/84222087-18b16600-ab1a-11ea-92e8-274d9e9d42b6.png)

There also appears to be an error message that appears in the log (also attached).
![Screen Shot 2020-06-10 at 12 59 38](https://user-images.githubusercontent.com/46059094/84222155-426a8d00-ab1a-11ea-9c18-291ad19cc633.png)

This is the code I am using for last.fm submissions in my script.
```

def lastfm.submit(~user,~password,~source="broadcast",~length=false,m) =
audioscrobbler.submit(user=user,password=password,
source=source,length=length,
host="post.audioscrobbler.com",port=80,m)
end

radio = on_metadata(lastfm.submit(user="*********",password="*********€€"), radio)
```

**Comment by toots** [comment] 2020-06-13 19:12
Ok thanks. There does not seem to be a retry mechanism in `audioscrobbler.submit` so I would suspect an issue with the source's metadata. Would you be able to hook up a function to print out the metadata? Something like:
```
s = on_metadata(print, s)
```
So we can see if the multiple submission comes from multiple metadata..

Also, some details about your script would help.

Thanks!

**Comment by oranjebloom** [comment] 2020-06-15 10:31
So I've attached the script I'm running ... Romain, you actually helped me to tidy up the code for this script about 8 months ago, so the script remains pretty much untouched since then. We were running version 1.3.7 back then. Where would you like me to add the `s = on_metadata(print, s)` in the script?

**Comment by oranjebloom** [comment] 2020-06-15 10:32
[ssr2.liq.txt](https://github.com/savonet/liquidsoap/files/4779639/ssr2.liq.txt)

**Comment by oranjebloom** [comment] 2020-06-18 11:58
Hi again, so I added `s = on_metadata(print, s)` to my script and have attached a small amount of the log. Please let me know if you need more detail and I'll set the logs to level 4, but I do see duplicate metadata in the logs attached.
[ssr2.log.txt](https://github.com/savonet/liquidsoap/files/4798325/ssr2.log.txt)

**Comment by toots** [comment] 2020-06-27 22:13
Hi. Thanks for that. It looks like we are indeed seeing duplicate metadata being passed. I think the next step would be to look at your script and see if we can reproduce the issue. If it's small enough it might easy, otherwise, we could try to prune it down while keeping the issue until it is small enough for me to run and reproduce locally. Hope that makes sense!

**Comment by toots** [comment] 2020-07-05 15:17
Hi! Any chance you could send us some details from your script? Would love to fix this in time for the `1.4.3` release!

**Comment by oranjebloom** [comment] 2020-07-24 12:36
Hi, sorry for the delay in getting back to you here. As you know, I added my script earlier in this thread, and have been trying to minimize it but when I do that, I find it hard to replicate the bug. Could you be a little more specific on what sections you'd like slimmed down?

**Comment by toots** [comment] 2020-07-25 17:45
Hi! Could you try to add `replay_metadata=false` to all your `switch`,`rotate` and `fallback`? I'm wondering if this could come from that mechanism, it would help a lot to know if switching it off makes the issue disappear..

**Comment by toots** [comment] 2020-07-31 01:38
I think I can reproduce!

**Comment by toots** [comment] 2020-07-31 01:53
```
set("log.level",4)

def trans(old, new) =
  source.skip(new)
  new
end

r = switch(id="switch",
    track_sensitive=false,
    transitions=[trans,trans],
    [({file.exists("/tmp/first")}, playlist("/path/to/pl1")),
     ({true}, playlist("/path/to/pl2"))])

def p(m) =
  log("meta: #{m}")
end

r = on_metadata(p,r)

output.ao(fallible=true,r)
```

You can toggle the two sources by creating/removing the `/tmp/first` file. Once you go back and forth you start seeing duplicate metadata.

Notes:
- `source.skip` seems to be required
- Both playlists have a single track in my tests.

**Comment by toots** [comment] 2020-07-31 04:06
Hi! Pretty sure that this is fixed in the latest `master` and `v1.4.3-pre-release`. Any chance you could test it to confirm?

**Closed** 2020-07-31 04:05 UTC
Labels: bug

**Comment by oranjebloom** [comment] 2020-07-31 06:16
Hi, Thanks for looking at this. Will test it this weekend. 

Cheers
Damian

**Comment by oranjebloom** [comment] 2020-07-31 07:29
My switch configuration is a little different to the one you used in your tests (see below). I'm assuming no changes are required... i can just test the exiting script as is?

```
def f(path) =
  fun () -> file.exists(path)
end

#TRANSITION & SCHEDULE#
def trans(old, new) =
    source.skip(new)
    sequence(merge=true,[
    fade.final(duration=10.,old),
    fade.initial(duration=0.,new)
  ])
end

sources = [
  #Monday#
  ({1w4h00-1w7h00},source2),
  
  #Default#
  ({true},source1)
]

transitions = list.map(fun (_) -> trans, sources)

radio = switch(
  track_sensitive=false,
  transition_length=10.,
  transitions=transitions,
  sources)
```

**Comment by toots** [comment] 2020-07-31 14:09
Yes, it should work with your configuration. My example is just minimized to make it easier to find the source of the issue.

**Comment by oranjebloom** [comment] 2020-08-02 12:31
So far so good. No submission duplicates with version 1.4.3. Will keep an eye on things for a bit longer though.

**Comment by toots** [comment] 2020-08-02 14:23
Awesome!
