### ISSUE TITLE
Delaying a Stream

### ISSUE THREAD

**Issue by RoxyBoxxy** [savonet/liquidsoap#2865] opened 2023-01-27 19:08 UTC
Hi i am trying to delay a stream by 8 hours how ever i am getting this error 

```
Error 5: this value has type
  float
but it should be a subtype of
  int (inferred at .\test.liq, line 14, char 29)
```

Bellow is my code 

```
log.stdout.set(true)
log.file.set(false)

# A HTTP input
input = input.http("https://22543.live.streamtheworld.com/VERONICA.mp3")

# Delay the stream by 8 hours 

delayed_stream = delay(input,8*60*60.0)

# An output to the local soundcard
output.ao(fallible=true,delayed_stream)

```

has anybody or know how i could fix this thanks

**Comment by vitoyucepi** [comment] 2023-01-27 20:29
Hi @RoxyBoxxy,
I think this is not an issue. It should be a discussion in *Q&A* instead.

Because of Liquidsoap's typing system, you can't perform math operations on different types.
So this could be solved by
1. Multiply as `int` and convert to `float`
   ```ruby
   delayed_stream = delay(input, float(8*60*60))
   ```
1. Defining a constant
   ```ruby
   SECONDS_IN_HOUR = 60 * 60
   stream_delay = 8 * SECONDS_IN_HOUR
   delayed_stream = delay(input, float(stream_delay))
   ```
1. Invent your own [date-fns](https://date-fns.org/docs/hoursToSeconds)
   ```ruby
   def hours_to_seconds(hours)
     hours * 60 * 60
   end
   stream_delay = hours_to_seconds(8)
   delayed_stream = delay(input, float(stream_delay))
   ```
1. Maybe you should use `float` instead of `int` everywhere
   ```ruby
   def hours_to_seconds(hours)
     float(hours) * 60. * 60.
   end
   stream_delay = hours_to_seconds(8)
   delayed_stream = delay(input, stream_delay)
   ```

**Comment by RoxyBoxxy** [comment] 2023-01-28 01:41
Hi thank you for the examples how ever i am now getting this error 

```
At line 9, char 8: the variable float used here has not been previously
  defined.
```

i am quite new to using a custom config with liquidsoap

thanks

**Comment by vitoyucepi** [comment] 2023-01-28 02:02
I've fixed the examples because the definition of function is `delay({float}, source())`.

> this error
> `At line 9, char 8: the variable float used here has not been previously defined.`

Could you please provide your liquidsoap version and the config you're using?

**Comment by RoxyBoxxy** [comment] 2023-01-28 02:12
This is my config 

```
log.stdout.set(true)
log.file.set(false)

# A HTTP input
input = input.http("https://22543.live.streamtheworld.com/VERONICA.mp3")

# Delay the stream by 8 hours 

def hours_to_seconds(hours)
  hours * 60 * 60
end
stream_delay = hours_to_seconds(8)
delayed_stream = delay(input, float(stream_delay))


# An output to the local soundcard
output.dummy(delayed_stream)
```

**Comment by vitoyucepi** [comment] 2023-01-28 02:21
OK, let's talk about the latest version.
I've tested this config locally, and it works well.

```ruby
log.stdout.set(true)
log.file.set(false)

# A blank input
input = blank()

def hours_to_seconds(hours)
  float(hours) * 60. * 60.
end

delayed_stream = delay(hours_to_seconds(8), input)

# A debug output
output.dummy(fallible=true, delayed_stream)

```

**Comment by RoxyBoxxy** [comment] 2023-01-28 02:23
Ohhh that makes sence now thank you

**Comment by rsp4jack** [comment] 2023-07-21 02:21
please close this issue if the problem is fixed @RoxyBoxxy

**Comment by toots** [comment] 2023-07-21 12:24
This should be fixed by the new `track.audio.defer` operator. See this link: https://www.liquidsoap.info/doc-dev/memory.html#audio-data-format

Usage:

```liquidsoap
s = ...

# If needed:
s = audio.encode.pcm_s16(s)

let {audio} = source.tracks(s)

# Delay audio
audio = track.audio.defer(delay=8.*60*.60., audio)

s = source({
  audio = audio,
  metadata = track.metadata(audio),
  track_marks = track.track_marks(audio)
})

# If needed:
s = audio.decode.pcm_s16(s)
```

**Closed by toots** 2023-07-21 12:24 UTC
Labels: usage
