### ISSUE TITLE
GStreamer-CRITICAL **: gst_poll_write_control: assertion 'set != NULL' failed

### ISSUE THREAD

**Issue by GBraga23** [savonet/liquidsoap#580] opened 2018-07-15 23:43 UTC
GStreamer-CRITICAL **: gst_poll_write_control: assertion 'set != NULL' failed

What is the problem?

**Comment by toots** [comment] 2018-07-17 11:53
Hi,

Could you share more details:
- Liquidsoap version and how you installed it
- Script extract
- Log extract

Thanks!

**Comment by autonarcosis** [comment] 2018-07-17 17:43
This error ties in with the previous report #579 and most likely #578.

The reported error above is related to too many files open, which is also TCP Error 24 in report #579.

I believe this is erroneously marked as 'can't reproduce' and should be marked as 'Insufficient Information'.

What version of Liquidsoap is being used.
And as Toots asked, script and log files.
What Operating System.
What CPU (exact model, not just i7).
How much RAM.
What is the CPU utilization prior to launching and during running of Liquidsoap.
What is the file system use prior to and during running of Liquidsoap.

The tie in with report #578 is that your example script shows you are attempting to use 720p video. It is my experience that the max usable frame size is 576p without using some sort of hardware acceleration for encoding or using an external encoder. Also to save you time, all source videos MUST BE THE SAME FRAME RATE or you will experience de-synchronized audio.

**Comment by toots** [comment] 2018-08-21 12:09
Hi,

We've been doing extensive work on gstreamer lately and it appears to work fine now. Please test with the latest code and gstreamer `1.14.2` or above and re-open if needed. Thanks!

**Closed by toots** 2018-08-21 12:09 UTC
Labels: incomplete
