### ISSUE TITLE
Cannot decode WMA files?

### ISSUE THREAD

**Issue by davehayes** [savonet/liquidsoap#483] opened 2017-09-23 00:25 UTC
Hello. I am trying to get a wma file to decode. Here's the script I am using:

```#!/home/dave/.opam/system/bin/liquidsoap --debug
  set("log.file.path","/home/dave/playlists/liquidstream.log")
  set("log.stdout", true)
  set("decoder.debug", true)
  myplay = playlist("/home/dave/playlists/allfmt.m3u", mode="normal")
  normplay = normalize(myplay)
  crossplay = smart_crossfade(normplay)
  output.icecast(
   %vorbis(channels=2, quality=0.3),
   id="MyStream",
   fallible=true,
   host="localhost",
   port=9500,
   mount="stream.ogg",
   icy_metadata="true",
   password="donthackme",
   crossplay)
```
I did a bit of digging and found that gstreamer appears to be the culprit:

```
  017/09/09 16:33:06 [decoder:4] Trying method "GSTREAMER" for 
"/home/dave/playlists/random.wma"...
  2017/09/09 16:33:06 [decoder.gstreamer:4] Invalid file extension for 
"/home/dave/playlists/random.wma"!
  2017/09/09 16:33:06 [decoder:3] Unable to decode 
"/home/dave/playlists/random.wma" as {audio=2;video=0;midi=0}!
```

So I tried `gst-play` and this works:

```
> gst-play-1.0 random.wma
  Press 'k' to see a list of keyboard shortcuts.
  Now playing /home/dave/playlists/random.wma
  Redistribute latency...
  0:00:02.0 / 0:04:46.8
```

How can I debug this further? Thanks in advance.

**Comment by davehayes** [comment] 2017-09-23 00:29
Perusing some related comments, this info may prevent a turnaround cycle in communication:

```
> ldd `which liquidsoap` | grep gstream
	libgstreamer-1.0.so.0 => /usr/local/lib/libgstreamer-1.0.so.0 (0x802c0c000)
> ldd `which gst-play-1.0` | grep gstream
	libgstreamer-1.0.so.0 => /usr/local/lib/libgstreamer-1.0.so.0 (0x8015fd000)
```

They are both using the same library. If there is any other info you need, please ask.

**Comment by toots** [comment] 2017-10-08 15:34
I can't reproduce on Debian/sid.. :-(

What version y'all using? I got:
```
liquidsoap: 1.3.2+scm@71fd37f
2017/10/08 10:33:26 [gstreamer.loader:3] Loaded GStreamer 1.12.3 0
```

**Comment by davehayes** [comment] 2017-10-09 18:31
I'm using 

```
2017/10/09 11:27:30 [main:3] Liquidsoap 1.3.2
2017/10/09 11:27:30 [main:3] Using: bytes=[distributed with OCaml 4.02 or above] pcre=7.2.3 dtools=0.3.3 duppy=0.6.1 duppy.syntax=0.6.1 cry=0.5.0 mm=0.3.0 xmlplaylist=0.1.4 ogg=0.5.1 vorbis=0.7.0 opus=0.1.2 speex=0.2.1 mad=0.4.5 flac=0.1.2 flac.ogg=0.1.2 dynlink=[distributed with Ocaml] lame=0.3.3 gstreamer=0.2.3 frei0r=0.1.1 fdkaac=0.2.1 theora=0.3.1 ffmpeg=0.1.2 samplerate=0.1.4 taglib=0.3.3 camomile=0.8.5 faad=0.3.3 ladspa=0.1.5 dssi=0.1.2 lo=0.1.1
2017/10/09 11:27:30 [gstreamer.loader:3] Loaded GStreamer 1.8.0 0
```

on FreeBSD 10.3. Seems your gstreamer is newer. 

I'm almost done with my horrible workaround where I'm getting liquidsoap to use vlc to decode the file. I really don't want to have to use this. ;)

**Comment by toots** [comment] 2017-10-10 14:07
huh `vlc`.. Why don't you use `ffmpeg` instead?

**Comment by davehayes** [comment] 2017-10-10 21:31
Can I? I've not used that from the command line. I'll look into it.

**Comment by toots** [comment] 2017-10-11 19:54
Ok can you try with the latest `gstreamer`? This this:

```
git clone --recursive https://github.com/savonet/ocaml-gstreamer.git
cd ocaml-gstreamer
opam pin add gstreamer .
```

That should recompile liquidsoap with the new gstreamer. Hopefully the issue is fixed in it.

**Comment by davehayes** [comment] 2017-10-11 20:19
That did not work for me. Here's a report on what happened. 

[liq2.txt](https://github.com/savonet/liquidsoap/files/1377050/liq2.txt)

**Comment by toots** [comment] 2017-10-11 20:21
Ok, thanks.

- Did the behavior change? It was crashing before right?
- Any chance you could send me that file at toots@rastageeks.org ?

**Comment by davehayes** [comment] 2017-10-11 20:22
The behavior did not change. Process uses 100% of the CPU and a 'kill -9' is required. 

I'll send that file to you shortly.

**Comment by toots** [comment] 2017-10-11 20:42
So that file you sent me works here.. Any chance you could update gstreamer to my version to see if that helps with the issue? I'm gonna try to install a FreeBSD in a virtual machine soon.

**Comment by davehayes** [comment] 2017-10-11 20:59
That is an extremely involved and somewhat slow process to do for me, sadly. I build FreeBSD packages myself for a number of users, and I have to pass a rigorous (if incomplete) set of tests that absolutely must pass before I make changes. 

Luckily I can see that [gstreamer 1.12](https://www.freshports.org/multimedia/gstreamer1) is available as a port. So I will look into it of course, but it will likely be faster for me to try to use ffmpeg as an external fallback decoder through your scripting language.

**Comment by toots** [comment] 2017-10-11 21:39
It seems to work on FreeBSD 32 bit with `gstreamer 1.12` here.

**Comment by davehayes** [comment] 2017-10-11 23:43
Wow. Seems gstreamer has 98 different ports. So I'll come back here and revisit this issue at a later date. Thank you very much for your time and effort.

**Comment by davehayes** [comment] 2017-10-19 02:34
I've experienced the exact same bug with gstreamer 1.12.

**Comment by toots** [comment] 2017-10-19 13:33
![Exterminate!](https://media.giphy.com/media/XHppLGyp0Mx2w/giphy.gif)

**Comment by toots** [comment] 2017-10-19 13:34
Thanks for trying. Any chance you'd have a backtrace of it? Not super important at this point, though but just in case.

**Comment by davehayes** [comment] 2017-10-19 18:45
It doesn't crash when it fails. It pegs the CPU to 100% (for that core) and sits there. I have to kill -9 the process.

**Comment by toots** [comment] 2018-07-02 12:47
Hi,

Still not many new ideas on this one tho I'll try to have another look at it shortly...

The image is from Dr Who :-)

**Comment by toots** [comment] 2018-08-21 12:12
Hi,

We've been doing extensive work on gstreamer lately and it appears to work fine now. Please test with the latest code and gstreamer `1.14.2` or above and re-open if needed. Thanks!

**Closed by toots** 2018-08-21 12:12 UTC
Labels: bug, can't reproduce
