### ISSUE TITLE
Audio stream becomes blank

### ISSUE THREAD

**Issue by Niall7459** [savonet/liquidsoap#572] opened 2018-07-06 14:31 UTC
After about half a day, my stream does not output music but continues to show loading songs in terminal. I need to restart the program to get the stream back

**Comment by toots** [comment] 2018-07-11 06:36
Thanks for this report. Do you have a script to share if possible as minimal as can be?

**Comment by Niall7459** [comment] 2018-07-11 11:39
‘’’#!/usr/bin/liquidsoap

set("log.file.path","/tmp/<script>.log")
set("log.stdout", true)

set("server.telnet", true)

hit_music = playlist("Greatest Hits/")
rap_music = playlist("Rap Music/")
radio = random(weights=[2,3],[hit_music,rap_music])
radio = crossfade(radio)
radio = amplify(1.,override="replay_gain",radio)

def transitionToLive(old,new) = 
  old = fade.final(old)
  new = fade.in(new)
  add([old,new])
end

def transitionToAuto(old,new) =
  old = fade.final(old)
  new = fade.in(new) 
  add([old,new])
end

vover = mksafe(input.http("http://192.168.111.103:8000/livevover.ogg"))
radio = add([radio,vover])
full = fallback(track_sensitive=false,transitions=[transitionToLive,transitionToAuto], [input.http("http://192.168.111.103:8000/liveinput.ogg"), crossfade(radio)]) 

output.icecast(%mp3(bitrate=128), 
  host="localhost",name="Nagar FM",description="Stay tuned for live shows.",port=8000,password="niallfm",
  mount="autodj.mp3",mksafe(full))
output.icecast(%mp3(bitrate=48), 
  host="localhost",name="Nagar FM",port=8000,password="niallfm",
  mount="autodjx.mp3",mksafe(full))

output.icecast(%vorbis, 
  host="localhost",port=8000,password="niallfm",
  mount="autodj.ogg",mksafe(full))
’’’

**Comment by toots** [comment] 2018-07-17 11:51
Hi @Niall7459,

Couple of additional questions:
- How did you install liquidsoap? If through opam or compiled yourself, what version of the OCaml compiler are you using?
- Are you in a position to deploy a test script and try to remove some of the operators? Half a day seems short enough to do so, for instance stating with removing one `output.icecast` then both and use `output.dummy`, remove one playlist etc. The idea would be to get to the point where removing one element makes the bug go away. That would help immensely to figure out where the issue is coming from.

Thanks for your help and patience.

**Comment by Yukioru** [comment] 2018-07-25 08:39
Hi @toots,
I have the same problem.

I tested it on different versions. The most stable is 1.3.1 with opam 1.2.0 from the Debian repository. OCaml version 4.01.0. (But this version loads CPU very much #475 )

I also tried to install the release version of opam 1.2.2 and the version of liquidsoap from 1.3.2 to 1.3.3-1, and also opam 2.0.0 beta 5 with liquidsoap 1.3.3. Version OCaml 4.05.0.

Attempts to reproduce were through the external encoder and through fdkaac. The decoder was used by the faad.

The result is the same. Stream just drops without killing the process.

The liquidsoap was assembled with the minimum configuration from opam + cry, faad, fdkaac, ladspa, samplerate.

### Below is the configuration and end of the logs on which I tested.
Judging by the logs, it almost always drops before or after the jingles.

**.log**
```
2018/07/25 00:11:49 [decoder:4] Trying method "MP4" for "/radio/collection/jingles/sg_preview.m4a"...
2018/07/25 00:11:49 [decoder.mp4:4] Libfaad recognizes "/radio/collection/jingles/sg_preview.m4a" as MP4 (44100Hz,2 channels).
2018/07/25 00:11:49 [decoder:3] Method "MP4" accepted "/radio/collection/jingles/sg_preview.m4a".
2018/07/25 00:11:49 [jingles:4] Remaining: 10.0s, queued: 0.0s, adding: 30.0s (RID 5)
2018/07/25 00:11:54 [smart_cross_10647:4] Buffering end of track...
2018/07/25 00:11:54 [smart_cross_10647:4] More buffering will be needed.
2018/07/25 00:11:55 [decoder:4] Decoding "/radio/collection/jingles/sg_preview.m4a" ended: Aac_decoder.Make_mp4(Generator).End_of_track.
2018/07/25 00:11:56 [jingles:3] Finished with "/radio/collection/jingles/sg_preview.m4a".
2018/07/25 00:11:56 [jingles:4] Remaining: 0.0s, queued: 30.0s, taking: 30.0s
2018/07/25 00:11:56 [jingles:3] Prepared "/radio/collection/jingles/sg_preview.m4a" (RID 5).
2018/07/25 00:11:56 [rotate_10643:3] Switch to mksafe with forgetful transition.
2018/07/25 00:11:56 [mksafe:4] Activations changed: static=[], dynamic=[rotate_10643:ladspa_10645:smart_cross_10647].
2018/07/25 00:11:56 [mksafe:4] Activations changed: static=[rotate_10643:ladspa_10645:smart_cross_10647], dynamic=[rotate_10643:ladspa_10645:smart_cross_10647].
2018/07/25 00:11:56 [smart_cross_10647:3] Analysis: -78.517370dB / -15.047655dB (5.02s / 1.98s)
2018/07/25 00:11:56 [joshcross:4] Before: ("kind","{audio=2;video=0;midi=0}")
2018/07/25 00:11:56 [joshcross:4] Before: ("decoder","MP4")
2018/07/25 00:11:56 [joshcross:4] Before: ("filename","/radio/collection/jingles/sg_preview.m4a")
2018/07/25 00:11:56 [joshcross:4] Before: ("temporary","false")
2018/07/25 00:11:56 [joshcross:4] Before: ("source","jingles")
2018/07/25 00:11:56 [joshcross:4] Before: ("initial_uri","/radio/collection/jingles/sg_preview.m4a")
2018/07/25 00:11:56 [joshcross:4] Before: ("playlist_length","1")
2018/07/25 00:11:56 [joshcross:4] Before: ("status","playing")
2018/07/25 00:11:56 [joshcross:4] Before: ("tool","qaac 2.67, CoreAudioToolbox 7.10.9.0, AAC-LC Encoder, CVBR 256kbps, Quality 96")
2018/07/25 00:11:56 [joshcross:4] Before: ("on_air","2018/07/25 00:11:20")
2018/07/25 00:11:56 [joshcross:4] Before: ("rid","0")
2018/07/25 00:11:56 [joshcross:4] Before: ("playlist_position","0")
```

**config.liq**
```
#!/usr/local/bin/liquidsoap

set("init.daemon.pidfile.path", "/radio/technical/liquidsoap/liquidsoap.pid")
%include "utils.liq"

set("decoder.stream_decoders",["MP4"])
set("decoder.file_decoders",["MP4"])
set("decoder.file_extensions.mp4",["m4a"])
set("decoder.mime_types.mp4",["audio/x-m4a"])

home = "/radio"
pl = "#{home}/collection"
muz = "#{pl}/music"
jin = "#{pl}/jingles"
logs = "#{home}/logs"

set("log.file.path", "#{logs}/liquidsoap.log")
set("log.level", 5)

music = mksafe(playlist("#{muz}"))
jingles = mksafe(playlist("#{jin}"))

stream = rotate(weights = [2, 1], [music, jingles])
stream = ladspa.matrixspatialiser(width = 3, stream)
stream = joshcross(stream)
stream = skip_blank(stream)

cfg = output.icecast(
	host = *********,
	port = ****,
	user = "source",
	password = *********,
	name = ************,
	description = ***********,
	genre = *******,
	url = ************,
	encoding = "UTF-8"
)

cfg(
	%external(
		channels = 2,
		samplerate = 44100,
		header = true,
		restart_on_crash = false,
		restart_on_metadata,
		restart_after_delay = 30,
		process="WINEDEBUG=-all /opt/wine-devel/bin/wine /radio/technical/qaac/qaac.exe -v 256 -q 2 --adts -s --log /radio/logs/qaac.log --threading --delay=0 --gapless-mode=2 --no-delay --rate=44100 - -o -"
	),
	mount = "source.aac",
	format = "audio/aac",
	stream
)


#cfg(
#	%fdkaac(
#		channels = 2,
#		samplerate = 44100,
#		vbr = 5,
#		afterburner = true,
#		aot = "mpeg4_aac_lc",
#		transmux = "adts",
#		sbr_mode = false
#	),
#	mount = "source.aac",
#	stream
#)

```
**utils.liq**
```
def joshcross (~start_next=5.,~fade_in=3.,~fade_out=3.,
                     ~default=(fun (a,b) -> sequence([a, b])),
                     ~high=-15., ~medium=-32., ~margin=4.,
                     ~width=2.,~conservative=false,s)
  fade.out = fade.out(type="sin",duration=fade_out)
  fade.in  = fade.in(type="sin",duration=fade_in)
  add = fun (a,b) -> add(normalize=false,[b, a])
  log = log(label="joshcross")

  def transition(a,b,ma,mb,sa,sb)

    list.iter(fun(x)-> log(level=4,"Before: #{x}"),ma)
    list.iter(fun(x)-> log(level=4,"After : #{x}"),mb)

    if ma["type"] == "J" or mb["type"] == "J" then
      log("Old or new file is a jingle: sequenced transition.")
      sequence([sa, sb])
    elsif
      # Do not fade if it's already very low.
      b >= a + margin and a <= medium and b <= high
    then
      log("new >= old + margin, old <= medium and new <= high.")
      log("Do not fade if it's already very low.")
      log("Transition: crossed, no fade.")
      add(sa,sb)

    else
      log("Transition: crossed, fade-in, fade-out.")
      add(fade.out(sa),fade.in(sb))
    end
  end

  smart_cross(width=width, duration=start_next, conservative=conservative,
              transition,s)
end

def skip_blank(~id="",~threshold=-40.,~max_blank=20.,~min_noise=0.,~track_sensitive=true,s)
  on_blank({source.skip(s)},threshold=threshold,max_blank=max_blank,min_noise=min_noise,track_sensitive=track_sensitive,s)
end
```

**Comment by toots** [comment] 2018-07-27 00:33
Hi,

Thank you very much for these details, this is super helpful.

Could you try to disable one by one the intermediate operators and see if the bug keeps happening? Start with removing ladspa, then the crossfade, then `skip_blank`. The idea would be to either narrow down a minimal script to reproduce the issue or single out one operator responsible for the bug.

Thanks!

**Comment by Yukioru** [comment] 2018-07-29 19:17
@toots 
From the past, the config has removed the jingles leaving only the tracks. So far, the config works 3 days without falling (_The last build of the master branch with ocaml 4.06.0 and opam 2.0.0 rc3_).

ladspa, skip_blank, crossfade has not deleted yet. 
I'll write more as more information appears.

**Comment by toots** [comment] 2018-07-30 22:33
Very interesting, thanks! Any specific audio format for the jingles that aren't used for the other tracks?

**Comment by toots** [comment] 2018-07-30 22:34
Sorry responding to myself: yes, it seems that they are in `m4a` format.

**Comment by toots** [comment] 2018-07-30 23:01
Ok, I've just pushed a cleanup of the `faad` decoder code. You might want to try with this. If you have installed via `opam`, you can simply do:
```
git clone https://github.com/savonet/ocaml-faad.git
cd ocaml-faad
opam pin faad
```
You will need `autotools`/`automake`.

**Comment by toots** [comment] 2018-07-31 04:55
(and a locally pinned `liquidsoap` and `ocaml-dtools` with the latest code. Same instructions)

**Comment by Yukioru** [comment] 2018-07-31 06:15
When assembling liquidsoap, a type error occurred.
```
OCAMLOPT -c decoder/aac_decoder.ml
File "decoder/aac_decoder.ml", line 91, characters 49-55:
Error: This expression has type string but an expression was expected of type
         bytes
../Makefile.rules:192: recipe for target 'decoder/aac_decoder.cmx' failed
make[2]: *** [decoder/aac_decoder.cmx] Error 2
make[2]: Leaving directory '/home/***/liquidsoap/src'
../Makefile.rules:67: recipe for target 'all-auto-ocaml-prog' failed
make[1]: *** [all-auto-ocaml-prog] Error 2
make[1]: Leaving directory '/home/***/liquidsoap/src'
Makefile.rules:27: recipe for target 'all-subdirs' failed
make: *** [all-subdirs] Error 2
```

**Comment by Niall7459** [comment] 2018-07-31 07:32
For me I can find that this can vary in duration of how long the stream works for.

Sometimes it can be 5 days, or 8 hours..
Although this _seems_ to closely match when another piece of software running crashed, the stream stayed working, when I restarted this other software, the stream went blank about 8 hours after.

I was running an instagram-bot. On a very low-end machine, maybe liquidsoap is running out of resources?

**Comment by toots** [comment] 2018-07-31 14:10
@Yukioru you will need to also use the latest liquidsoap & dtools code:
```
git clone https://github.com/savonet/ocaml-dtools.git
cd ocaml-dtools
opam pin add .

git clone https://github.com/savonet/liquidsoap.git
cd liquidsoap
opam pin add .
```

**Comment by toots** [comment] 2018-07-31 14:14
@Niall7459 lack of resources I don't think so. To me it looks like some kind of stack corruption, which is why I'm tempted to investigate the C part of the code, mostly the bindings. The OCaml part of the code has been well tested over the years, it'll be a real surprise to find an issue of that magnitude in it to me.

**Comment by Yukioru** [comment] 2018-07-31 16:04
@toots 
Of course, I used the latest versions, but something went wrong.
```
=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[ERROR] The compilation of liquidsoap failed at "make".
Processing  1/1: [liquidsoap: rm]
#=== ERROR while installing liquidsoap.dev ====================================#
# opam-version 1.2.2
# os           linux
# command      make
# path         /home/yorha/.opam/4.06.0/build/liquidsoap.dev
# compiler     4.06.0
# exit-code    2
# env-file     /home/yorha/.opam/4.06.0/build/liquidsoap.dev/liquidsoap-19022-e7966f.env
# stdout-file  /home/yorha/.opam/4.06.0/build/liquidsoap.dev/liquidsoap-19022-e7966f.out
# stderr-file  /home/yorha/.opam/4.06.0/build/liquidsoap.dev/liquidsoap-19022-e7966f.err
### stdout ###
# [...]
# OCAMLOPT -c decoder/image_decoder.ml
# OCAMLOPT -c decoder/image/ppm_decoder.ml
# OCAMLOPT -c decoder/external_decoder.ml
# OCAMLOPT -c decoder/raw_audio_decoder.ml
# OCAMLOPT -c decoder/aac_decoder.ml
# ../Makefile.rules:192: recipe for target 'decoder/aac_decoder.cmx' failed
# make[2]: Leaving directory '/home/yorha/.opam/4.06.0/build/liquidsoap.dev/src'
# ../Makefile.rules:67: recipe for target 'all-auto-ocaml-prog' failed
# make[1]: Leaving directory '/home/yorha/.opam/4.06.0/build/liquidsoap.dev/src'
# Makefile.rules:27: recipe for target 'all-subdirs' failed
### stderr ###
# Use String.uppercase_ascii instead.
# [...]
# File "io/oss_io.ml", line 149, characters 12-25:
# Warning 3: deprecated: String.create
# Use Bytes.create instead.
# File "decoder/aac_decoder.ml", line 91, characters 49-55:
# Error: This expression has type string but an expression was expected of type
#          bytes
# make[2]: *** [decoder/aac_decoder.cmx] Error 2
# make[1]: *** [all-auto-ocaml-prog] Error 2
# make: *** [all-subdirs] Error 2
```

**Comment by toots** [comment] 2018-07-31 16:12
I believe this was fixed in commit a6d3813

**Comment by Yukioru** [comment] 2018-07-31 16:16
```
~/liquidsoap(master ✔) git checkout
Your branch is up-to-date with 'origin/master'.
```
I also took the last commit.
```
commit a6d381359d1ca19b62efd679e2ddd3baa9a64449
Author: Romain Beauxis <toots@rastageeks.org>
Date:   Mon Jul 30 23:53:36 2018 -0500

    Bump faad, adapt to new API, use Bytes.to_unsafe_string when possible.
```

**Comment by toots** [comment] 2018-07-31 16:18
Hmm. And you're using https://github.com/savonet/ocaml-faad/commit/2e0593d4e49b90350d39af3a754f0ba589d23dba ?

**Comment by toots** [comment] 2018-07-31 16:19
Also make sure to update the pinned copy, just in case:
```
opam update liquidsoap
```

**Comment by Yukioru** [comment] 2018-07-31 16:28
I had to modify liquidsoap.opam, because ocaml-mm needs 0.4.0 versions from the master branch. (I collected it manually, not through opam) and the problem with the assembly is the same.

**Comment by toots** [comment] 2018-07-31 16:48
Ok, should be fixed now.

**Comment by Yukioru** [comment] 2018-07-31 16:54
Heh. Now 128 line. https://github.com/savonet/liquidsoap/blob/master/src/decoder/aac_decoder.ml#L128
```
# File "decoder/aac_decoder.ml", line 128, characters 41-47:
# Error: This expression has type string but an expression was expected of type
#          bytes
```

**Comment by toots** [comment] 2018-07-31 18:33
Ok, I was compiling with the wrong version of OCaml. Fixed now.

**Comment by Niall7459** [comment] 2018-08-02 17:48
Will this push changes to apt-get?

**Comment by Yukioru** [comment] 2018-08-03 08:57
@toots, with jingles also falls. I will test further - the result will be reported.

**Comment by toots** [comment] 2018-08-03 16:13
Ok, thanks. I'm definitely investigating it as a stack corruption in the faad decoder.

I've pushed another cleanup of the GC/callback code. There's a small chance that it could fixe the issue, feel free to test when you get a chance. Thks!

**Comment by toots** [comment] 2018-08-07 14:19
Any update on this one?

**Comment by Yukioru** [comment] 2018-08-07 16:16
@toots, I have updated the packages correctly?
Updated: fadd, dtools, liquidsoap
```
cd ./package
git pull
opam pin add.
opam upgrade package
```
I doubt it, because there was no reassembly.

**Comment by toots** [comment] 2018-08-07 16:20
You can always try: `opam reinstall <package>`

**Comment by Yukioru** [comment] 2018-08-07 16:20
ok

**Comment by Yukioru** [comment] 2018-08-07 17:53
@toots The stream also falls. 😫 
I'm going to turn off the processing.

**Comment by toots** [comment] 2018-08-07 22:36
Yes, the processing could be another possible culprit, let us know if that changes anything..

**Comment by Yukioru** [comment] 2018-08-11 07:00
Eventually.
From my script I turned off the processing one at a time:
- ladspa;
- skip_blank;
- joshcross.

After the first two the stream also fell.
After disabling joshcross, the stream has been running for 2 days without falling.

It's all with jingles on.

-----------------------------------------
Let me remind you what the joshcross script looks like:
```
def joshcross (~start_next=5.,~fade_in=3.,~fade_out=3.,
                     ~default=(fun (a,b) -> sequence([a, b])),
                     ~high=-15., ~medium=-32., ~margin=4.,
                     ~width=2.,~conservative=false,s)
  fade.out = fade.out(type="sin",duration=fade_out)
  fade.in  = fade.in(type="sin",duration=fade_in)
  add = fun (a,b) -> add(normalize=false,[b, a])
  log = log(label="joshcross")

  def transition(a,b,ma,mb,sa,sb)

    list.iter(fun(x)-> log(level=4,"Before: #{x}"),ma)
    list.iter(fun(x)-> log(level=4,"After : #{x}"),mb)

    if ma["type"] == "J" or mb["type"] == "J" then
      log("Old or new file is a jingle: sequenced transition.")
      sequence([sa, sb])
    elsif
      # Do not fade if it's already very low.
      b >= a + margin and a <= medium and b <= high
    then
      log("new >= old + margin, old <= medium and new <= high.")
      log("Do not fade if it's already very low.")
      log("Transition: crossed, no fade.")
      add(sa,sb)

    else
      log("Transition: crossed, fade-in, fade-out.")
      add(fade.out(sa),fade.in(sb))
    end
  end

  smart_cross(width=width, duration=start_next, conservative=conservative,
              transition,s)
end
```

**Comment by Niall7459** [comment] 2018-08-11 07:11
Recent changes I have made:
- more songs have been added
- crossfade() added

This has made the stream fail every 8 or so hours. Before, I had crossfade() but it was in the wrong place and not taking effect. I can hear the crossfade s

I think the problem is cross fading

Also I’m on Linux and I use apt-get to install liquid soap. How can I pull changes or should I build it.

**Comment by toots** [comment] 2018-08-12 14:50
Thanks guys for these, this is extremely helpful. Let's try one last thing to narrow it down: @Yukioru, could you try to change the `sequence([sa, sb])` transition in the jingle case to `add(sa,sb)` like in the other case? I'm trying to figure out if the problem comes from the `sequence` operator or the `smart_cross` operator himself. Thanks so much!

**Comment by Yukioru** [comment] 2018-08-12 15:26
@toots OK. Replaced. Restarted the stream. Let's see how it will work.

**Comment by Yukioru** [comment] 2018-08-13 09:02
@toots It still falls.
```
2018/08/12 23:29:50 [source:4] Source add_12534 gets up.
2018/08/12 23:29:50 [add_12534:4] Content kind is {audio=2;video=0;midi=0}.
2018/08/12 23:29:50 [source:4] Source smart_cross_5951_after gets up.
2018/08/12 23:29:50 [source:4] Source buffer_12492 gets up.
2018/08/12 23:29:50 [buffer_12492:4] Content kind is {audio=2;video=0;midi=0}.
2018/08/12 23:29:50 [buffer_12492:4] Activations changed: static=[smart_cross_5951_after:add_12534:smart_cross_5951], dynamic=[].
2018/08/12 23:29:50 [rotate_5949:4] Activations changed: static=[smart_cross_5951_after:add_12534:smart_cross_5951, smart_cross_5951_after:fad$2018/08/12 23:29:50 [rotate_5949:4] Enabling caching mode: two static activations.
2018/08/12 23:29:50 [smart_cross_5951_after:4] Activations changed: static=[add_12534:smart_cross_5951], dynamic=[].
2018/08/12 23:29:50 [source:4] Source smart_cross_5951_before gets up.
2018/08/12 23:29:50 [smart_cross_5951_before:4] Content kind is {audio=2;video=0;midi=0}.
2018/08/12 23:29:50 [smart_cross_5951_before:4] Activations changed: static=[add_12534:smart_cross_5951], dynamic=[].
```

**Comment by toots** [comment] 2018-08-13 13:26
Gotcha, thanks. On it!

**Comment by toots** [comment] 2018-08-13 22:11
@Yukioru Any chance you could share a bit more of the logs? Something showing the whole transition would be great.

**Comment by Yukioru** [comment] 2018-08-14 06:06
@toots 
[liquidsoap.log.txt](https://github.com/savonet/liquidsoap/files/2285672/liquidsoap.log.txt)

**Comment by toots** [comment] 2018-08-14 15:59
Ok, thanks. I'm a bit confused now. The initial description of the issue was:
> After about half a day, my stream does not output music but continues to show loading songs in terminal. I need to restart the program to get the stream back

Is that what you are experiencing?

**Comment by Yukioru** [comment] 2018-08-14 16:18
Hmmm. Maybe partly yes.
In the original description it is not clear whether the stream itself is still available and there is just silence?

If so, then maybe I did not understand the problem correctly. 😕 

In my case, the liquidsoap process remains working, but the tracks stop playing (the stream itself is not available at the same time).

If you think this is wrong, I can recreate the issue for my case.

**Comment by toots** [comment] 2018-08-14 16:20
Thanks for the clarification. @Niall7459 is that also what you are experiencing?

**Comment by Yukioru** [comment] 2018-08-14 16:51
@toots Let me create a new problem. I was wrong with the wording of the problem in this topic.

I did not find any similar problems. As I understand, all the problems with the silence in the stream.

Sorry for the comments off topic. And yet, can I hope that the problem will be solved in 1.2.4?

**Comment by toots** [comment] 2018-08-14 18:41
I'm not sure that you were off-topic and, yeah, I'm not gonna let this one go now that we're so close to fixing it :-)

**Comment by Yukioru** [comment] 2018-08-14 18:44
Anyway, it seems to me better to continue in the right topic? )

**Comment by Niall7459** [comment] 2018-08-14 21:43
Yep, in my case tracks are still prepared, the stream is still available, sending metadata, just no audio.

I have my icecast server at http://listen.nagar.eu:8000/

And the stream url is http://listen.nagar.eu:8000/autodj.mp3
(working at the time of writing)

 64-bit architecture. I used apt and can confirm I’m running 1.1.1

I will attempt an update tommorow morning.
I believe I’m using Debian 8 (Rasbian)

I can also do tests on other systems and see what happens.

**Comment by Niall7459** [comment] 2018-08-14 21:56
Just wanted to say, thanks for this amazing piece of software, I’ve used VLC, WinAMP but nothing has come close to compatibility/features of liquidsoap. It’s perfect for radio automation and extremely lightweight to run! Good luck!

**Comment by toots** [comment] 2018-08-15 14:13
@Niall7459, I'm gonna close this one here for house keeping. I am focused on issues on the recent code and this one hasn't been reported since `1.1.1`. However, feel free to re-open or submit a new one if you experience it with the latest code. Thks!

**Comment by toots** [comment] 2018-08-15 14:16
Oh also, thanks for the kind words, much appreciated!

**Comment by Niall7459** [comment] 2018-08-15 15:07
@toots 
![screen shot 2018-08-15 at 16 05 20](https://user-images.githubusercontent.com/9781846/44155471-4e4ebc8a-a0a5-11e8-96d5-bac4c26b682f.png)

not yet on our lists :(

**Comment by Niall7459** [comment] 2018-08-15 15:08
Il check on my ubuntu system

**Comment by Niall7459** [comment] 2018-08-15 15:10
nope, I can attempt a build but it probably wont work for me

**Comment by Yukioru** [comment] 2018-08-15 16:26
https://github.com/savonet/liquidsoap/issues/572#issuecomment-413228714 @Niall7459 
You need to use opam to install the latest version. Or manually collect from the repository.

https://opam.ocaml.org/

**Comment by Niall7459** [comment] 2018-08-15 16:48
@Yukioru I've installed 1.3.3-1 but when i run 'liquidsoap' its still running version 1.1.1 that I installed using apt. Has opam installed it somewhere different so I can make an alias to it. Thanks

**Comment by Yukioru** [comment] 2018-08-15 16:51
@Niall7459  The installed liquidsoap through the opam is in the home directory.
For example: `/home/username/.opam/bin/liquidsoap` or `/home/username/.opam/4.05.0/bin/liquidsoap`

**Comment by Niall7459** [comment] 2018-08-15 17:00
@Yukioru  Thanks, It's there but...
![screen shot 2018-08-15 at 17 59 19](https://user-images.githubusercontent.com/9781846/44161386-0e0c1e00-a0b5-11e8-977e-418eb83c5d97.png)

I have to use ./liquidsoap or it runs from command and not binary

**Comment by Niall7459** [comment] 2018-08-22 20:37
Current script that I’m having problems with

‘’’#!/usr/bin/liquidsoap

set("log.file.path","/tmp/<script>.log")
set("log.stdout", true)

set("server.telnet", true)
set("server.telnet.bind_addr","0.0.0.0")
set("server.telnet.port",1717)
set("server.telnet.reverse_dns",true)

hit_music = crossfade(playlist("/home/pi/Desktop/NagarFM/Greatest Hits/",reload_mode="watch"))
rap_music = playlist("/home/pi/Desktop/NagarFM/Rap Music/",reload_mode="watch")
#twok_music = playlist("2000s/", reload_mode="watch")
radio = random(weights=[7,1],[hit_music,rap_music])

radio = crossfade(radio)
radio = amplify(1.,override="replay_gain",radio)


#radio = switch([ ({19h-01h}, twok_music), ({01h-19h}, radio) ], track_sensitive=true)

def transitionToLive(old,new) = 
  old = fade.final(old)
  new = fade.in(new)
  add([old,new])
end

def transitionToAuto(old,new) =
  old = fade.final(old)
  new = fade.in(new) 
  add([old,new])
end

vover = mksafe(input.http("http://192.168.111.103:8000/livevover.ogg"))
radio = add([radio,vover])
full = fallback(track_sensitive=false,transitions=[transitionToLive,transitionToAuto], [input.http("http://192.168.111.103:8000/liveinput.ogg"), crossfade(radio)]) 

output.icecast(%mp3(bitrate=128), 
  host="localhost",name="Nagar FM",description="Playing the latest and greatest music until 6 PM. Join us at 6 PM for party and rap music.",port=8000,password="niallfm",
  mount="autodj.mp3",mksafe(full))
output.icecast(%mp3(bitrate=64), 
  host="localhost",name="Nagar FM",port=8000,password="niallfm",
  mount="autodjx.mp3",mksafe(full))

output.icecast(%vorbis, 
  host="localhost",port=8000,password="niallfm",
  mount="autodj.ogg",mksafe(full))
’’’

**Comment by Niall7459** [comment] 2018-08-22 20:38
I was thinking earlier maybe it’s the mksafe() coming into action producing a blank stream of the sources are failing

**Comment by Niall7459** [comment] 2018-08-22 20:40
Also @toots I attempted opam install of liquidsoap and I get this error on run.

https://user-images.githubusercontent.com/9781846/44161386-0e0c1e00-a0b5-11e8-977e-418eb83c5d97.png
^ above imagd

**Comment by gilou** [comment] 2018-08-27 14:05
You probably need to install cry as well

**Comment by Niall7459** [comment] 2018-09-03 13:33
@toots tested this on a different machine, using the liquidsoap-win binarys and same problem occured.

**Comment by Niall7459** [comment] 2018-09-03 13:33
Any update on this?

**Comment by toots** [comment] 2018-09-03 16:17
@Niall7459, you're using the latest script above right? Symptoms are: stream goes silent but logs continue to show tracks being loaded? Can you share logs with `set("log.level",5)`? Thks!

**Comment by Niall7459** [comment] 2018-09-03 17:38
Okay il get that set now, I’ve also noticed since I’ve tried it on windows, it’s a lot quicker to fail (about 4 hours compared to 8ish)

Wondering if it’s down to the specs of the system? Il set the log level to 5

**Comment by Niall7459** [comment] 2018-09-03 17:46
Okay I’ve stup the log levels but I’ve taken out http features as this was spamming the logs

**Comment by Niall7459** [comment] 2018-09-03 18:11
the quicker failing on the windows machine might have been due to other issues not liquidsoap related, Il edit the script on my raspberry pi and see what happens anything I should specifically look out for (il upload entire log aswell)

**Comment by Niall7459** [comment] 2018-09-03 18:40
I’ve set it all up on log level 5 and will see later on today or tommorow what happens

**Comment by Niall7459** [comment] 2018-09-04 08:09
@toots Is there anything I should specifically look for in the log files?

**Comment by Niall7459** [comment] 2018-09-04 08:27
https://drive.google.com/file/d/1tZj3CpqBLZhVpD4ONiIWn_ppUvJLnapc/view?usp=sharing

**Comment by toots** [comment] 2018-09-05 15:09
Thank you. I'll give it a try when I get a moment.

**Comment by toots** [comment] 2018-09-06 00:48
Hi. I should have looked at your script before. You should remove the `mksafe` around `input.http`. Otherwise, once the `fallback` switches to that source it'll never switch back to the other source because `mksafe` guarantees that source to always be available, even when `input.http` fails, in which case you will indeed stream blank. This should fix your problem. Gonna close here. Please re-open if needed.

**Closed by toots** 2018-09-06 00:48 UTC
Labels: bug

**Comment by Niall7459** [comment] 2018-09-07 06:45
Thanks! Il try it overnight and see what happens

**Comment by Niall7459** [comment] 2018-09-07 16:32
@toots all seems fine, no falling of the stream (~2 days going) another slightly unrelated thing over telnet what should request.all show?

Currently it shows this after about 12 hours running: 
![screen shot 2018-09-07 at 17 30 39](https://user-images.githubusercontent.com/9781846/45231404-c3508100-b2c3-11e8-85cc-df0ff5be9067.png)

I have about 100 audio files and wondering why only these show?

**Comment by toots** [comment] 2018-09-07 17:07
Glad to know! `request.all` should only show queued or currently playing requests so that's to be expected.

**Comment by Niall7459** [comment] 2018-09-07 20:01
Ok thanks! Final question, is there anyway we can add a password for the telnet protocol?

**Comment by toots** [comment] 2018-09-07 20:07
You can add SSH access. It's actually a neat trick, it's described here: http://www.liquidsoap.info/doc-1.3.3/server.html

**Comment by Niall7459** [comment] 2018-09-08 08:28
Ok thanks!

**Comment by Niall7459** [comment] 2018-09-08 09:07
@toots is there a telnet/say command to view all available songs? I mean like return all the ids of every song

**Comment by Niall7459** [comment] 2018-09-08 14:40
Sometimes if I request to skip tracks this happens:
![screen shot 2018-09-08 at 15 35 15](https://user-images.githubusercontent.com/9781846/45255374-7a5d0300-b37d-11e8-8704-1a776d5079c3.png)
