### ISSUE TITLE
 LS 2.2.0+git@dcf405ff4: Alpha=00 ignored in `video.add_rectangle(color=0xAARRGGBB, …)`

### ISSUE THREAD

**Issue by Moonbase59** [savonet/liquidsoap#3160] opened 2023-06-20 00:04 UTC
**Describe the bug**
A small oversight probably: Alpha values of 0x00 in `video.add_rectangle(color=0xAARRGGBB, …` are ignored and produce a solid color instead.

**To Reproduce**
Minimal script:
```
#
# Alpha 00 ignored in video.add_rectangle()
#

v = video.testsrc(width=1280, height=720)

# this should not display (fully transparent AARRGGBB)
# but shows as a red rectangle (transparency ignored if =00)
v = video.add_rectangle(color=0x00eb0000, height=30, width=320, x=0, y=532, v)

# this is a bad workaround (use alpha =01 instead)
v = video.add_rectangle(color=0x01eb0000, height=30, width=320, x=0, y=562, v)

output.sdl(v)
```

Current workaround: Use alpha=0x01 instead, which is _almost_ fully transparent but normally not distinguishable.

**Expected behavior**
Alpha=0x00 work and "display" a fully transparent color. This is sometimes needed to hide something that is actually there, like my "Live: " indicator, which shall only show when a live DJ is connected (I use this with _AzuraCast_):

![video m2t - VLC media player_010](https://github.com/savonet/liquidsoap/assets/3706922/51d80251-1ed7-4aba-97b0-fda17005d53e)

**Version details**

- OS: Linux Mint 21.1, Ubuntu 22.04 LTS Docker
- LS Version: 2.2.0+git@dcf405ff4

**Install method**
`.deb` from release-assets.

**Comment by smimram** [comment] 2023-06-20 08:59
Yes, I know :) The problem is with backward compatibility: we want to consider that 0xRRGGBB is a solid color and 0x00RRGGBB is a transparent color, but the two are the same integer...

I think that the best solution is to add an argument `alpha` for the alpha channel, which I propose to be a float between 0 and 1 (rather than an int between 0 and 0xff). What do you think?

**Comment by Moonbase59** [comment] 2023-06-20 10:35
Hmm. Maybe too complicated? We’re already suffucating from "featuritis" a little… ;-) I _think_ most people (like me) are used to a bytewise HTML hex notation (which we almost have by using `0xAARRGGBB`).

I wonder what the current HTML/CSS standards are—do they use RGBA or ARGB? (I think LS should use as many standardized things as possible.)

I see that exactly _that_ might be the reason why so many use RGBA instead of ARGB—it’s just an 8-bit shift to drop the alpha, and we have different (long) int’s.

**Comment by toots** [comment] 2023-06-20 14:26
Changing the arguments can be done in a backward compatible way. I understand the thoughts around features changing but features not changing also leads to people having -- and reporting -- the same problem over and over..

@smimram can we add a new, separate parameter and still accept the old one with a warning that it shouldn't be used anymore?

**Comment by toots** [comment] 2023-06-20 14:27
@Moonbase59 Doing RRGGBBAA would lead to complexity for users who don't need transparency right out of the box. We usually try to have the first setup simple and complex things popping out only when needed.

**Comment by toots** [comment] 2023-06-20 22:32
This was fixed with PR #3162

**Closed by toots** 2023-06-20 22:32 UTC

**Comment by Moonbase59** [comment] 2023-06-21 07:15
Thanks, will test hopefully tomorrow.

**Comment by Moonbase59** [comment] 2023-06-21 09:24
Confirmed working fine, suing https://github.com/savonet/liquidsoap-release-assets/releases/download/rolling-release-v2.2.x/liquidsoap-6469ce0_2.2.0-ubuntu-jammy-1_amd64.deb on both Linux Mint 21.1 and Ubuntu Server 22.04.2 LTS in AzuraCast Docker.
