### ISSUE TITLE
Error: Failed to build Liquidsoap

### ISSUE THREAD

**Issue by orassr** [savonet/liquidsoap#1434] opened 2020-12-11 01:58 UTC
```
Checking Centova Cast Common Files ...
Not updated, skipping
Checking Centova Cast Application Server ...
Not updated, skipping
Checking Centova Cast Image Daemon ...
Not updated, skipping
Checking Centova Cast Web Server ...
Not updated, skipping
Checking Centova Cast Comet Daemon ...
Not updated, skipping
Checking Centova Cast Control Daemon ...
Not updated, skipping
Checking Centova Cast FTP Server ...
Not updated, skipping
Checking IceCast ...
Not updated, skipping
Checking Liquidsoap ...
Downloading Liquidsoap ...
Verifying archive integrity ...
Unpacking archive ...

Installing Liquidsoap ...


Installing opam and dependencies...

opam 2.0.5 already installed, skipping
Reading package lists... Done
Building dependency tree
Reading state information... Done
gzip is already the newest version (1.6-5ubuntu1).
m4 is already the newest version (1.4.18-1).
make is already the newest version (4.1-9.1ubuntu1).
unzip is already the newest version (6.0-21ubuntu1).
bubblewrap is already the newest version (0.2.1-1ubuntu0.1).
bzip2 is already the newest version (1.0.6-8.1ubuntu0.2).
file is already the newest version (1:5.32-2ubuntu0.4).
g++ is already the newest version (4:7.4.0-1ubuntu2.3).
gcc is already the newest version (4:7.4.0-1ubuntu2.3).
patch is already the newest version (2.7.6-2ubuntu1.1).
tar is already the newest version (1.29b-2ubuntu0.1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

Setting up ocaml compiler toolchain ...


User configuration:
  ~/.profile is already up-to-date.
[NOTE] Make sure that ~/.profile is well sourced in your ~/.bashrc.


<><> Updating package repositories ><><><><><><><><><><><><><><><><><><><><><><>
[default] no changes from https://opam.ocaml.org
O caml, my caml!
[NOTE] Package opam-depext is already installed (current version is 1.1.5).

Installing OS package dependencies ...

Reading package lists... Done
Building dependency tree
Reading state information... Done
Note, selecting 'libsamplerate0-dev' instead of 'libsamplerate-dev'
libflac-dev is already the newest version (1.3.2-1).
libmp3lame-dev is already the newest version (3.100-2).
libogg-dev is already the newest version (1.3.2-1).
libpcre3-dev is already the newest version (2:8.39-9).
libsamplerate0-dev is already the newest version (0.1.9-1).
libtag1-dev is already the newest version (1.11.1+dfsg.1-0.2build2).
libvorbis-dev is already the newest version (1.3.5-4.2).
m4 is already the newest version (1.4.18-1).
pkg-config is already the newest version (0.29.1-0ubuntu2).
ladspa-sdk is already the newest version (1.13-3ubuntu2).
libfdk-aac-dev is already the newest version (0.1.5-1).
libmagic-dev is already the newest version (1:5.32-2ubuntu0.4).
libmad0-dev is already the newest version (0.15.1b-9ubuntu18.04.1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

Building Liquidsoap ...

[NOTE] Package fdkaac is already installed (current version is 0.2.1).
[NOTE] Package magic is already installed (current version is 0.7.3).
[NOTE] Package ladspa is already installed (current version is 0.2.0).
[NOTE] Package flac is already installed (current version is 0.1.4).
[NOTE] Package samplerate is already installed (current version is 0.1.5).
[NOTE] Package cry is already installed (current version is 0.6.5).
[NOTE] Package vorbis is already installed (current version is 0.7.1).
[NOTE] Package lame is already installed (current version is 0.3.4).
[NOTE] Package mad is already installed (current version is 0.4.5).
[NOTE] Package taglib is already installed (current version is 0.3.6).
The following actions will be performed:
  ∗ install liquidsoap 1.3.7

<><> Gathering sources ><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
[liquidsoap.1.3.7] found in cache

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
[ERROR] The compilation of liquidsoap failed at "/usr/local/centovacast/.opam/opam-init/hooks/sandbox.sh build make".

#=== ERROR while compiling liquidsoap.1.3.7 ===================================#
# context     2.0.5 | linux/x86_64 | ocaml-base-compiler.4.07.1 | https://opam.ocaml.org#fb801efd
# path        ~/.opam/4.07.1/.opam-switch/build/liquidsoap.1.3.7
# command     ~/.opam/opam-init/hooks/sandbox.sh build make
# exit-code   2
# env-file    ~/.opam/log/liquidsoap-4267-6d07ae.env
# output-file ~/.opam/log/liquidsoap-4267-6d07ae.out
### output ###
# [...]
# File "operators/ladspa_op.ml", line 90, characters 8-30:
# Error: This function has type
#          Ladspa.Descriptor.t -> int -> Ladspa.Descriptor.instance
#        It is applied to too many arguments; maybe you forgot a `;'.
# ../Makefile.rules:196: recipe for target 'operators/ladspa_op.cmx' failed
# make[2]: *** [operators/ladspa_op.cmx] Error 2
# make[2]: Leaving directory '/usr/local/centovacast/.opam/4.07.1/.opam-switch/build/liquidsoap.1.3.7/src'
# ../Makefile.rules:67: recipe for target 'all-auto-ocaml-prog' failed
# make[1]: *** [all-auto-ocaml-prog] Error 2
# make[1]: Leaving directory '/usr/local/centovacast/.opam/4.07.1/.opam-switch/build/liquidsoap.1.3.7/src'
# Makefile.rules:27: recipe for target 'all-subdirs' failed
# make: *** [all-subdirs] Error 2

<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
┌─ The following actions failed
│ λ build liquidsoap 1.3.7
└─
╶─ No changes have been performed
! Error: Failed to build Liquidsoap
! Error: Installation failed
Liquidsoap installation failed
Installer exited with error, aborting
```

**Comment by yasircs4** [comment] 2021-03-06 11:03
i have same issue, @orassr did you find any solution ?

**Comment by sfj8872** [comment] 2021-03-07 17:20
I actually just ran into this same issue this is a known issue caused by the lack of dependency checks in the package manager used by Liquidsoap

If this is a fresh install, just run the following

su -s /bin/bash ccuser -c 'opam pin ladspa 0.1.5'

then try install of liquidsoap again

/usr/local/centovacast/sbin/update --add liquidsoap


If however you are updating from a previous version

mv /usr/local/centovacast/.opam /usr/local/centovacast/opam_old

then do liquidsoap install

i had a issue installing it with a fresh install and had to contact support to figure out what was happening and they gave me these instructions

**Comment by yasircs4** [comment] 2021-03-15 13:55
thanks @sfj8872 , it's work like charm

**Comment by smimram** [comment] 2021-07-26 14:18
Looks like @sfj8872 has provided a decent solution, closing, feel free to reopen.

**Closed by smimram** 2021-07-26 14:18 UTC
Labels: usage

**Comment by orassr** [comment] 2022-05-18 01:04
I guess Centova team found a fix for your fix :( @sfj8872
